### ISSUE TITLE
Modify warning message to reflect new rendering capabilities with node-mapnik server

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#100]
Our current warning triangle message is out of date with the mapnik server rendering capabilities.  We should change any warning messages from "Zoom in to view data" to "Zoom in to _Edit_ data" etc.  We may simply remove the warning all together as we no longer need to provide an indication that features are hidden from view.

**Comment by sisskind** [comment]
@mjeffe98 Like the idea of changing to 'Zoom to edit data'.  @brianhatchl any objections?

**Comment by sisskind** [comment]
@mjeffe98 ready for test
