### ISSUE TITLE
Add a UI test for poi/poly merging

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#1020]

**Comment by maxgrossman** [comment]
Ticket resurrection!
Found a bug where UI allows us to merge poly->poi, which hoot knows and switches the direction for us. However, subsequent attempts to merge reviews that included the initial poi are still provided to the user, but upon trying to merge the element merger service (rightfully) responds error messages that the ui just does not know how to handle.

Per @bwitham's suggestion, let's just disallow the poly->poi direction in the merge ui; only poi->poly

**Comment by brianhatchl** [comment]
Is there a good POI-to-Poly dataset in `hoot/test-files` that displays these multiple reviews?

**Comment by bwitham** [comment]
[These files](https://github.com/ngageoint/hootenanny/tree/master/test-files/cmd/glacial/PoiPolygonConflateStandaloneTest) maybe. May need to crop them smaller for this.

**Comment by jackgrossman18** [comment]
i had been using these 
[Hokkaido_poi_to_poly.zip](https://github.com/ngageoint/hootenanny-ui/files/4394273/Hokkaido_poi_to_poly.zip)
