### ISSUE TITLE
Basemap is not displaying on develop version

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#104]
When I try to switch to the custom basemap as a background layer nothing displays.    Some 404 errors in the console but nothing jumps out.  Note that it was working on the 0.2.19 release version.

**Comment by mjeffe98** [comment]
I think we want to make sure the new release that is cut doesn't inherit this bug

**Comment by sisskind** [comment]
@mjeffe98 wouldnt this be identified in testing of release branch?

**Comment by mjeffe98** [comment]
@sisskind it would but it was working in the release and it looks like we are going to replace a functioning basemap upload capability with a non-functional when develop is merged with release.  I suppose we can lower the priority and make this a regression fix.

**Comment by mjeffe98** [comment]
Basemap *does* appear on new release candidate 8093 but not in the develop branch.  @jchoi1267 could be a configuration issue on 8091 since there is no error message in the dev console?  I think the release branch version has the same code that develop has (or had at the time of the first diagnosis of this issue) and most likely would have been impacted during the merge of develop into release.

**Comment by jchoi1267** [comment]
Yup, this was caused by static path issue. Fixed path we will see if that works tomorrow..

**Comment by mjeffe98** [comment]
So is this fixed and ready for test @jchoi1267 ?

**Comment by jchoi1267** [comment]
tested on selma and works
