### ISSUE TITLE
Design the display of conflation stats in the UI

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#105]
Running conflate with the `--stats` options produces output (shown below) that the user might want to see for gauging the performance of the conflation.  Currently the UI just shows number of review items.

Questions to consider:
* Should we run stats with every conflate command?  or add an option to the UI?
* On command line, stats seems to direct to stdout, is there a way to capture to file?
* Can we use metadata kvp to retain stats of a conflation job?
* Should stats added to the review ui or in a popup after conflation completes?
* Should there be a way to access stats ui via datasets tab (do we run stats on demand?)  Seems we're interested in preserving conflation performance for merged datasets, so would have to persist; check for stats metadata, run stats on single dataset if absent, just retrieve if present.

Proposed subset of stats for the UI:
* Show counts of nodes, ways, relations for each input and merged output
* Show counts of pois, highways, buildings for each input and merged output
* Show percent untouched, percent conflated, percent marked review for merged output

Sample output:
```
stats = (stat) OR (input map 1 stat) (input map 2 stat) (output map stat)
Node Count  337 156 483
Total Feature Tags  978 468 1433
Total Feature Information Tags  641 312 950
Total Feature Metadata Tags 337 156 483
Unique Names    323 152 475
Total Feature Count 337 156 483
Total Conflatable Features  337 156 0
Percentage of Total Features Conflatable    100 100 0
Total Unconflatable Features    0   0   0
Percentage of Total Features Unconflatable  0   0   0
Total Features Processed By Conflation  0   0   10
Number of Match Creators    3   3   3
Features Conflatable by: hoot::BuildingMatchCreator 0   0   0
Features Conflatable by: hoot::PlacesPoiMatchCreator    337 156 0
Features Conflatable by: hoot::HighwayMatchCreator  0   0   0
Total Conflated Features    0   0   10
Percentage of Total Features Conflated  0   0   2.0703933747412009
Total Features Marked for Review    0   0   0
Percentage of Total Features Marked for Review  0   0   0
Total Number of Reviews to be Made  0   0   0
Total Unmatched Features    337 156 473
Percentage of Total Features Unmatched  100 100 97.929606625258799
POI Count   337 156 483
Conflatable POIs    337 156 0
Conflated POIs  0   0   10
POIs Marked for Review  0   0   0
Number of POI Reviews to be Made    0   0   0
Unmatched POIs  337 156 473
Percentage of POIs Conflated    0   0   2.0703933747412009
Percentage of POIs Marked for Review    0   0   0
Percentage of Unmatched POIs    100 100 97.929606625258799
Highway Count   0   0   0
Conflatable Highways    0   0   0
Conflated Highways  0   0   0
Highways Marked for Review  0   0   0
Number of Highway Reviews to be Made    0   0   0
Unmatched Highways  0   0   0
Meters of Highway Processed by Conflation   0   0   0
Percentage of Highways Conflated    0   0   0
Percentage of Highways Marked for Review    0   0   0
Percentage of Unmatched Highways    0   0   0
Building Count  0   0   0
Conflatable Buildings   0   0   0
Conflated Buildings 0   0   0
Buildings Marked for Review 0   0   0
Number of Building Reviews to be Made   0   0   0
Unmatched Buildings 0   0   0
Meters Squared of Buildings Processed by Conflation 0   0   0
Percentage of Buildings Conflated   0   0   0
Percentage of Buildings Marked for Review   0   0   0
Percentage of Unmatched Buildings   0   0   0
Longest Tag 57  63  63
Translated Populated Tag Percent    0.25    0.054734169653524491    0.072788277184333061
Translated Populated Tag Count  337 733 1063
Translated Default Tag Count    1011    10664   11561
Translated Null Tag Count   0   1995    1980
Building Translated Populated Tag Percent   nan nan nan
Highway Translated Populated Tag Percent    nan nan nan
POI Translated Populated Tag Percent    0.25    0.054734169653524491    0.072788277184333061
Difference Between Total Features in Output and Total Features in Inputs            -10
Percentage Difference Between Total Features in Output and Total Features in Inputs         -2.028397565922921
Read Inputs Time (sec)              0.02473902702331543
(Dubious) Read Inputs Bytes             175217
(Dubious) Read Inputs Bytes per Second              7082614.8431329085
Time to Calculate Stats for Input 1 (sec)               1.2566380500793457
Time to Calculate Stats for Input 2 (sec)               0.6789250373840332
Initial Element Count               493
Apply Named Ops Time (sec)              0.0054628849029541016
Apply Pre Ops Time (sec)                5.0067901611328125e-06
Project to Planar Time (sec)                4.0531158447265625e-06
Find Matches Time (sec)             0.43674802780151367
Number of Matches Found             10
Number of Matches Found per Second              22.896497209930487
Number of Matches Before Whole Groups               10
Number of Whole Groups              0
Optimize Matches Time (sec)             0.0019080638885498047
Number of Optimized Matches             10
Number of Matches Optimized per Second              5240.9146570036237
Create Mergers Time (sec)               0.00034379959106445312
Apply Mergers Time (sec)                0.0007610321044921875
Mergers Applied per Second              13140.050125313282
Apply Post Ops Time (sec)               0.0013201236724853516
Conflation Time (sec)               0.44175505638122559
Project to WGS84 Time (sec)             0.000431060791015625
Time to Calculate Stats for Output (sec)                0.84905886650085449
(Dubious) Initial Elements Processed per Second             150.84078655193443
(Dubious) Final Elements Processed per Second               147.78113570909599
Write Output Time (sec)             0.011230945587158203
Final Element Count             483
Total Time Elapsed (sec)                3.2683467864990234
Bytes Read              42185629
Bytes Written               185920
Number of Read Syscalls             2677
Number of Write Syscalls                140
Bytes Read From Storage             2576384
Bytes Written To Storage                0
Cancelled Write Bytes               0
(Dubious) Bytes Processed per Second                53610.284172962056
```

**Comment by bwitham** [comment]
_Should we run stats with every conflate command? or add an option to the UI?_

I'd keep stats optional.  They can get pricy for large datasets.  Some may not be interested in the extra overhead incurred.

**Comment by jasonsurratt** [comment]
> On command line, stats seems to direct to stdout, is there a way to capture to file?

Not, now but @mingjiesu could knock that out quickly. How about [--stats [output.json]]?

> Can we use metadata kvp to retain stats of a conflation job?

This would also be easy to implement, but it is important to note that the stats would become stale almost immediately. Would we want to store the time that they were updated in the metadata too?

**Comment by brianhatchl** [comment]
>Not, now but @mingjiesu could knock that out quickly. How about [--stats [output.json]]?

This would be helpful.  I'm currently redirecting to stdout and then parsing the CSV in the hoot-ui code into json.

>This would also be easy to implement, but it is important to note that the stats would become stale almost immediately. Would we want to store the time that they were updated in the metadata too?

In this case, I think the interest is more in the performance of the conflation and less in the accuracy of the reflecting the current state of the merged dataset.  But you raise a good point.

**Comment by brianhatchl** [comment]
New 'Collect Statistics?' option in Conflate menu:
![stats-option](https://cloud.githubusercontent.com/assets/2600932/12731685/07fbd864-c900-11e5-81de-2a2cdd622fc9.gif)

**Comment by brianhatchl** [comment]
New layer control to display conflation settings and statistics:
![stats-control](https://cloud.githubusercontent.com/assets/2600932/12731708/271b6624-c900-11e5-8084-65cab8ef97e8.gif)

**Comment by mjeffe98** [comment]
I cannot generate a stats layer using either FF v44.0 or Chrome Version 48.0.2564.97 (64-bit)

**Comment by sisskind** [comment]
2016-02-03 19:32:12,911 ERROR JobExecutionManager:225 - Job with ID: 46e5f8b1-79ec-40c7-bdfa-890e87e59ca7 failed: {"chainjobstatus":"46e5f8b1-79ec-40c7-bdfa-890e87e59ca7","childrencount":"3","children":[{"id":"9104647a-141e-481f-9730-1934ae260664","detail":"Failed to execute.\/home\/vagrant\/hoot\/scripts\/makeconflate:57: *** commands commence before first target. Stop.\n","status":"failed"}]}

**Comment by mjeffe98** [comment]
Initially got the error: 
`2016-02-03 13:57:19,140 ERROR JobResource:216 - Failed to execute./bin/sh: 1: cannot create /home/mjeffe/hoot/data/reports/Merged_Roads_dc_stats-stats.csv: Permission denied
make: *** [step1] Error 2` 

but then chmod 777 the hoot/reports dir and was able to generate the stats.  I don't know if this is something generally handled by the Vagrant script or by some other mechanism but thought I should mention it.
