### ISSUE TITLE
Performance issues rendering larger datasets with mapnik

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#107]
I seem to be hitting limits in returning rendered mapnik tiles with a shapefile of San Diego roads.  The file is not translated but for rendering geometry it is unnecessary.  Separate email will be sent with local path to data.  Are there tuning parameters that can be adjusted?  

The zipped dataset is 43MB.  Unzipped its 124MB.  Hoot says its 843MB ingested.

**Comment by mjeffe98** [comment]
@brianhatchl perhaps this is something you could take a look at ?

**Comment by brianhatchl** [comment]
Yes.  The usual approach is to make scale dependent rules in the mapnik style that filter unimportant feature types at small map scales.  Unfortunately for Hoot, the datasets can be quite specific, such as only waterways, or only POIs.  One solution I've considered is to see if the node-mapnik postgis datasource can accept a sql term like LIMIT 10000.  This is the approach we use with retrieving tiled osm data and also with the reviews geojson service used by map-in-map.

**Comment by mjeffe98** [comment]
Might be worth investigating.  I noticed that the failure to render some tiles seems to be independent of zoom level so you could be at 1:5000 scale and not see the data.

**Comment by mjeffe98** [comment]
Loaded a relatively small dataset on selma release in the brazil folder. @jchoi1267 or @sisskind feel free to observe as well.  I don't get the layer to appear until zooming below the node limit threshold which tells me that maybe the mapnik server is not turning the features on as one would expect.  Without density raster, there is no other source to view data above the limit.

**Comment by brianhatchl** [comment]
I pushed the fix for node-mapnik not working at all, f4df99a6e3170b8230397c44b3c409a34529332c, to both release and develop.  Still need to work the scalability issue so leaving this ticket open.

**Comment by brianhatchl** [comment]
Added a row_limit (currently 2000) and extended the connect_timeout (from 4 to 6 seconds) to improve scalability.  At small scales, artifacts of the row_limit are clearly present for dense data like Sand Diego roads.![Screenshot from 2015-12-20 18:19:11.png](https://files.zenhub.io/567737a020b75d5d6e26980c)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by brianhatchl** [comment]
![screenshot from 2015-12-20 18 19 11](https://cloud.githubusercontent.com/assets/2600932/11920835/b92bb4aa-a746-11e5-9c18-a688aa28b874.png)

**Comment by mjeffe98** [comment]
@brianhatchl the San Diego roads data may represent fringe datasets but I suppose we should clarify that larger datasets will require either mapnik rendering rules or a tweaking the row_limit value.  Is that documented in the README in node-mapnik?

**Comment by mjeffe98** [comment]
Tested the Brazil data and looks good. I'm not going to stress the larger dataset solution until that is prioritized.
