### ISSUE TITLE
Geometry Editing Tools Shortcut Bug

### ISSUE THREAD

**Issue by kweint** [ngageoint/hootenanny-ui#1108]
![hoot_tools_shortcutbug](https://user-images.githubusercontent.com/18521019/40723363-c8865620-63ec-11e8-9fc8-dbbf8a27e7c1.gif)

Expected behavior: User ought to be able to turn "on and off" the point, line, and area geometry tools with their respective shortcuts. (Point = 1; Line = 2; Area = 3)

Observed behavior: I can use the aforementioned shortcuts to turn "on" each function, but am forced to actually mouse click to turn "off" each geometry tool. 

This has been observed in Hootenanny Release branch (Version: 0.2.39_109_gd9e302f_dirty) as well as Hoot production (Version: 0.2.38).

**Comment by bobi7** [comment]
Seems to have been fixed
