### ISSUE TITLE
Report generation failures cause conflation job to fail

### ISSUE THREAD

**Issue by jchoi1267** [ngageoint/hootenanny-ui#113]
Moved from 
redmine/issues/7446

**Comment by bwitham** [comment]
OBE w/ new UI stats view...

**Comment by sisskind** [comment]
@bwitham Think we should leave open since report generation is still something that is desired in long run.

**Comment by bwitham** [comment]
@sisskind got it.

**Comment by brianhatchl** [comment]
report generate gone bye bye
