### ISSUE TITLE
Ensure that change log is being updated

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#114]
Need to edit process to extract tickets from GitHub milestone as opposed to RedMine.

**Comment by sisskind** [comment]
@bwitham @mv003348 @qwyjibojones FYI - this will be the ticket to extract issues completed in each milestone.

**Comment by bwitham** [comment]
I think a document with links to the completed github issues per sprint is what we eventually want.  The plain text format the change log used to be in isn't as useful.

**Comment by sisskind** [comment]
Script complete.  Need to integrate within MakeRelease script.

**Comment by sisskind** [comment]
@bwitham Can you review?

**Comment by bwitham** [comment]
@sisskind Reviewed.  Sent you a message on gitter.
