### ISSUE TITLE
Getting TypeError in Conflict.js that prevents any resolution of conflict review.

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#116]
I've now been able to reproduce this error consistently even though I've seen it sporadically.  When reviewing POI datasets like Brazil OSM vs. Geonames, the TypeError below pops up.  It cannot be merged or resolved during review, only skipped.  

TypeError: Cannot read property 'members' of undefined(…)
processMerge@Conflicts.js:408

One example in Brazil_SaoPaulo_OSM and Brazil_SaoPaulo_geonames.
Jardim Vila Galvão vs. Vila Galvao;Vila Galvão.  I don't know how frequently this occurs but have seen it > 2 in the first 50 reviews.

**Comment by mjeffe98** [comment]
Occurs on both develop and release branch

**Comment by jchoi1267** [comment]
Hey Mike, will I be able to reproduce this with standard Brazil data?

**Comment by jchoi1267** [comment]
Ok.
This is good one. This data so heavy it take time to load all features. So if user clicks resolve before all gets loaded we end up with the error.

**Comment by jchoi1267** [comment]
Committed fix.

Now we masks while loading osm to guarantee existence of data when resolving or merging

**Comment by mjeffe98** [comment]
I will test this on develop tomorrow.  For now I'll assume the release branch will be unchanged unless a critical issue is uncovered.

**Comment by mjeffe98** [comment]
I can still trigger the TypeError message in the UI but it looks like it no longer prevents users from advanced if the r key is hit too quickly.
