### ISSUE TITLE
Map overlay in map background settings caches layer in original display color

### ISSUE THREAD

**Issue by mikejeffe** [ngageoint/hootenanny-ui#117]
Add a layer and select a color to display.  Layer displays fine on the map and will update properly to another color if selected.  However if you open the background settings (b) to expose the map overlay options, then check the layer overlay radio button it will display in the original color that the layer was loaded in.  In the example below the layer was originally added as blue then switched to orange.  The POI layer is updated on the map to orange but when you check the overlay layer it displays as blue.  Also there is some funkiness with the layer controllers below.  Checking and unchecking the radio buttons at the bottom left do not always toggle the layer displays on/off.  It depends on the zoom level which I presume is related to when the mapnik layer switches on/off.  

![image](https://cloud.githubusercontent.com/assets/7560096/11968750/69b46e7e-a8c4-11e5-84d5-088e2bef5b33.png)

Below gif you'll see the layer can be toggled on off when the feature geometries display (not the mapnik tiles)  but when you zoom out beyond feature display to the mapnik tiles the layer toggle stops working.  Instead you need to use the map overlay toggle, which of course displays in the originally selected color.  

![layer_controller](https://cloud.githubusercontent.com/assets/7560096/11968912/ac859834-a8c6-11e5-91c8-8566e3cd9d4a.gif)

**Comment by brianhatchl** [comment]
node mapnik server has been removed so this is OBE
