### ISSUE TITLE
Selecting differential roads engine from advanced options doesn't execute differential conflate command

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#1178]
It just executes the regular conflation command.  Selecting differential as the conflation type does send the correct command however.

**Comment by bwitham** [comment]
It may just be that "Differential" needs to be removed from the advanced options and only remain in the conflate type dropdown....I'm not sure, though.

**Comment by mschicker** [comment]
I think it would be best to remove "Differential" from the roads advanced options drop-down!

**Comment by bwitham** [comment]
Ok, cool thanks.  I'll make that change now.

**Comment by bwitham** [comment]
will be handled in https://github.com/ngageoint/hootenanny/issues/2467
