### ISSUE TITLE
Multiline Relation does not show "blue" feature

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#122]
When in review mode and if review feature is multiline relation, the "blue" feature is not being highlighted as blue.  The click to zoom appears to be working when you click on the table.

**Comment by jchoi1267** [comment]
This smells like all the members of child relation is not being loaded

**Comment by jchoi1267** [comment]
This bug was caused by not implmenting code to handle relation members when highlighting feature.
Now we recursively highlight members

**Comment by mjeffe98** [comment]
I was also able reproduce a similar issue with the attached MassNh.zip data. [MassNh.zip](https://files.zenhub.io/5693ec47547e1dfa3ce9169f)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
 
Review in question involves a relation (red) against a linear river feature (blue).  In this case, only the non-relation feature (blue) is highlighted even though both appear in the table.  Clicking on the red feature selects the relation but it does not get highlighted in the map.

**Comment by mjeffe98** [comment]
Can @sisskind or @jchoi1267 provide the dataset that reproduced the issue?  Need to verify against that.

**Comment by mjeffe98** [comment]
Not occurring with a subset of Haiti roads data.  "Blue" feature always appearing.
