### ISSUE TITLE
Relations need to be better visualized

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#130]
It can be difficult in review mode to visualize all the relations for a review feature.  As a user of Hootenanny, I would like to be able to see what other features are at most one degree away with my review feature.

**Comment by jchoi1267** [comment]
Made change such as when mouse hovers on a reviewable feature then all related ones are highlighted with same color (red/blue) 

submodule synched

**Comment by mjeffe98** [comment]
TBH I'm not sure that the highlighting of these features is obvious enough to make it easier to interpret a review against relations.  Particularly for roads, it doesn't appear to be any different than before.  For POIs, I do some some benefit of the color association but it's not enough to make this obvious.  I think this just needs more input.  For example, what about an option to show all related features?  A button that will zoom to whatever view displays all of the features that participate in the relation.  Or possible an arrow that connects any POIs that are participating in a relation. I think this is going to need another round of comments.

**Comment by mjeffe98** [comment]
WRT road features, I don't see any change in how the visualization occurs b/w a feature and a relation.  In this image, the blue highlighted feature is the relation and the red, the road.  Nothing appears to happen when you hover over either. 

![image](https://cloud.githubusercontent.com/assets/7560096/12860439/5b9db5f0-cc11-11e5-98dc-42952535d009.png)

**Comment by jchoi1267** [comment]
@mjeffe98 which dataset should I use?

**Comment by mjeffe98** [comment]
@jchoi1267 I used the haiti subset ones.  Any roads data would probably work though.

**Comment by jchoi1267** [comment]
This is good one. Currently only node and ways are being handled. Looking into relation

**Comment by jchoi1267** [comment]
@mjeffe98 At least relation flashing is fixed. Now I am looking into relation Arrow..

**Comment by jchoi1267** [comment]
made one more change so it does not change other member (i.e. if review than do not change review_against)

**Comment by jchoi1267** [comment]
submodule upadated

**Comment by sisskind** [comment]
Will be tested on version 2.22 to see if current solution meets requirement.  @njackson01 will follow up.

**Comment by sisskind** [comment]
This also may be duplicated by #264.
