### ISSUE TITLE
Refactor advanced conflation options to only pass overrides

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#1315]
No need to pass a long list of default params.  But this will need the ui to compute a diff to collect only the non-default params.

**Comment by maxgrossman** [comment]
steps towards success...

- [ ] make ui work such that selecting conflation type makes services execute `hoot conflate ${a} ${b} -c ${conflation.type.json}`
- [ ] make ui work such that selecting conflation type makes services execute above command + any overrided params like  `hoot conflate ${a} ${b} -c ${conflation.type.json} -D ${override.param}=${override.param.option}`
- [ ] figure out how to integrate advance options...
