### ISSUE TITLE
Post-Conflation Not Kicking Off Review Mode

### ISSUE THREAD

**Issue by kweint** [ngageoint/hootenanny-ui#1319]
The DC POI reference conflation ought to automatically kick off a review mode (usually 63 needed reviews). Please see below gif for what happens in Hoot 2.0 after conflation:

![image](https://user-images.githubusercontent.com/18521019/51757319-0e133f80-2091-11e9-9b80-e53c6fc461a9.png)

When run with dev console, the following error message manifests: 
![image](https://user-images.githubusercontent.com/18521019/51757491-7cf09880-2091-11e9-854f-7fe85de541cb.png)

**Comment by brianhatchl** [comment]
@maxgrossman when you get dev env setup can you try to reproduce?  I think the errors are gone now, but the advanced options for selected conflations types still do not match those of Hoot1 UI.

**Comment by brianhatchl** [comment]
should be resolved with refactor of adv options
