### ISSUE TITLE
Refactor Help Menu

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#132]
Remove references to OpenStreetMap walkthrough.  Also remove the "Edit Now" option when starting Hootenanny.

**Comment by sisskind** [comment]
@mjeffe98 Ready for test.  Please review the new text in the help menu.  Let me know if there are edits to be made, or if you want to update in core.yaml.

**Comment by mjeffe98** [comment]
Looks good.  Thanks @sisskind

**Comment by mjeffe98** [comment]
Looks like this commit was reverted in 0.2.20-259-gc43c1da-dirty(Hootenanny)

**Comment by sisskind** [comment]
Looks okay on current branch of Develop.
