### ISSUE TITLE
Measurement Tool Bug

### ISSUE THREAD

**Issue by kweint** [ngageoint/hootenanny-ui#1320]
Please see the below gif for erratic measurement tool behavior: 

![image](https://user-images.githubusercontent.com/18521019/51757676-0738fc80-2092-11e9-8379-8ca34dda06ce.png)

**Comment by maxgrossman** [comment]
this I think is due to changes in class names for layers in iD

**Comment by maxgrossman** [comment]
...so after upstream merging version 2.11 or something, layer names are different, the measure tool is still looking for old layers, this breaks.

**Comment by putipong** [comment]
fixed after merging in iD v2.11
