### ISSUE TITLE
Geometry Editing Tools Bug

### ISSUE THREAD

**Issue by kweint** [ngageoint/hootenanny-ui#1321]
Only impacts linear and area feature generation. Cursor is nowhere near the geometry being created. 

![image](https://user-images.githubusercontent.com/18521019/51759332-fa1e0c80-2095-11e9-8b3d-8ac0b2e63fdd.png)

**Comment by putipong** [comment]
fixed after merging in iD v2.11

**Comment by maxgrossman** [comment]
@putipong @kweint, awesome if fixed. just for clarity then, were we testing an older v. of the ui?

**Comment by kweint** [comment]
@maxgrossman I was testing the latest version of hoot2x. But obviously happy to test again.
