### ISSUE TITLE
Issue Viewing Translation Files

### ISSUE THREAD

**Issue by kweint** [ngageoint/hootenanny-ui#1322]
User is unable to view Translation files on Hoot 2.0. Please see below gif for how this UI needs to work:

![image](https://user-images.githubusercontent.com/18521019/51759488-55e89580-2096-11e9-98e9-5cc22a3202d6.png)

**Comment by maxgrossman** [comment]
@kweint - this gif does not seem to be animating, could you maybe upload it again? thanks!

**Comment by kweint** [comment]
Sure thing! 
![translations_redo](https://user-images.githubusercontent.com/18521019/51847146-11a10380-22e9-11e9-90fa-aedbc2093e83.gif)

**Comment by maxgrossman** [comment]
....we need to make sure the above context menu shows.
