### ISSUE TITLE
Hootenanny loses attribution after downtime

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#136]
If Hootenanny is left unattended for period of time (~30 minutes), no attribution will appear on the menu unless you shut down and restart the web browser.  Opening a new tab does not solve the problem.

**Comment by mjeffe98** [comment]
Will investigate to reproduce

**Comment by mjeffe98** [comment]
I cannot reproduce this issue even after leaving the Hoot UI client open with the attribute panel displayed.  Clicked on a feature and left the UI with the tags displayed for 3 hrs.  Came back and same tags displayed and was able to modify values without re-selecting the feature. This could be a unique condition in the user environment that caused the behavior described.

**Comment by sisskind** [comment]
Since this cannot be reproduced and has not been an issue, will be closed.
