### ISSUE TITLE
Linear Measurement Tool Issue

### ISSUE THREAD

**Issue by kweint** [ngageoint/hootenanny-ui#1369]
Measure length is using metric even even I've got it on imperial measurement system. Double-clicking (to finish measurement parameters) shouldn't make the measurement display disappear. Please see below GIF for illustration: 
![hoot2x_measure-tool-issue](https://user-images.githubusercontent.com/18521019/53993528-a9221f00-40fd-11e9-8633-00dc005624db.gif)

**Comment by brianhatchl** [comment]
Seems to be fixed
