### ISSUE TITLE
Saving New Translation, from Translation Assistant 

### ISSUE THREAD

**Issue by kweint** [ngageoint/hootenanny-ui#1372]
After completing translation assistant, the save button returns the following window:

![image](https://user-images.githubusercontent.com/18521019/53994335-120a9680-4100-11e9-9471-69c8add88cea.png)

Most notably, the translation js is not present.

**Comment by jackgrossman18** [comment]
@kweint  did you experience this after you added this new translation?

If not, it looks like the reason isn't saving is because no translation text was put into the translation box

**Comment by brianhatchl** [comment]
So the translation assistant should auto-populate the text area with the generated translation file.

Check Hoot1 for it's behavior.
