### ISSUE TITLE
Measurement Tool gets hidden behind features

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#138]
Measurement vectors and label gets hidden behind features.  It appears it needs to be moved "to front".

**Comment by sisskind** [comment]
@brianhatchl Does this occur with merge arrow as well?

**Comment by brianhatchl** [comment]
yes.

**Comment by sisskind** [comment]
Is there a mitigation, or is this just accepted because any layer w/interactivity needs to exist in front of #surface?

**Comment by brianhatchl** [comment]
I guess it just hasn't been reported as a problem yet.

**Comment by sisskind** [comment]
Moving to backlog and reporting to iD repo for resolution.

**Comment by sisskind** [comment]
Accepted as function of iD editor, and will be closed for now.  Will reopen if becomes an issue again.
