### ISSUE TITLE
iD Editor Upstream Merge

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#139]
Update iD Editor to v1.8.5.

**Comment by sisskind** [comment]
For future reference:
```
cd path/to/project-b
git remote add project-a path/to/project-a
git fetch project-a
git merge project-a/master # or whichever branch you want to merge
git remote remove project-a
```

[Source](http://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories)

**Comment by sisskind** [comment]
https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

**Comment by sisskind** [comment]
May need to revisit css/map.css

**Comment by sisskind** [comment]
need to revisit js/id/svg/tag_classes.js

**Comment by sisskind** [comment]
Need to run: ```sudo npm install svg-sprite -g```

**Comment by sisskind** [comment]
https://github.com/openstreetmap/iD/issues/2785#issuecomment-176526383

**Comment by sisskind** [comment]
Moved to backlog pending ATP.

**Comment by sisskind** [comment]
Main issue with initial merge was with new SVG icons.  
Remember to run ```npm install svg-sprite -g``` when doing merge in future.

**Comment by sisskind** [comment]
Updating to 1.9.2

**Comment by sisskind** [comment]
https://github.com/openstreetmap/iD

**Comment by sisskind** [comment]
Committed to develop.  @mjeffe98 ready for review.  If you see the following, can assume that this is complete:

1) See toggle icon (layers) and go to review icon in radial menu when in review mode
2) Can see Map-in-map checkbox in sidebar (Map Data)
3. All other icons appear as they should

**Comment by mjeffe98** [comment]
@sisskind I'm ready to sign off on this assuming that the work for https://github.com/ngageoint/hootenanny-ui/issues/351 is complete.

**Comment by mjeffe98** [comment]
@sisskind how do you want me to treat testing of this?  I think we should close it and then open new issues as they are discovered.  This is too much of a "regression-ey" ticket which has a very vague set of testing criterion.  thoughts?

**Comment by sisskind** [comment]
I made it into an Epic using ZenHub, so once the others are closed we can close it out.  I'll take the lead on tracking and closing when ready.

**Comment by mjeffe98** [comment]
thanks.  I just didn't know about the ready for test state.  thanks for clarifying
