### ISSUE TITLE
Refactor Folder/Datset view

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#140]
As a user of Hootenanny, I want the ability to better visualize the datasets and folders listed for loading and managing.

* ~~Larger font~~
* ~~Better contrast with colors~~
* ~~Lines connecting folders (more of a tree view)~~
* ~~Ability to resize folder window (the window where datasets and folders are listed)~~
* ~~Dataset/Folder name overlaps size, date if too small~~
* ~~Ability to increase sidebar size (increase width)~~

**Comment by sisskind** [comment]
* Increased font size to 12pt
* Changed colors for better contrast
* Not adding lines for now, as it makes it look more cluttered.  Can revisit if need be.

**Comment by sisskind** [comment]
![issue-140](https://cloud.githubusercontent.com/assets/6191659/12392131/b304f8ea-bdba-11e5-9b3b-d0abde776002.png)

**Comment by sisskind** [comment]
What it could look like with connecting lines.  What is lost is the fade animation when folders are opened/closed.

![issue-140](https://cloud.githubusercontent.com/assets/6191659/12392319/1a2f33cc-bdbc-11e5-9c39-c7b437a493fe.gif)

**Comment by brianhatchl** [comment]
I like this.  But do the rows need the blue background at all now?

**Comment by sisskind** [comment]
Only to differentiate between datasets and folders.  The icons area already doing that, but does provide a bit of contrast between the two.

**Comment by njackson01** [comment]
This looks better. How does it look with a folder inside a folder? Will the internal folder be a different color?

**Comment by njackson01** [comment]
Never mind I see it now. I think it's good.

**Comment by mjeffe98** [comment]
I think we should commit this into develop and show it as a demo to the customer.

**Comment by sisskind** [comment]
Sidebar now expandable.  Min width is 33.3% of window size.  When expanding, will cover the map, toolbars, etc.  If user double clicks on the resizable anchor, will reset size back to 33.3%.

**Comment by sisskind** [comment]
Dataset name will add '...' and show full name on hover if it is too long (and covers size).

**Comment by sisskind** [comment]
@mjeffe98 Can you test?

**Comment by mjeffe98** [comment]
@sisskind I saw that resize folder window (the window where datasets and folders are listed)` was not crossed off.  Was that supposed to be included?

**Comment by sisskind** [comment]
Corrected -- just forgot to update.
