### ISSUE TITLE
Support geonames file ingest without requiring renaming extension from .txt to .geonames

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#141]
Redmine #6812

Be able to import geonames file without having to change extension to .txt.

**Comment by curranMapper** [comment]
went here: http://download.geonames.org/export/dump/
downloaded:  ss.zip
extracted: ss.txt

Was unable to import into Hoot 

Getting "import failed or partially failed" error.  Trying on nightly build

**Comment by kweint** [comment]
Just tried replicating Curran's test above and resulted in the same issue.

**Comment by sisskind** [comment]
@treycaldwell is submodule updated?

**Comment by brianhatchl** [comment]
I'm not getting an error importing that file on my local dev env.

**Comment by treycaldwell** [comment]
@sisskind Not sure what's going on.  @brianhatchl merged it and it was working locally.  I added tests and they passed.  Maybe the tomcat log will yield some insight.  The nightly build was verified as being updated.

**Comment by brianhatchl** [comment]
I just imported the SS geonames file to nightly build without error.  It's under the folder Brian/SS_test

**Comment by curranMapper** [comment]
Thanks @brianhatchl @treycaldwell.  It could of been our browser needed a refresh on our end.   I ran the import again this morning on nightly build.  Was successful ingesting the ss.txt file as geonames translation.  Conflated with ME place name node data, and exported without any issues. Seems to be working correctly.
