### ISSUE TITLE
Show selected settings 

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#143]
After conflation runs, show what settings were used to run the conflation job (i.e. reference dataset, conflation type).

**Comment by sisskind** [comment]
#105

**Comment by mjeffe98** [comment]
@sisskind is this testable if #105 is still being worked on?

**Comment by sisskind** [comment]
@mjeffe98 Would say yes.

**Comment by mjeffe98** [comment]
> After conflation runs, show what settings were used to run the conflation job (i.e. reference dataset, conflation type).

I can see by clicking on the `i` next to the layer the parameters and options listed.  I believe this satisfies the ticket criteria.
