### ISSUE TITLE
use translation server in translation assistant

### ISSUE THREAD

**Issue by maxgrossman** [ngageoint/hootenanny-ui#1437]
Not something we need/should put efforts towards now, but we can probably just use the translation server for translation assistant. This could remove the need for the 300kb tds mappings file the class currently uses

**Comment by brianhatchl** [comment]
Yes, these are under the `/data` directory and are called `*_field_values.josn`

**Comment by brianhatchl** [comment]
Figure we can use taginfo to replace `osm-plus-taginfo.json`.
Requests could be to fetch a page of keys/values by popularity (count), e.g. 

>Get popular keys
https://taginfo.openstreetmap.org/api/4/keys/all?include=prevalent_values&sortname=count_all&sortorder=desc&page=1&rp=18&qtype=key

>Get popular values for "building"
https://taginfo.openstreetmap.org/api/4/key/values?key=building&filter=all&lang=en&sortname=count&sortorder=desc&page=1&rp=16&qtype=value


or in the taginfo api with a `query` of the user typed text, e.g.

>Get keys that include "aerow"
https://taginfo.openstreetmap.org/api/4/keys/all?lang=en&page=1&query=aerow&rp=10&sortname=count&sortorder=desc

>Get values for "aeroway" that include "runw"
https://taginfo.openstreetmap.org/api/4/key/values?filter=ways&key=aeroway&lang=en&page=1&query=runw&rp=25&sortname=count&sortorder=desc

**Comment by brianhatchl** [comment]
fixed in #2032
