### ISSUE TITLE
complete review resolve all reviews does not clear review controls

### ISSUE THREAD

**Issue by bobi7** [ngageoint/hootenanny-ui#1456]

**Comment by jackgrossman18** [comment]
@bobi7 was this fixed?

**Comment by bobi7** [comment]
@jackgrossman18  not that i know of

**Comment by brianhatchl** [comment]
Turns out Complete Review... Resolve all remaining reviews - not working
The reviews relations are not removed because the popup prompting to go into review mode reappears.
