### ISSUE TITLE
Post-Conflation Does Not Kick Off Review Mode

### ISSUE THREAD

**Issue by kweint** [ngageoint/hootenanny-ui#1479]
**Behavior from smoke test**
- User initiates conflation
- Conflation completes, and prompts user into Review Mode
- User opts into review mode, but Hootenanny keeps the map zoomed out and does not initiate the Review Mode UI. 
- _I had to force a review mode by zooming into the geography I already knew data existed/where the first few data reviews would typically be._ 

**Expected behavior:**
- User initiates conflation
- Conflation completes, and prompts user into Review Mode
- User opts to initiate Review Mode, and Hootenanny zooms into the first data review (including the review mode UI controls)

**Comment by sisskind** [comment]
@kweint which datasets did you use?

**Comment by kweint** [comment]
Ran the test 3 time with DC POI data, then with Eilat, ISR data.

**Comment by maxgrossman** [comment]
@kweint  - Can you share/point to datasets and conflation algorithms you used in these reviews? 

I am testing with these 2 datasets grabbed from overpass turbo and as soon as I click enter review mode, it zooms immediately to the first review relation.

**Comment by kweint** [comment]
@maxgrossman Sure, I'll share the specific data sets with you in Slack.

**Comment by sputnam** [comment]
@kweint Was this problem specific to the legacy ui or ui2x?  Or did you see it in both?

**Comment by kweint** [comment]
ui2x

**Comment by maxgrossman** [comment]
We think the problem, which is also creeping up and being worked on in #1471 is that the UI builds a minimum bounding box based on 2 features in the review relation. 

If the features are very close, the zoom ends up being very high. This can cause confusion (if 2 points are over a building, imagery just shows a big grey blob).

I guess the same could go for features to review that are quite far away. Perhaps there's a scenario where the minimum zoom for features is greater than the zoom generated by 2 features' minimum bounds.

That said, we should take the work from the ticket mentioned before and make sure better manage this bounds/zoom dilemma.

**Comment by brianhatchl** [comment]
I've seen this too in Hoot2x UI and my workaround has always been to click the `+ Zoom to Edit` button on the map.
