### ISSUE TITLE
Scale Bar Options

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#148]
The scale bar should be able to be viewed as metric or imperial units.  The measurement tool should then use those units for their measurements.

**Comment by sisskind** [comment]
@mjeffe98 Ready for testing.  To change the metric, click on the value in the scale bar (i.e. 500, etc.)  Then run measurement tool to ensure that it is using the same value as the scale bar.

**Comment by mjeffe98** [comment]
I am noticing that with the latest develop ( 0.2.20-317-g1122335) I can no longer toggle the units of the scale bar.  @sisskind can you confirm that?

**Comment by sisskind** [comment]
@mjeffe98 I am able to adjust in Version: 0.2.20-317-g1122335-dirty.

**Comment by mjeffe98** [comment]
@sisskind must have been something on my local dev environment. I confirmed it with selma.
