### ISSUE TITLE
Tags in review tables don't get updated after a review merge until after the "Resolved" button is clicked

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#1480]
Saw this with poi/poly conflation while working on https://github.com/ngageoint/hootenanny/issues/3322. If you merge two features during a review, the tags for the feature being merged into don't get updated in the red/blue tables until you click the "Resolved" button. It seems like the tag tables should be updated immediately after clicking the "Merge" button, but that's arguable. I think this has led to some user confusion that tags aren't merging correctly.

**Comment by jackgrossman18** [comment]
cc@bwitham & @maxgrossman 

when the user clicks the merge button, which do you think would be the best change to make to the tag table. 

1.  Update the table so the new merge tag column overtakes the 'from' tags column as that feature is deleted. This will result in one large red table containing the new merged tags.

2. Only merge the 'from' tags into the 'to' tags column, leaving the 'from' tags column in the UI

3. Delete the entire tag table once the merge button is clicked.

**Comment by bwitham** [comment]
That's a good question... 1) seems to make the most sense to me. 

It would be nice then after that if you clicked the undo button, the red and blue tables would reappear and the features be unmerged...but that may be difficult to do.

**Comment by jackgrossman18** [comment]
Agreed, option 1 seems like the best choice. 
I'll work through your suggestion for the undo button action to see how much work it would take. Thanks
