### ISSUE TITLE
Ability to save review

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#149]
Hootenanny should provide the ability to save or tag a review for later, in the event a user wants to revisit that specific feature directly at a later point, or be able to go directly to it with another user during a different session for a second opinion.

**Comment by mjeffe98** [comment]
@jchoi1267 I'm having issues when I click on the magnifying glass for saved reviews.  It loads the review but then doesn't take me to the correct zoom level or load the review.  The error below is reported in the dev console. Tested this in both Firefox and Chrome.

locale.js
`Missing en translation: review.sharereview.descriptiont @ locale.js:32(anonymous function) @ Conflicts.js:247show @ bootstrap-tooltip.js:107(anonymous function) @ d3-compat.js:38(anonymous function) @ d3.min.js:1`

![saving reviews](https://cloud.githubusercontent.com/assets/7560096/12799798/c709de1e-ca85-11e5-812d-49902f851115.gif)

**Comment by jchoi1267** [comment]
@mjeffe98 hmm.. I will need help from you to reproduce this. I will call when I get back in office.

**Comment by mjeffe98** [comment]
@jchoi1267 I'll check to see if this is happening on the develop branch on selma.

**Comment by jchoi1267** [comment]
@mjeffe98 This discovered another bug in review. Now we have 2 bugs..

**Comment by jchoi1267** [comment]
It was caused by callback function being overwritten.

**Comment by jchoi1267** [comment]
Done with submodule synch.
