### ISSUE TITLE
UI should resolve a review with a changeset when any feature involved in the review is deleted - 5496 branch

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#15]

**Comment by jchoi1267** [comment]
committed 5496

**Comment by bwitham** [comment]
error seen:

* conflate Brazil poi's
* merge first 8 reviews
* resolve 9th

Error shown: 

"Element with ID: -15 and type: Node does not exist for relation. (The feature may have been deleted by other user and may require reloading of the layer. Will jump to next valid review item)
 Server returned status code 412"

I believe the correct behavior should be that the review relation containing that node should have had its member already deleted from the relation, thus already having resolved the review.  The user should have never seen that review.  Also, closing the error dialog does not jump the user to the next review...it stays on the same one.

**Comment by bwitham** [comment]
Quicker test to reproduce:

* conflate AllDataTypes
* merge and resolve first review
* resolve second review

**Comment by jchoi1267** [comment]
K,

This was caused by not clearing merged POI information set previously and it was kept being added in next review resolve..

**Comment by bwitham** [comment]
looks good
