### ISSUE TITLE
Deleting several layers at once causes hoot-services error

### ISSUE THREAD

**Issue by jackgrossman18** [ngageoint/hootenanny-ui#1509]
`/layers` in hoot services returns the following error

```
ERROR: relation "changesets_178" does not exist
```

**Comment by brianhatchl** [comment]
#1511 doesn't fix this, but it's being tracked as a symptom of the tomcat deadlock ticket #1512 which we think is caused by query dsl misbehaving during concurrent requests that occur now that the UI uses Promise.all() and fires off requests (like upload and delete) all at once.
