### ISSUE TITLE
Refactor control.Conflate.js

### ISSUE THREAD

**Issue by jchoi1267** [ngageoint/hootenanny-ui#151]
Like old Conflict.js, Conflate.js is getting too big and need to be decomposed into separate classes.

**Comment by jchoi1267** [comment]
Committed first cut and asked Josh for review

**Comment by sisskind** [comment]
@jchoi1267 reviewed code and looks good.  new architecture/organization is well thought out, and we should probably implement on other code pieces where applicable moving forward.

**Comment by jchoi1267** [comment]
Great! I will merge it in..

**Comment by jchoi1267** [comment]
Merged into Develop branch
