### ISSUE TITLE
Folder lists should filter based on Public Data button state

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#1525]
![image](https://user-images.githubusercontent.com/2600932/62156582-4cf0af00-b2d9-11e9-88eb-59f1dd916345.png)

if Public Data is not shown, public folders not owned by the users should be filtered out

**Comment by maxgrossman** [comment]
dropdowns that let you select folders need should also be filtered to show only private or private+public folder depending on if the above button is selected.
