### ISSUE TITLE
Adding a non-review layer as Reference and a review layer as Secondary can cause UI to freeze

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#154]
I've observed this on multiple occasions (Brazil Sao Paulo osm/geonames poi data for example) where if you add a non-review layer such as Brazil_SP_geonames as the _reference_ dataset followed by a merged layer containing unresolved reviews as the secondary dataset, the UI appears to get stuck in "Checking for reviewable features...." mode. This appears to spin for an indefinite period of time. No obvious errors in the log or console.

![image](https://cloud.githubusercontent.com/assets/7560096/12127536/a0d874e8-b3ac-11e5-994c-7919f8af46c8.png)

**Comment by mjeffe98** [comment]
similar to #127

**Comment by mjeffe98** [comment]
Also occurs when you add non-review layer as secondary and review layer as primary, as long as you add the non-review layer first and the review layer second.

**Comment by jchoi1267** [comment]
hmm.. tested with AllDataTypeA vs review layer and no bug. May be due to new code introduced. I will check tomorrow on selma to confirm

**Comment by mjeffe98** [comment]
I would test with a larger dataset.  Sometimes AllDataTypes does not capture because there are a small number of reviews/features to load.

**Comment by jchoi1267** [comment]
checked against selma using brazil data and appears to be working. Please check...

**Comment by mjeffe98** [comment]
confirmed working now.
