### ISSUE TITLE
Add some import options to the ingest UI for OGR inputs

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#1556]
Add these option to the ingest UI when the input source is OGR (shape or GDB):
* "Simplify Complex Buildings". The default value of the option should be tied to the default value of the `ogr2osm.simplify.complex.buildings` hoot core config option
* "Merge Nearby Nodes'; tied to `ogr2osm.merge.nearby.nodes`. Possibly we also want to add `merge.nearby.nodes.distance` for configuration.

These options should be passed along during ingest to the services when the `hoot convert` command is invoked (so there's also services work involved with this). Technically, the node merging could be an option for any input but I don't think its been tried with anything but OGR inputs ever.

**Comment by brianhatchl** [comment]
Here are two endpoints that help drive the advanced conflation options:
http://localhost:8888/hoot-services/info/advancedopts/getoptions?conftype=hoot2
http://localhost:8888/hoot-services/info/advancedopts/getoptions?conftype=conflationOptions

We probably need to create an endpoint that returns advanced import options.  There is a step in the build process that builds the curated conflation options from a json version of ConfigOptions.asciidoc.

I pushed an `import_options` hoot branch that has a hardcoded config for the moment to get the import dialog working against.  Use this request to get the import options config http://localhost:8888/hoot-services/info/ingest/getoptions

**Comment by maxgrossman** [comment]
@bwitham - we're working to add these opts so they are configurable and built when services get built in the same fashion the advanced opts are.
I just tested the ui locally and noticed the `merge.nearby.nodes` ui is set to true. this is how the configOptions.ascii defines the default. However, after #1583 I know how this can get weird. So, just want to make sure we definitely want things to be set that way (as in we don't want the ui to be false for the option, the checkbox to be unchecked)

**Comment by bwitham** [comment]
Are you talking about `ogr2osm.merge.nearby.nodes`? The correct default for it is `true`. That option only gets read in during import for OGR data sources (same is true for `merge.nearby.nodes.distance` and `ogr2osm.simplify.complex.buildings`). For non-OGR data sources, its ignored completely. 

So, maybe in the UI all of the aforementioned options are disabled for update (greyed out)  when a non-OGR data source is selected to make it more clear that they have no effect in that situation. Thanks.

**Comment by brianhatchl** [comment]
@bwitham is there a hoot command to get a list of all the `hoot convert` options and then to see which are for OGR data sources and which are for OSM and which might be for both?

**Comment by bwitham** [comment]
Kind of... You could do:

`hoot info --config-options | grep ogr2osm`

It turns out that those two are the only ones. I'm not sure what the history behind these two config options being only used for OGR inputs is. Do you know @mattjdnv? Anyway, I've already disabled `ogr2osm.simplify.complex.buildings` by default at Tradecraft's request, and I have a sneaking suspicion that I may have to disable the nearby node merging to get rid of the JOSM building validation errors I'm looking at right now...we'll see. 

I guess these two options must have been useful to someone during OGR ingest at some point, which is why I wanted to expose the options in the UI...just in case someone ever needed them. They were enabled by default for many years.

**Comment by mattjdnv** [comment]
I don't know why these are named the way they are.
