### ISSUE TITLE
Refactor control/utilites/Dataset.js

### ISSUE THREAD

**Issue by jchoi1267** [ngageoint/hootenanny-ui#157]
Refactor control/utilites/Dataset.js

**Comment by jchoi1267** [comment]
Need to bring this to this iteration since it is tied to 283

**Comment by jchoi1267** [comment]
First cut
https://github.com/ngageoint/hootenanny-ui/pull/247​

**Comment by jchoi1267** [comment]
@treycaldwell Please review this ticket

**Comment by sisskind** [comment]
@mjeffe98 Ready for test.

**Comment by mjeffe98** [comment]
@sisskind is there a user story or issue that this is tied to for constraining test cases?

**Comment by sisskind** [comment]
@mjeffe98 @jchoi1267 is your man for that question

**Comment by mjeffe98** [comment]
Not seeing anything come up with this after testing data ingest, delete, move, export, etc..  I think we can close then open up any tickets during regression testing if issues arise.
