### ISSUE TITLE
Displaying TDS attributes in UI

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#160]
When displaying TDS attributes on the UI, the features identified as generic points, lines, and areas will have the wrong attributes show. For these generic features it shows the attributes of the last feature clicked with a non-generic type. This is also happening with features labeled with Highway for lines and Amenity for points of interest. If you change the to the OSM attribution it will show the actual attribution so there needs to be an improvement to showing the TDS attribution in the UI.

**Comment by sisskind** [comment]
@mattjdnv @brianhatchl is this still an issue, or has it been resolved by work done over past 6 months?

**Comment by brianhatchl** [comment]
I'll look into this today.  Thanks for going in and triaging older tickets, definitely needs to be done.

**Comment by brianhatchl** [comment]
Yes, this still seems to be a bug.

**Comment by brianhatchl** [comment]
This seems to be due to an error in the osmtotds translation:

```
terminateHandler caught unhandled exception. what(): /home/vagrant/hoot/plugins/etds61.js (66) 
                var tmpList = etds61.rules.fcodeLookup[tFCODE]['enum'];
                                                              ^ 
TypeError: Cannot read property 'enum' of undefined
stack trace:
  hoot::SignalCatcher::terminateHandler() +0x7f
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 : ()+0x5e6d6
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 : ()+0x5e703
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 : ()+0x5e922
  hoot::HootExceptionJs::throwAsHootException(v8::TryCatch&) +0x5c1
  hoot::JavaScriptTranslator::_translateToOgrVariants(hoot::Tags&, hoot::ElementType, geos::geom::GeometryTypeId) +0x387
  hoot::JavaScriptTranslator::translateToOgrTags(hoot::Tags&, hoot::ElementType, geos::geom::GeometryTypeId) +0x45
  hoot::TranslationVisitor::visit(boost::shared_ptr<hoot::Element const> const&) +0x104
  hoot::OsmMap::visitRw(hoot::ElementVisitor&) +0x275
  hoot::TranslationOp::apply(boost::shared_ptr<hoot::OsmMap>&) +0x3d
  hoot::OsmMapOperationJs::apply(v8::Arguments const&) +0x75
  /usr/lib/libv8.so.3.14.5 : ()+0x99313
  [0x25d656c06362]
```

I'll have to see what FCODE it's trying to pass.

**Comment by sisskind** [comment]
@brianhatchl what is a good way to test?

**Comment by sisskind** [comment]
@brianhatchl ping RE: testing

**Comment by brianhatchl** [comment]
Select some features and switch between OSM and a translated schema.  You should not see features turn into generic points, lines or polygons.  If you select a feature that does not have a valid translation in the selected schema you should see an error, either specifically as to why (e.g. "Point geometry is not valid for AK120 in MGCP TRD4") or else "Feature out of spec.  Failed to translate."  The tag schema should then remain as the previous selection.

Try adding an point with OSM preset Park.  Then switch to MGCP.  This should generate the warning above.

It should now be impossible to create an invalid feature when selecting from translated schema presets.

The refactored schema switcher has not yet been merged into hoot-ui, but this bug should have been addressed by a prior bug-fix commit

**Comment by kweint** [comment]
Tested over every dataset at my disposal on hoot nightly and develop -- TDS attributes are displaying correctly. Closing issue.
