### ISSUE TITLE
Conflation output names might not detect public duplicates

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#1602]
resulting in this js error in console
`Hoot.layers.findBy(...) is undefined`

**Comment by brianhatchl** [comment]
To reproduce you'd need to run a conflation from a public folder.  Then a different user would have to pick the same two input layers and the default output layer would not get deduped it seems.  The conflated output with duplicate name gets created, but the UI does not handle this well.

**Comment by bobi7** [comment]
Seems to be working properly
