### ISSUE TITLE
Determine best practice to change color of edited features

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#162]
When editing a feature, include a halo/highlight/change color so the user is aware of the edits that have already been made.  This could remain until the user saves their changes.

**Comment by sisskind** [comment]
Need to select Map Data menu from sidebar, open Map Features and check 'Highlight edited features'

**Comment by mjeffe98** [comment]
Tested on local develop.  Looks good.

**Comment by mjeffe98** [comment]
I am noticing that the yellow edited feature halo turns off when you zoom out just slightly.  Wanted to make sure this was intended.  Looking at the DcTigerRoads data, there is only a slight difference in zoom level when the halo comes on/off.

![highlight_edits](https://cloud.githubusercontent.com/assets/7560096/13445902/fd46711a-dfc3-11e5-9ae7-1a2632bb0d0b.gif)

**Comment by brianhatchl** [comment]
This was not intended, just a side effect.  I see @sisskind is assigned to look into it, but I suppose there may be a css rule that hides the halo svg group past a certain zoom level.

**Comment by sisskind** [comment]
Appears to be occurring when low-zoom class kicks in.

**Comment by sisskind** [comment]
@mjeffe98 submoduling syncing and will be ready for test.

**Comment by mjeffe98** [comment]
looks good on develop.  Did not have any zooming issues.
