### ISSUE TITLE
Allow map to pan/zoom while measuring

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#163]
The map 'freezes' when using Hootenanny measurement tools.  Users may want the ability to pan/zoom while measuring.

**Comment by sisskind** [comment]
Refer to #264 for potential solution, specifically: 
```
function redraw(difference, extent, waitOnLoad) {
```

**Comment by sisskind** [comment]
@mjeffe98 ready for test.  should be able to draw measurement vectors and they should persist as you pan/zoom map.  To remove, click tools menu.

**Comment by mjeffe98** [comment]
@sisskind this does work but there is the unintended side effect that the measurement will remain on the screen until you click again on the Tools button.  I think we're gonna need a 'Clear' screen button if you want this ability.

**Comment by sisskind** [comment]
Will add and resubmit.
