### ISSUE TITLE
Review Bookmarks not functional in Hoot2x

### ISSUE THREAD

**Issue by ryanmcweeny** [ngageoint/hootenanny-ui#1637]
After making multiple bookmarks using the Bookmark Review button I went to the Review Bookmarks section in Hoot2x which did not populate. However, when going to the legacy hoot page all of my bookmarks were displayed. Examples of this are below.
![68222458-0d60ef80-ffb9-11e9-9be8-ca4824189eda](https://user-images.githubusercontent.com/24612000/68233007-4a82ad00-ffcc-11e9-8f0c-2ebc5a035d68.png)
![68222459-0d60ef80-ffb9-11e9-9631-663c04b47c6c](https://user-images.githubusercontent.com/24612000/68233008-4a82ad00-ffcc-11e9-8ce1-8eee32feffad.png)

**Comment by bobi7** [comment]
ref #1736
