### ISSUE TITLE
Make review highlight wider when selected in red/blue table

### ISSUE THREAD

**Issue by jchoi1267** [ngageoint/hootenanny-ui#166]
When both red and blue features are stack on each other, it gets difficult see where blue/red feature is located. When user selects a column, make the highlight wider to accentuate the selected feature..

**Comment by sisskind** [comment]
@jchoi1267 Rather than on click event, what about on hover?

**Comment by sisskind** [comment]
@mjeffe98 Ready for test.

**Comment by mjeffe98** [comment]
@sisskind can you include a screen capture of this?  I need to confirm first.

**Comment by mjeffe98** [comment]
For example if you look at this POI set (dcpoi and mapcruzen), the DC BILINGUAL PCS and blue District of Columbia Bilingual ...  pois actually fall pretty near on top of each other.  When either are selected there is no difference in halo size.  I need to know what to be looking for to determine whether there is a behavior change.

![image](https://cloud.githubusercontent.com/assets/7560096/12898967/18f0dd36-ce64-11e5-909b-b974833c1b2b.png)

**Comment by sisskind** [comment]
@mjeffe98 Will set back to 'In Progress' for POIs and also for roads.

**Comment by sisskind** [comment]
@mjeffe98 Ready for test.  Will update gifs shortly to show changes.

**Comment by sisskind** [comment]
![issue166](https://cloud.githubusercontent.com/assets/6191659/12921069/858d8876-cf19-11e5-9811-97ca39a12477.gif)

**Comment by sisskind** [comment]
![issue166-poi](https://cloud.githubusercontent.com/assets/6191659/12922088/1672f78c-cf1e-11e5-94b3-3342c76faa3f.gif)

**Comment by mjeffe98** [comment]
Everything seems to be working now.  Thanks for fixing @sisskind
