### ISSUE TITLE
Blue highlighted review features not displaying at default zoom level for longer linear features

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#167]
I started observing this on the release branch after a recent commit that impacted reviews for single ways against multilinestrings.  As I stepped through reviews of Haiti PortAuPrince data, noticed that on more than one instance the highlighted blue review against feature would not always display until I zoomed in further.  No longer zooming to the zoom level where both the highlighted features display.  It appears that you need to zoom in further to turn on the blue in this case.

@jchoi1267 @brianhatchl any ideas?  

![test](https://cloud.githubusercontent.com/assets/7560096/12250154/b3d6a944-b879-11e5-82c7-9228eb6e3f2b.gif)

**Comment by mjeffe98** [comment]
This could be a duplicate of ngageoint/hootenanny-ui#122

**Comment by mjeffe98** [comment]
reassigned to @brianhatchl since you are typically the color master :)

**Comment by mjeffe98** [comment]
Adding some additional notes on this.  Rendering issues mainly occur on features > 2 km long.

**Comment by mjeffe98** [comment]
Attached useful subset of Haiti data for recreating issue.  The  review against Rue Louis E. Pouget (red) vs. mgcp illustrates issue.  Only occurs when blue feature exceeds some unknown distance.  

[Haiti_subset.zip](https://files.zenhub.io/56953e195a0cfd1c5d6e86c8)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by brianhatchl** [comment]
@jchoi1267 Seems like loadMissingFeatureDependencies() is not handling relations (i.e. loading constituent ways of the relation)

**Comment by jchoi1267** [comment]
As @brianhatchl  suggested fixed using Hoot.control.conflicts.actions.idgraphsynch.getRelationFeature

Also now delegates panning to caller since when zoomed out we do not want to zoom back in.

**Comment by mjeffe98** [comment]
Looks good.  All segments were loading at the default zoom for each review.
