### ISSUE TITLE
Clicking 'next' in fast succession produces error loading review members

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#169]
Getting pop-up error message, "There are no members in the review relation" after going through a review of features containing multilinestrings vs. relations.  If you click the 'n' key in quick succession before the feature is loaded you will see this.  This may also be related to the NaN issue.  
(https://github.com/ngageoint/hootenanny-ui/issues/137) 

Not seeing an error in the dev console associated with this action.

![image](https://cloud.githubusercontent.com/assets/7560096/12275682/403f5d16-b926-11e5-8a33-d98223ce6a83.png)

**Comment by mjeffe98** [comment]
Also was able to trigger NaN by clicking n really fast.

**Comment by jchoi1267** [comment]
Updated the setProcessing masking. Although there is sometimes 0.5 sec gaps between locking it should cover most of processing range. Could not create lock covers whole process since tile loading is extremely asychronous operation and can not cover all entry and exit points
