### ISSUE TITLE
UI job status log not showing all logging statements

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#1723]
The status log leaves out several status messages from a conflate job. This is making it more difficult to diagnose user problems when a job crashes, since we don't know exactly where its crashing.

@SeeBee2018

**Comment by brianhatchl** [comment]
We can do something about this.  There is more info on command text and stdout available in the job status responses that we can optionally display.

**Comment by bwitham** [comment]
Cool, thanks.
