### ISSUE TITLE
Job cancelling not working

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#1729]
This might be a services issue instead...

While watching conflate processes on the testing server, I cancelled a conflate job, got confirmation from the UI that the job cancelled, but the process on the server never went away. It kept running and taking up memory. When I launched a second conflate job, the terminal seemed to freeze up as the memory available to me was maxed out with two jobs running at the same time. The iD testing app was unresponsive shortly thereafter.

**Comment by bobi7** [comment]
fixed here https://github.com/ngageoint/hootenanny/issues/3938
