### ISSUE TITLE
Allow user to copy specific tags from selected feature

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#173]
Currently, paste tags relies on the user to select a feature and ctrl+C to copy it, thereby copying all the feature tags.  If the user only wants a subset of tags, they could select (highlight) the rows in the tag table in the sidebar and then click a copy button.  The selected tags would then be available to paste onto other selected features as described in #172

**Comment by brianhatchl** [comment]
![screenshot from 2016-01-15 17 21 32](https://cloud.githubusercontent.com/assets/2600932/12366947/79f7f6fc-bbac-11e5-9351-0a89c8506eae.png)

**Comment by mjeffe98** [comment]
I'm seeing that certain tags to dot get updated after copying.  For example, input1 tag source:datetime and source:ingestdatetime were checked.  When pasting using either method (overwrite Ctrl+Shift+V or append Ctrl+Alt+V) those two tags did not get updated in the target (input2).   Also wanted to verify that if input1 amenity=restaurant and input2 amenity=post_box; If I chose the append paste than I would get input2 amenity=restaurant;post_box.  Are we just relying on the user to avoid making those errors that would cause the translation to fail if exported?

**Comment by mjeffe98** [comment]
Added a graphic to make it clearer.

![issue173](https://cloud.githubusercontent.com/assets/7560096/12402025/1e069a80-bddf-11e5-851a-95f74dbba617.png)

**Comment by brianhatchl** [comment]
>I'm seeing certain tags not getting updated after copying. For example, input1 tag source:datetime and source:ingest:datetime were checked. When pasting using either method (overwrite Ctrl+Shift+V or append Ctrl+Alt+V) those two tags did not get updated in the target (input2). I made sure that input1 and input2 had different values for those tags.

Those tags are in the omit list, https://github.com/ngageoint/hootenanny-ui/blob/develop/js/id/behavior/paste_tags.js#L5-L27  This was done assuming those were internal hoot system tags.  We can change this behavior if we want.

>Also wanted to verify that if input1 amenity=restaurant and input2 amenity=post_box; If I chose the append paste than I would get input2 amenity=restaurant;post_box. Are we just relying on the user to avoid making those errors that would cause the translation to fail if exported?

Yes, for now.  I'm working on generating a list of enumerated tags from the hoot schema json files that we can use to implement an always overwrite rule.

**Comment by mjeffe98** [comment]
Ok thanks.

**Comment by mjeffe98** [comment]
@brianhatchl I was experimenting with this

**Comment by mjeffe98** [comment]
In addition I did see some cases where it was possible to paste two highway values e.g. highway=road;yes.  Have we set up the rules to prevent that from happening yet?

**Comment by brianhatchl** [comment]
>I thought the business logic behind the check box in the tag table was to allow users to select a specific set of values to copy/paste

Totally.  If not something is wrong.

> it was possible to paste two highway values e.g. highway=road;primary

You still have to choose between overwrite (Ctrl+Shift+V) and append (Ctrl+Alt+V).  We have not taken action on the ticket to always overwrite enumerated tags, https://github.com/ngageoint/hootenanny-ui/issues/176.

**Comment by brianhatchl** [comment]
I'm unable to reproduce this.  Maybe you can webex demo this for me?

**Comment by mjeffe98** [comment]
Yes I can.  I've been testing with some POIs and seem to reproduce my workflow consistently.

**Comment by mjeffe98** [comment]
User Error. The act of checking the tag boxes copies the selected tags.  Will update the documentation accordingly.
