### ISSUE TITLE
When data is loaded from folder the conflate form does not get populated properly

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#174]
Possibly related to changes made with Conflate.js in https://github.com/ngageoint/hootenanny-ui/issues/151

After updating my dev instance to latest develop branch code, it looks like Conflate.js can no longer read data contained in folders.  If you remove the data from the folder to root, then the form populates as expected.

**Comment by mjeffe98** [comment]
When data is loaded from a folder as opposed to root, the Conflate form is missing buttons.  

In dev console, line 211 in Conflate.js is highlighted where folderList is not defined.

![image](https://cloud.githubusercontent.com/assets/7560096/12310443/2a78e58a-ba05-11e5-9ba0-d3f44c9c502e.png)

**Comment by mjeffe98** [comment]
If you remove the data from the folder to root, then the form populates fine

**Comment by jchoi1267** [comment]
The bug was from not passing in folderList properly. This got broken during conflate.js refactor.

**Comment by mjeffe98** [comment]
Looks like that fixed it with my local instance.  Will check again tomorrow on selma.
