### ISSUE TITLE
Include Hoot Tags on set by default when I open the Export modal

### ISSUE THREAD

**Issue by maxgrossman** [ngageoint/hootenanny-ui#1740]
If I...

1. have a merged dataset
2. right-click in dataset panel and choose export

the modal does not have the include tags input

then when I 

3. reselect osm as a schema in the schema input

it appears.

**Comment by brianhatchl** [comment]
I thought that was fixed in https://github.com/ngageoint/hootenanny-ui/pull/1734

**Comment by brianhatchl** [comment]
@maxgrossman still an issue or already fixed?
