### ISSUE TITLE
Hovering over merge button triggers message "Please wait while loading tiles"

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#175]
It seems we have introduced some inadvertent behavior.  Now when you hover over the merge button to see the arrow, a request is sent to the server.  This seems unnecessary and will slow down the review process significantly. This is appearing in latest develop branch.

When hovering over merge button or immediately following this hovering over any other button the following post request is made from the UI:
http://localhost:8080/hoot-services/osm/api/0.6/map/nodescount

**Comment by mjeffe98** [comment]
Note the cursor location when the update occurs.

![hoot-ui-175](https://cloud.githubusercontent.com/assets/7560096/12433368/958cff32-beb5-11e5-8aac-248a8ff3f49d.gif)

**Comment by jchoi1267** [comment]
It was caused by load Arrow updating the vector tile. Now added check to see if arrow is being displayed if so do not block..

**Comment by mjeffe98** [comment]
@jchoi1267 did you submodule synch?

**Comment by jchoi1267** [comment]
LOL. This time I have remembered. But next time when you do not ask I would have forgotten..Murphy's law

**Comment by mjeffe98** [comment]
git log tells me everything :)

**Comment by mjeffe98** [comment]
muy bien.  thanks @jchoi1267 for the quick turn around.
