### ISSUE TITLE
Clip function doesn't seem to be working

### ISSUE THREAD

**Issue by ryanmcweeny** [ngageoint/hootenanny-ui#1754]
When trying to use either of the clip dataset tools nothing occurs despite Hootenanny saying the task was completed. The dev console gave the following message.
<img width="556" alt="Screen Shot 2020-03-23 at 11 00 34 AM" src="https://user-images.githubusercontent.com/24612000/77331426-1566c500-6cf7-11ea-8378-023d706b4aa6.png">

**Comment by brianhatchl** [comment]
Did you have a folder selected in the clip dialog (under Path)?
![image](https://user-images.githubusercontent.com/2600932/77331782-92923a00-6cf7-11ea-89d6-7e39e5e19a18.png)

**Comment by ryanmcweeny** [comment]
I thought I had. The path usually has one selected automatically. However, I'm trying it now and everything is working with all vector files. I'm chocking this up to user error and marking as resolved.

**Comment by ryanmcweeny** [comment]
So what actually happens is if you select the button to resolve all remaining issues in a merged layer and then try to make a clip of that layer the Path will no longer autopopulate or provide a dropdown menu with your folders.  This can be seen in the images below. This can be resolved by refreshing the page.
<img width="389" alt="Screen Shot 2020-03-23 at 1 31 31 PM" src="https://user-images.githubusercontent.com/24612000/77345459-05f17700-6d0b-11ea-94f4-5d983269b92d.png">
<img width="1003" alt="Screen Shot 2020-03-23 at 1 31 55 PM" src="https://user-images.githubusercontent.com/24612000/77345466-08ec6780-6d0b-11ea-86df-630b3f1108c8.png">
