### ISSUE TITLE
Tagging schemas besides OSM not working

### ISSUE THREAD

**Issue by ryanmcweeny** [ngageoint/hootenanny-ui#1755]
When trying to translate an object from OSM to TDSv40 or any other schema Hoot says that the feature is out of spec. I tried this with points lines and polygon features. The dev console returned the attached error. Furthermore when attempting to create a new feature with a schema besides OSM none of the tags populate or give you the option to use a dropdown menu.
<img width="229" alt="tag1" src="https://user-images.githubusercontent.com/24612000/77337586-772b2d00-6cff-11ea-8393-27b4bebee350.png">
<img width="230" alt="tag2" src="https://user-images.githubusercontent.com/24612000/77337587-772b2d00-6cff-11ea-9552-6ebaa14c7d7d.png">
<img width="554" alt="tag3" src="https://user-images.githubusercontent.com/24612000/77337588-772b2d00-6cff-11ea-8aa9-0b78d9546c16.png">
<img width="382" alt="tag4" src="https://user-images.githubusercontent.com/24612000/77337589-772b2d00-6cff-11ea-8fff-29b1da8f24e6.png">

**Comment by jackgrossman18** [comment]
@ryanmcweeny does this behavior occur when you try to translate a feature you have created, or an existing feature?

**Comment by ryanmcweeny** [comment]
I noticed the issue with both.

**Comment by brianhatchl** [comment]
This is the same issue that's causing the merge review features to fail.  It's related to our nodejs rpm installed as part of Hoot.  There's no UI code change to be made.

**Comment by jackgrossman18** [comment]
I did notice when looking into this, that if you were to switch from osm to any other scheme, a new tag cannot be added. Seems to be an issue with accessing translations w/in the raw tag editor class

**Comment by brianhatchl** [comment]
fixed in https://github.com/ngageoint/hootenanny-ui/pull/2039
