### ISSUE TITLE
Paste tags: use a list of enumerated tags to always overwrite

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#176]
The paste tags #172 now operates in two modes: overwrite (Ctrl+Shift+V) and append (Ctrl+Alt+V).  However, some tags are enumerated and should never have multiple values.  To enforce this, the paste tags code could use a list of enumerated tags to **always** overwrite the target value when pasted.

Hoot maintains a schema of osm tags that could be used to generate this list.

**Comment by brianhatchl** [comment]
Might want to compare the hoot schema list of enumerated tags with this, http://wiki.openstreetmap.org/wiki/Map_Features

**Comment by sisskind** [comment]
OBE
