### ISSUE TITLE
Search radius not returning different results

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#177]
When I adjust the search radius in advanced conflation options, it does not appear that the number of review items increases or decreases (same no matter what).

**Comment by sisskind** [comment]
Step 1. Find dataset where results should increase depending on search radius.

**Comment by bwitham** [comment]
As you increase the search radius, you will *sometimes* then match features which were previously marked for review only, thus decreasing reviews (runtime can increase as well).  New reviews could also be incorporated into the results as the search distance increases.  So, the overall number of reviews may or may not change that much with an increase in search radius, but the reviews themselves  may change instead.

**Comment by brianhatchl** [comment]
Might want to decrease the radius then, and see if you get fewer.

**Comment by bwitham** [comment]
Right, that may be a more straight forward way to do it.  

For POI's, search radii are handled a little differently (assuming its unifying), and I'm not sure that the UI distance setting has any affect on that conflation.  See rules/PoiGeneric.js for the distance thresholds there, if needed.

**Comment by sisskind** [comment]
@jchoi1267 Can you review https://github.com/ngageoint/hootenanny-ui/commit/b6ae2223e43a48981ccfed6285994e758bc05f81?  Looks like it was taking the default value for list items no matter what, even if they had been updated.

**Comment by jchoi1267** [comment]
Will do

**Comment by jchoi1267** [comment]
Looks like you've got the fix! Tried changing Search Radius Highway and with old code it was not updating but with your fix it is passing correct value.
Let me know if you want me to do merge..

**Comment by sisskind** [comment]
Thanks Jong! I can throw the merge together!

**Comment by mjeffe98** [comment]
Verified that updated values are getting passed when clicking on show values option.  Also in output, if you specify 5m vs. 100m as the road search radius with Haiti roads data you get fewer reviews so it is having an impact on the conflation job.
