### ISSUE TITLE
Adjust line width

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#178]
As a user of Hootenanny, I would like the ability to adjust line width of vectors for better visualization.

**Comment by sisskind** [comment]
@mjeffe98 Ready for testing.  Find in Manage Tab > UI Settings.

**Comment by mjeffe98** [comment]
I like the control but my only suggest would be to move it from Manage | UI Settings to the layer control.  The reason being typically when you are adjusting symbology, you generally don't want to toggle back and forth b/w an admin console.  If that is too cumbersome or other UI guys like @brianhatchl @jchoi1267 disagree than we'll leave it as is.

**Comment by mjeffe98** [comment]
Going to mark as closed for now since the task is complete.

**Comment by mjeffe98** [comment]
Something we should consider @brianhatchl @sisskind, the path width setting is only going to apply to the feature rendering at the "Edit" zoom level so mapnik rendering will not be impacted.  I suspect that some of the requests for this may have come from a desire to modify the mapnik rendering but could be wrong.
