### ISSUE TITLE
Add user customizable POI conflation search radii to advanced options

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#1784]
Working with @curranMapper, we've recognized some conflation scenarios where hoot's default configured search radius distances for POI conflation aren't adequate. It would be useful to give users the option to customize these distances as needed.

As part of [these changes](https://github.com/ngageoint/hootenanny/pull/4096), hoot now accepts incoming POI feature search radii distances as JSON, whereas before they weren't customizable unless you were running from the command line and made edits to `rules/Poi.js`. Now, we'd like to expose this functionality via the UI. Definitely open to other ideas, but I'm thinking that under the "Poi" section of the adv opts, add a dialog that shows each feature type hoot POI conflation supports along with their default search radii. Then allow the user to change those distances from there.

* The default POI search radii are defined in [this file](https://github.com/ngageoint/hootenanny/blob/master/conf/core/PoiSearchRadii.json), which is configured with the `poi.search.radii.config` config option. So, this file can be read in to get the defaults.
* Another config option, `poi.search.radii` has been set up to override the aforementioned file and pass in the search radii as JSON from the UI.
* The JSON format is very simple. 'key' and 'distance' are required and 'value' is optional. If 'value' is left out, then all features with the tag key will be matched with the same search radius.
* **BONUS IDEA:** Additionally if we want, we could allow users to add search radii for additional types that aren't in the hoot defaults. The one caveat is that if hoot doesn't have the user added type defined in its schema then it won't able to conflate it as a POI (there are a lot of POI types already in the schema, though). In those cases the point *should* get conflated with generic point conflation, which is a little more stripped down in functionality and then will ignore the specified POI search radius and use the custom radius its configured with. There are ways to query hoot's schema to know what types are considered POI's, but I don't think that information is available outside of the core. So, if we did this we may want to add the capability to query for that information first. Will leave the decision of whether we want to implement this particular functionality up to Tradecraft.

**Comment by bwitham** [comment]
@curranMapper @mattjdnv This is something I recognized as being useful given some of Curran's recent work. I implemented it in the core but then would need this task done to make it available in the UI. I'll leave what we think the importance of doing this task is up to you guys. If Curran isn't having any current problems with not being able to customize the POI search radii, then maybe this is lower priority for now.

**Comment by curranMapper** [comment]
My 2 cents is this is a great addition to have going forward and we will be useful against similar use cases but not a blocker to accomplishing anything at the moment, so agree with lower priority tag.

additional context of specific use case which will likely apply to others is user is interested in conflating barrier=border_control; government=office and government=customs datasets from various sources.  There are cases where a particular dataset has a tag of 'locational precision = approximate or unknown' and other examples where it would be great to extend search radius in order to flag user to make Merge or create site relation decisions in reviews.  Ideally in the grail context.

**Comment by bwitham** [comment]
Ok, sounds good. Marking it down in priority for now. 

As it works now, hoot will read the `error:circular` tag off each feature and if the accuracy value is larger than what's configured in the search radius file for a feature, it will use that instead. So for that scenario, we could add an `error:circular` tag with those same values and accomplish the same thing. That's a little kludgy, though. It would be nice if we could configure hoot to look for a particular accuracy tag in a dataset, rather than forcing it to be `error:circular` every time. Don't think we can do that now, so I'll look into that too.
