### ISSUE TITLE
Tag Schemas are not populating in All Tags section when changed

### ISSUE THREAD

**Issue by ryanmcweeny** [ngageoint/hootenanny-ui#1802]
If you take a feature such as a railway in OSM tag schema and try and translate it to TDSv4 or anything besides the OSM the All Tags section will not populate and Hoot will inform you the feature is out of spec. No error seems to show up in the console. This was tried with several types of way and point features. using the MassNh_OSM_small test file.

**Comment by brianhatchl** [comment]
`iD.min.js:1 Uncaught TypeError: Hoot.fcode is not a function` is the js error when the raw tag table does not populate with the translated tags.  "Feature out of spec" is an error shown when the OSM tags could legitimately not be translated to a valid feature in the target schema.  I think these are two separate occurrences, with the second being ok if it happens.

**Comment by brianhatchl** [comment]
Also this has been a bug since `0.2.55`
