### ISSUE TITLE
Error importing Phillippines OSM dataset into UI

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#186]
gis-data/pacom/philipines/osm/philippines-12Mar14.osm

Error upon importing dataset from UI:

2016-01-25 12:50:52,222 ERROR JobResource:216 - Failed to execute.Error running convert:
Parse error at line 1, column 1:
error occurred while parsing element
make: *** [step1] Error 255

**Comment by bwitham** [comment]
@mjeffe98 If you receive a server side error message, log the issue in the services or core category rather than the UI category.  thanks.

**Comment by mjeffe98** [comment]
@bwitham will do.  thanks.

**Comment by bwitham** [comment]
services issue..moving to hoot repo
