### ISSUE TITLE
how to run development_server.js?

### ISSUE THREAD

**Issue by d3netxer** [ngageoint/hootenanny-ui#1863]
I am trying to run development_server.js, but I get this error: ```Cannot find module './build_src'
```

is there supposed to be a folder called 'build_src'?

**Comment by sisskind** [comment]
@bwitham

**Comment by bwitham** [comment]
@bobi7 @brianhatchl

**Comment by bobi7** [comment]
@d3netxer is your goal just to run the ui because if so, you can use `npm start` and it will run in dev mode

**Comment by d3netxer** [comment]
I would like to be able to run it on my own server; also I would like to connect the UI with hootenanny core.

**Comment by brianhatchl** [comment]
This project is included as a submodule of the main Hoot repo https://github.com/ngageoint/hootenanny
No need to clone it separately
