### ISSUE TITLE
Error when trying to export OSM

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#187]
I think this will happen with any layer, but have only reproduced it with DcGisRoads.osm and an Egypt buildings shape file so far:

1. import DcGisRoads.osm into the UI
2. right click export to OSM (don't think the translation selected matters)

You get this error:

2016-01-25 13:19:06,090 ERROR JobExecutionManager:225 - Job with ID: ex_5c1ca45c49434652b2de33bb0c1bc02e failed: Failed to execute.Error running convert:
If a map name is specified then the user email must also be specified via: services.db.reader.email
make: *** [step1] Error 255

**Comment by mjeffe98** [comment]
@jchoi1267 did we reintroduce the old bug of exporting .osm files?

**Comment by mjeffe98** [comment]
since this is fairly critical I believe it should be included in current sprint.

**Comment by jchoi1267** [comment]
I surely smell like it! Looking into it.. (I will never finish 149 :-( )

**Comment by jchoi1267** [comment]
@mjeffe98 Looked into this and this is bug created by bug fix. :-)
services.db.reader.email was broken so temporarily I have changed to use services.db.writer.email. Now services.db.reader.email is fixed so it is broken again. I will change back to services.db.reader.email

**Comment by bwitham** [comment]
services.db.reader.email and services.db.writer.email seem to be the exact same setting now.  I'd just collapse them to services.db.email and then avoid this type of thing in the future.

**Comment by jchoi1267** [comment]
Thanks
