### ISSUE TITLE
Allow for multiple linear feature types to be selected for way snapping when using Diff Conflate

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#1873]
This task is blocked by [hoot 4772](https://github.com/ngageoint/hootenanny/issues/4772).

Currently, the feature types selected for way snapping in DC is controlled only from a core config and limited to either one feature type at a time or all feature types. After [hoot 4772](https://github.com/ngageoint/hootenanny/issues/4772) is complete, multiple feature types may be specified and all of them will be snapped. If not feature types are specified, then all feature types are snapped.

This task will involved adding a multi-select listbox to the Diff Conflate section of the advanced options that maps to the `snap.unconnected.ways.snap.criteria` configuration option, which is under "Differential Conflation" --> "Linear feature types to snap" in the adv opts. This option controls both the types of the ways being snapped and that of those being snapped to, as we're assuming in the UI we always want them to be the same. It is possible to use separate types for each (e.g. snapping generic lines to roads), but don't see that being a use case in the UI at this point. The listbox display contents should be controlled by the types of features that have been selected for conflate (roads, rivers, etc.). Each listbox display item should map to the hoot core criterion class name its associated with based on what the user has selected to conflate (e.g. "Roads" --> `hoot::HighwayCriterion`; the complete list is below). So for instance, don't let a user select snapping for rivers if river conflation has been disabled. Only linear feature types are applicable for selection. Multiple items may be selected in the listbox.

"Generic Lines" --> `hoot::LinearCriterion` (associated matcher: `hoot::ScriptMatchCreator,Line.js`; These are lines with no type or a type that doesn't map to anything hoot can specifically conflate)
"Power Lines" --> `hoot::PowerLineCriterion` (associated matcher: `hoot::ScriptMatchCreator,PowerLine.js`)
"Railways" --> `hoot::RailwayCriterion` (associated matcher: `hoot::ScriptMatchCreator,Railway.js`)
"Rivers" --> `hoot::LinearWaterwayCriterion` (associated matcher: `hoot::ScriptMatchCreator,River.js`)
"Roads" --> `hoot::HighwayCriterion` (associated matcher: `hoot::HighwayMatchCreator` for Unifying or `hoot::NetworkMatchCreator` for Network)

**Comment by bwitham** [comment]
@curranMapper

**Comment by bwitham** [comment]
See https://github.com/ngageoint/hootenanny/pull/4794 for updated info.

**Comment by bobi7** [comment]
ref #1876
