### ISSUE TITLE
Clipped datasets do not have bounding boxes

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#188]
When clipping/subsetting data using either visual extent or bounding box there is no bounding box getting generated.  @brianhatchl  I also noticed that mapnik tiles weren't getting generated but this may end up being a separate ticket depending on the diagnosis here.  I tested on develop and release using different POI datasets e.g. Latvia500 etc..

**Comment by sisskind** [comment]
@mjeffe98 Unsure I am the right assignee -- may be more of an ingest issue as opposed to a clipping issue.  Can discuss at next sprint planning.

**Comment by mjeffe98** [comment]
@sisskind new datasets get bounding boxes but not clipped ones.  Since you wrote the original code I thought you were the best assignee

**Comment by mjeffe98** [comment]
I think this is no longer an issue
