### ISSUE TITLE
View where reviews have occurred

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#194]
Provide the ability to show what area of the AOI that you have already reviewed to prevent from going over the same area twice.  Similar to HOT tasking, where you click a square to edit, and it turns yellow.

**Comment by brianhatchl** [comment]
This was once a feature using the map-in-map.  If in review mode the map-in-map would populate with dots for reviews, yellow for open and green for resolved.  (And red for locked back when we locked reviews.  Hoot no longer does this and using optimistic locking).

**Comment by brianhatchl** [comment]
![screenshot from 2016-09-29 12 22 20](https://cloud.githubusercontent.com/assets/2600932/18962575/6c110ebc-863f-11e6-9360-754882c2bfef.png)

When in conflation review mode, map-in-map shows locations of reviews in merged dataset.
- red = current review
- green = resolved review
- yellow = open review

**Comment by sisskind** [comment]
@curranMapper can you confirm above and, if so, close ticket?

**Comment by sisskind** [comment]
pinging @curranMapper

**Comment by curranMapper** [comment]
![confirmed](https://cloud.githubusercontent.com/assets/15927720/22066683/0c812e9a-dd5c-11e6-8e08-bfd0cb38ca95.JPG)
Confirmed/closing
