### ISSUE TITLE
Get Dates for Imagery

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#196]
There is currently no known method to find out the date of your imagery that is being viewed for your background.   This is important to know, because of the differences there may be on what is collected and what is showing up on the imagery.

**Comment by brianhatchl** [comment]
Seems like it is possible to get image capture date from Bing tiles in the HTTP response header:
```
Access-Control-Allow-Origin:*
Cache-Control:public, max-age=31535971
Connection:keep-alive
Content-Length:8724
Content-Type:image/jpeg
Date:Wed, 03 Feb 2016 17:07:47 GMT
ETag:"4963"
Expires:Thu, 02 Feb 2017 17:07:18 GMT
Last-Modified:Wed, 27 Jan 2016 22:18:45 GMT
Server:Microsoft-IIS/8.5
X-AspNet-Version:4.0.30319
X-Cache-Remote:TCP_MISS from a23-79-240-26.deploy.akamaitechnologies.com (AkamaiGHost/7.4.2.1-16635586) (-)
X-Powered-By:ASP.NET
X-VE-TBE:BN20040420
X-VE-TFE:BN20251343
X-VE-TILEMETA-CaptureDatesRange:4/21/2011-4/21/2011
X-VE-TILEMETA-Product-IDs:138
```

**Comment by HokieHI** [comment]
Is this about getting the date in this view?

Thanks!
Berkley

![image](https://cloud.githubusercontent.com/assets/20308614/18517305/d529a1ca-7a69-11e6-8215-1ac9ee670e5a.png)

**Comment by sisskind** [comment]
@HokieHI No, would be specific for Hootenanny

**Comment by brianhatchl** [comment]
Is this for Bing or for EGD plugin?

**Comment by briandaviddavidson** [comment]
I believe @sisskind said it was for the EGD plugin

**Comment by brianhatchl** [comment]
We have code that does this for the image validation workflow.

Try it out (image validation) and then see https://github.com/ngageoint/hootenanny-ui/blob/master/js/hoot/control/Validation.js#L347-L348

**Comment by sisskind** [comment]
OBE
