### ISSUE TITLE
Data visibility zoom level 12-14

### ISSUE THREAD

**Issue by MappinBenny** [ngageoint/hootenanny-ui#1966]
It would be helpful, especially for network conflation, to be able to review data at a zoom level somewhere between 12-14. Zoom level 16 is great for urban dataset review, but this zoom level becomes counter-productive when reviewing large features and/or sparsely collected areas.

Workaround idea - at zoom levels 12-14, it might also be helpful to at least be able to review two matched features by themselves (but still very much attached to the rest of the network if networks are being conflated) during the post-auto-conflation cleanup phase.

**Comment by brianhatchl** [comment]
PR #1749 intends to address this, but it has languished without being merged for a long time so will have to be resurrected.

In a prior version of the Hoot UI, the tiled requests for vector data were pre-flighted with a request for the node count in each tile.  If no tile exceeded the max node per tile count (which was 10k), the editable vector data would be loaded above z16 until the threshold was exceeded.

**Comment by MappinBenny** [comment]
@brianhatchl is the 10k node count still applicable? My ignorance has me curious about the RAM strain compared to something like 20k.

**Comment by brianhatchl** [comment]
#1975 has been merged and now the UI will load up to 50k nodes above z16.
