### ISSUE TITLE
Post-conflation review (red/blue) table labels

### ISSUE THREAD

**Issue by MappinBenny** [ngageoint/hootenanny-ui#1967]
It would be helpful while resolving post-conflation issues to add a label showing which dataset is which in the red/blue tables.
![hoot_screenshot](https://user-images.githubusercontent.com/102063985/168686217-6c55b005-02a5-4247-acb5-dc789fab3553.png)

**Comment by brianhatchl** [comment]
Most times the red column is the reference and the blue column is the secondary.  But there are situations where a review may involve two features from the same layer or against a feature that has been merged during conflation.

How about something like this?

![Screenshot from 2022-06-03 12-44-27](https://user-images.githubusercontent.com/2600932/171909412-9f124046-e291-4b9a-9e98-55ca78abdf9e.png)

![Screenshot from 2022-06-03 12-44-10](https://user-images.githubusercontent.com/2600932/171909437-8072d5b9-8418-4224-8fdc-0a4e27fa8b1a.png)

![Screenshot from 2022-06-03 12-45-00](https://user-images.githubusercontent.com/2600932/171909452-e55c60e5-f97e-4a6c-b924-1489bfb9a97a.png)

**Comment by MappinBenny** [comment]
Brian... I am so sorry and embarrassed to reply 10 months after this discussion started... your suggestion would work great to help with clarity during the review process!
