### ISSUE TITLE
Nodes remain when layer turned off

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#198]
Nodes for lines remain on the screen when the layer is turned off in background setings.  Once the map is panned/zoomed, the nodes disappear. While the nodes are visible, they can be clicked on and interacted with.

**Comment by sisskind** [comment]
Before:
![issue-198-before](https://cloud.githubusercontent.com/assets/6191659/13190743/0f746d14-d72d-11e5-93db-edf6b2e53e88.gif)

After:
![issue-198-after](https://cloud.githubusercontent.com/assets/6191659/13190747/145546aa-d72d-11e5-9320-aadd5f113871.gif)

**Comment by sisskind** [comment]
@mjeffe98 Ready for test.

**Comment by mjeffe98** [comment]
@sisskind I see the fixed behavior on my local dev but not on selma.  It's strange as I would have expected to see the fix on both given that selma was rebuilt today and the commit was from friday. Can you hit selma and add DcGisRoads quickly to confirm?

**Comment by sisskind** [comment]
@mjeffe98 Which version are you using?

**Comment by mjeffe98** [comment]
doesn't look like selma develop has the modified js/id/core/connection.js with `return event.layer();` but my latest dev from local does.

I can close since the addition confirms working behavior but still curious why the discrepancy.

**Comment by mjeffe98** [comment]
local dev where behavior is working: 0.2.22_240_*
selma dev: 0.2.22_141_*
