### ISSUE TITLE
Translation Assistant on Selected Feature Classes

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#205]
As a user of Hootenanny, I need the ability to select an individual feature class or multiple feature classes from a file geodatabase when creating a new translation using Translation Assistant.  In the user interface this would take the form of being able to display the contents of a file geodatabase followed by the user selecting the feature class or classes to be brought into the Translation Assistant.  May need to take domains into account for this as well.

May be related to ngageoint/hootenanny#284 and ngageoint/hootenanny#285

**Comment by sisskind** [comment]
@mattjdnv Is this feasible to create new translation (forgetting the UI portion)?

**Comment by sisskind** [comment]
This functionality is already found within Hootenanny.

**Comment by sisskind** [comment]
@brianhatchl to confirm existing functionality

**Comment by brianhatchl** [comment]
Some findings:
* The translation script cannot filter features, it only handles attribute mapping
* We recently added code to throw an error and fail the ingest if the Translation Assistant attribute mapping fails to translate any attributes for a feature with this, `No attributes could be translated to tags!`
* Not sure if the logic to filter features belongs in the `translateAttributes` function or further up in the hoot ogr2osm command, see the commentary below

>We have a layer name filter that we use with FGDB. I'll have a try applying it to the renderDb translator.
The TDS translations use this filter to remove o2s and SRC_ layers:
// Layer name filter - Filter out all layers that match this regexp
function layerNameFilter()
{
// Drop all of the "SRC_" and "o2s_" layers
return "^(?!SRC_|o2s_)";
}
Command Line:
=== ogr.import.filter
Data Type: string
Default Value: `` The regexp to be used to filter the layer names when importing layers from an ESRI File Geodatabase. The default is to import all layers from a FGDB. Setting this variable will override the filter value that can be set by the layerNameFilter function inside a translation script.

**Comment by brianhatchl** [comment]
Regarding data sources with multiple layers (fgdb, zip of shps) TA would enforce that all attributes of all layers be either mapped or ignored before a translation script would be generated.  By removing the 'ignore remaining' feature

**Comment by brianhatchl** [comment]
@mattjdnv bringing you in to discuss.

**Comment by brianhatchl** [comment]
The ability to specify layer filters in the translation may be obviated by https://github.com/ngageoint/hootenanny/issues/283, if the upload dialog will already allow the user to specify a subset of feature classes to ingest.

**Comment by brianhatchl** [comment]
Learned today that returning null instead of {} hoot will drop the feature from the translate op.

**Comment by mjeffe98** [comment]
@brianhatchl I just want to clarify something.  If I upload a .gdb to TA that has two feature classes (we'll call them fclass1 and fclass2), when I'm doing my mapping if I only map a single attribute in fclass1 e.g. F_CODE and then save the translation, I only see fclass1 in the resulting translation.  I haven't ignored any other attributes as you can see but flcass2 is not included in the translation.

```
hoot.require('translation_assistant')
var attributeMapping = {
    "fclass1": {
        "F_CODE": {
            "Feature Code": {
                "AP030": "AP030: Road",
                "AP050": "AP050: Trail"
            }
        }
    }
};
var fcode;
var schema = 'TDSv61';

//translateToOsm - takes 'attrs' and returns OSM 'tags'
var translateToOsm = function(attrs, layerName) {
    return translation_assistant.translateAttributes(attrs, layerName, attributeMapping, fcode, schema);
};
```

**Comment by brianhatchl** [comment]
Yes, this lets you just translate the features in fclass1.  All the features from fclass2 should be dropped by the translation when you use it during ingest.

**Comment by mjeffe98** [comment]
ok then its behaving as expected.
