### ISSUE TITLE
Modify Folder Name Placeholder

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#207]
When you select "Modify" on a folder, the menu box pops up, if you change the name of the folder in the modify menu, the whole existing title disappears.  Sometimes you may want to add or delete a word without having to type the whole title in.  Some of my titles had 10 digit numbers in them and it became impossible to remember all those digits when it disappeared while changing the name.  Plus the Modify menu was not moveable, it covered up the Folder listing and you could not see the full title on the folder menu, so it became almost impossible to re-type the title unless you wrote the title down.

**Comment by sisskind** [comment]
@mjeffe98 Ready for test.  If you click in the input text field, you should have the current name to start.

**Comment by mjeffe98** [comment]
@sisskind just want to clarify that there is no "modify" option in the UI that I am aware of.  The action is to "Rename (layer name)".  Looks like it's working as expected.

**Comment by sisskind** [comment]
@mjeffe98 Yes -- Rename == Modify in this ticket.
