### ISSUE TITLE
POI merge failure

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#213]
Anytime I try to merge 2 POIs an error appears in the UI console, "poi merge failure".

rest.js:8  `Uncaught TypeError: Cannot read property 'output' of undefined`

**Comment by mjeffe98** [comment]
could be related to https://github.com/ngageoint/hootenanny/issues/302

**Comment by jchoi1267** [comment]
@mjeffe98 having trouble reproducing using DcPoi and AllDataTypes. Will call

**Comment by mjeffe98** [comment]
@bwitham @jchoi1267 looks like this is no longer an issue on latest develop

**Comment by mjeffe98** [comment]
@sisskind @brianhatchl I'm getting this error on both develop and release in my local vagrant environment.  Basically when I try to merge a POI pair in a review I get an error: _Poi merge failure._
I'm not seeing this error on Selma in either instance, only in vagrant. Can one of you take a look if you're seeing a similar issue when merging POIs in a review on your vagrant instances?


Uncaught TypeError: Cannot read property 'output' of undefined
  rest.js line 343:             var oDOM = oParser.parseFromString(resp.output, "text/xml");

**Comment by sisskind** [comment]
@mjeffe98 did not get error.  what data were you using?

**Comment by mjeffe98** [comment]
@sisskind this is occurring with all POI datasets.  I would speculate this must have something to do with port configuration but I've kept everything default.  I have multiple vagrant instances but not running simultaneously.

**Comment by mjeffe98** [comment]
rest.poiMerge = function (data, callback) {
        d3.json(window.location.protocol + '//' + window.location.hostname + ":"  +
               iD.data.hootConfig.p2pServerPort

@brianhatchl is there a way to determine which port is being used for merging POIs?

**Comment by mjeffe98** [comment]
OST http://10.0.1.12:**8096**/p2pmerge net::ERR_CONNECTION_REFUSED

**Comment by brianhatchl** [comment]
try this
```
vagrant@vagrant-ubuntu-trusty-64:~/hoot$ ps -ef | grep P2PServer
tomcat6   1899  1859  0 12:51 ?        00:00:00 node /home/vagrant/hoot/scripts/P2PServer.js port=8096 threadcount=0
tomcat6   1903  1899  0 12:51 ?        00:00:00 /usr/bin/nodejs /home/vagrant/hoot/scripts/P2PServer.js port=8096 threadcount=0
tomcat6   1904  1899  0 12:51 ?        00:00:00 /usr/bin/nodejs /home/vagrant/hoot/scripts/P2PServer.js port=8096 threadcount=0
tomcat6   1905  1899  0 12:51 ?        00:00:00 /usr/bin/nodejs /home/vagrant/hoot/scripts/P2PServer.js port=8096 threadcount=0
tomcat6   1906  1899  0 12:51 ?        00:00:00 /usr/bin/nodejs /home/vagrant/hoot/scripts/P2PServer.js port=8096 threadcount=0
tomcat6   1908  1899  0 12:51 ?        00:00:00 /usr/bin/nodejs /home/vagrant/hoot/scripts/P2PServer.js port=8096 threadcount=0
tomcat6   1911  1899  0 12:51 ?        00:00:00 /usr/bin/nodejs /home/vagrant/hoot/scripts/P2PServer.js port=8096 threadcount=0
tomcat6   1913  1899  0 12:51 ?        00:00:00 /usr/bin/nodejs /home/vagrant/hoot/scripts/P2PServer.js port=8096 threadcount=0
tomcat6   1917  1899  0 12:51 ?        00:00:00 /usr/bin/nodejs /home/vagrant/hoot/scripts/P2PServer.js port=8096 threadcount=0
vagrant   4386  2404  0 15:04 pts/0    00:00:00 grep --color=auto P2PServer
```

seems like your merge service is not running

**Comment by mjeffe98** [comment]
vagrant@vagrant-ubuntu-trusty-64:~/hoot$ ps -ef | grep P2PServer

```
tomcat6   1490  1466  0 Apr05 ?        00:00:00 node /home/vagrant/hoot/scripts/P2PServer.js port=8096 threadcount=0
tomcat6   1495  1490  0 Apr05 ?        00:00:00 /usr/bin/nodejs /home/vagrant/hoot/scripts/P2PServer.js port=8096 threadcount=0
tomcat6   1496  1490  0 Apr05 ?        00:00:00 /usr/bin/nodejs /home/vagrant/hoot/scripts/P2PServer.js port=8096 threadcount=0
tomcat6   1497  1490  0 Apr05 ?        00:00:00 /usr/bin/nodejs /home/vagrant/hoot/scripts/P2PServer.js port=8096 threadcount=0
tomcat6   1499  1490  0 Apr05 ?        00:00:00 /usr/bin/nodejs /home/vagrant/hoot/scripts/P2PServer.js port=8096 threadcount=0
vagrant   8691  8658  0 15:09 pts/0    00:00:00 grep --color=auto P2PServer
```

**Comment by mjeffe98** [comment]
Ok figured it out and solved my problem.  My Vagrantfile was using the wrong port (8095) for the merge nodejs service and it seems like 8096 must have been either pre-baked or cached.  When I changed this to 8096, POI merged worked.  Up to this point I was using vagrant reload and my assumption would be that it would use the port specified in the Vagrantfile would be the one used but not in this case.

```
  # merge nodejs service
  config.vm.network "forwarded_port", guest: 8095, host: 8095
```
