### ISSUE TITLE
Possible improvement for Save Review

### ISSUE THREAD

**Issue by mikejeffe** [ngageoint/hootenanny-ui#214]
Just thinking off the cuff here but thinking if there would be a way to add the names of the features under review automatically to the title.  Just a quick way to provide some additional context for people sharing/saving reviews.

**Comment by mjeffe98** [comment]
@jchoi1267 any ideas on this?

**Comment by jchoi1267** [comment]
@mjeffe98 When you say names of features do you mean feature id?

**Comment by mjeffe98** [comment]
no I was thinking the actual name tag.  For example: `Dome hotel` & `Port Hotel`. We can talk more about it with the group.  I like the added context of the name and given that some names are in foreign languages, adding it automatically means the user doesn't have to type it if they want to have that as part of the description.  These are just ideas.

**Comment by bwitham** [comment]
@jchoi1267 @mjeffe98 Should this be promoted to a proposed feature?

**Comment by jchoi1267** [comment]
@bwitham That makes sense.
