### ISSUE TITLE
Layer name has a fixed limit in the Add Dataset window

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#216]
Since we now have the ability to expand the side bar, it doesn't make sense that we would limit the char display for layer names e.g. PortAuPrinceMGCPRoadsBu..... in the tree view.

![image](https://cloud.githubusercontent.com/assets/7560096/12860135/93445a1a-cc0f-11e5-8e75-7c587250badf.png)

@sisskind what do you think?

**Comment by sisskind** [comment]
@mjeffe98 Ready for test on develop branch.

**Comment by sisskind** [comment]
@mjeffe98 did not test this method scaled with hundreds of datasets. If possible can you test in that environment? If not let me know and I can spin up dummy datasets (just blank titles) to test scale.

**Comment by sisskind** [comment]
@mjeffe98 merged into develop.  tested with 100s of datasets and works.  Little lag, but unsure if that is my machine or not.

**Comment by mjeffe98** [comment]
tested with names as long as MgcpPortAuPrinceBuildingTest_12312hf22jh23r23rjhfskjhds3232j3hfsefw23rfwefuh23r23234.osm and seems to work fine.
