### ISSUE TITLE
Translation Assistant errors out when trying to upload a .zip containing a gdb.

### ISSUE THREAD

**Issue by mikejeffe** [ngageoint/hootenanny-ui#219]
Data for this provided in https://github.com/DigitalGlobe/dgis-devops/files/116646/hg_SY_RelPOI.zip 

When you upload hg_SY_RelPOI as the .zip it errors out with the message below but when you unzip the contents and load the .gdb folder itself the TA does not produce an error.

"2/8/2016, 3:11:19 PM: Job failed.\nFailed to execute.Error running attribute-count:\nattribute-count takes at least one parameter.\nmake: **\* [step1] Error 255\n\n\nFiles can be one or more shapefiles, consisting of .shp, .shx, and .dbf components at a minimum.\n\nOr a zip file containing one or more shapefiles or a folder that is a file geodatabase.\n\nFolders can contain one or more shapefiles or be a file geodatabase."

**Comment by mjeffe98** [comment]
Note I'm not referring to all cases, just this particular dataset.

**Comment by brianhatchl** [comment]
Just tried this and it worked
