### ISSUE TITLE
Clip tools output name removes text when you click in the field

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#222]
Similar to fix for https://github.com/ngageoint/hootenanny-ui/issues/207 we should keep the original text in the Output Name so that the user is not required to re-enter the original text.  Should just keep the name and allow the user to modify existing not blank it out completely.

**Comment by mjeffe98** [comment]
![clip output name](https://cloud.githubusercontent.com/assets/7560096/12957333/01ecb4e2-cfe1-11e5-9eba-e7e7f871f45f.gif)

**Comment by sisskind** [comment]
Updated.  Merged into release and develop.  @mjeffe98 ready for test.
