### ISSUE TITLE
Move line width toggle to side bar menu

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#223]
Move UI Settings tab from manage tab to the sidebar, along with the "Fill Areas" menu.

**Comment by sisskind** [comment]
![issue-223](https://cloud.githubusercontent.com/assets/6191659/12960801/34482a64-d00b-11e5-8328-c1edd4f55d11.png)

**Comment by sisskind** [comment]
@mjeffe98 Ready for testing.  Took your advice by placing it in higher visibility area within UI.

**Comment by mjeffe98** [comment]
@sisskind very nice.  I think it is easier to use now.
