### ISSUE TITLE
Nodes for hidden layers appear

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#225]
During conflict review, nodes for a hidden layer are visible when a feature under review is selected.  Image to follow with example.

**Comment by mjeffe98** [comment]
Josh I believe this issue has been resolved with https://github.com/ngageoint/hootenanny-ui/issues/144.  What exactly is a "hidden layer"?

**Comment by sisskind** [comment]
@mjeffe98 Believe this is different.  Hidden layer in this context is one with visibility turned off.  It would be the reference dataset, for example, vs the conflated result.

**Comment by mjeffe98** [comment]
Ok if that's the case please provide an example with datasets.  When #144 was fixed, there was a short period of time after when I noticed that during review some of the nodes were displaying for merged features but currently, I am unable to reproduce that issue.

**Comment by sisskind** [comment]
OBE
