### ISSUE TITLE
Provide a mechanism to view conflation stats and info after merged layer is removed from Map

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#228]
If you set Collect Stats = true, you can view the Parameters, Options, Statistics for a given conflation job but once the layer has been removed from the map following the resolving of any review, the 'i' button no longer appears making it impossible to view the layer stats from the UI.  We should probably provide a mechanism to allow users to view this as it might be necessary to review the parameters for a given conflation job after the fact.

**Comment by brianhatchl** [comment]
I think you mean
>once the layer has been removed from the map following the resolving of **all** reviews

But I see what you mean, it's an oversight on my part.  The intention was any time you add a dataset to the map, it should display the 'i' button (stats, review-mode, or not).

**Comment by mjeffe98** [comment]
yup, maybe we can just say, allow the layer information to be viewable after reviews have been resolved..
