### ISSUE TITLE
Fix imagery validation UI code

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#229]
Imagery validation UI code needs to catch up with the changes made for the review as relation refactoring.

**Comment by brianhatchl** [comment]
@jchoi1267 @jasonsurratt @bwitham Question about review relations as I get the imagery validation workflow re-wired to match.  I notice that we are not deleting the relation when a review is resolved, rather we just update the tag `hoot:review:needs = no`.  What was the reasoning behind this?

I was writing the image validation code to remove the member feature from the relation and then delete the relation.  It seems better to me not to leave the resolved/verified review relations behind in the data.

Thoughts?

**Comment by bwitham** [comment]
I'm sure Jong knows better, but some of the reasoning was for provenance.  So, I can see what was reviewed after someone reviewed it.  There's no user accounts, so I guess you still won't know the who part...just the what was reviewed part.  And then I guess that new review bookmarks feature that he added would also depend upon that as well....if you bookmark a review, you may want to hold onto that bookmark indefinitely....not sure if that was the use case or not for that one.

**Comment by jasonsurratt** [comment]
This is a bit foggy for me, but my recollection has to do with the way reviews are assigned to individuals. There are some notes on redmine here:

https://dgredmine/redmine/projects/hootenany/wiki/Developer_-_ReviewRedesignwNotes#Current-iD-mechanism-for-handling-relations

If you delete the reviews then you lose the information that a review has already been resolved and increase the odds that two people will overlap in reviews.

After all reviews are resolved I suggest deleting them all from the data set.

**Comment by brianhatchl** [comment]
See https://github.com/ngageoint/hootenanny-ui/pull/234 for behavior descrition.

**Comment by brianhatchl** [comment]
@jchoi1267 can you comment on this?
> If you delete the reviews then you lose the information that a review has already been resolved and increase the odds that two people will overlap in reviews.

From what I can tell indirectly, the review/next endpoint doesn't consider reviews set to `hoot:review:needs = no` when getting the next review and only considers the `hoot:review:sort_order`, is that correct?

That is, if reviews were deleted after resolution, the sort_order (offsetseqid param in the review/next url) is all that's needed to attempt to maintain geographic locality.

Also, for review bookmark, is it possible (or is there a use case) to revisit a bookmarked review that has been resolved?

**Comment by jchoi1267** [comment]
@brianhatchl 
1. Following happens when review/next is called.
a. Service looks at current review offset sequnce id and fetches the relation review with select id from current_relations_x where tags->'hoot:review:needs' = 'yes' and tags->'hoot:review:sort_order'='seqidxxx'
b. if we get the hit from a we return else we call Random reviewable.

So bottom line is we do consider hoot:review:needs

2. We made decision not to delete any reviewbale relation we just mark hoot:review:need

3. For review bookmark, it is possible to get to resolved item but we block it by first checking if that one has been reviewed.

**Comment by brianhatchl** [comment]
It still sounds to me like the only ill effect of deleting reviews after they are resolved would be losing information on the number of resolved reviews.

**Comment by jchoi1267** [comment]
@brianhatchl Aha I guess it was good idea to keep notes on decisions made during review refactor. :-) Please see following (3. Resolve all reviews: section)

https://10.194.71.155/redmine/projects/hootenany/wiki/Developer_-_ReviewRedesignwNotes

**Comment by mjeffe98** [comment]
Tested with a sample dataset using DG GBM/EGD and getting the appropriate tags when validating for options 1, 2, or 3.  Looks like the tags are there now: `source:geometry` is capturing the GBM imagery type (i.e. Least Cloud Cover), `source:geometry:sensor` is valid, and `source:geometry:date` plus additional ones associated with the validation process.
