### ISSUE TITLE
Handle large one to many during relation review

### ISSUE THREAD

**Issue by jchoi1267** [ngageoint/hootenanny-ui#23]
When there are large numbers of one to many (ie 686 during Brazil review) browser memory stack blows while trying to update history. To fix the problem, do not update relation during automerge but create manual changeset before resolving.

**Comment by jchoi1267** [comment]
Added code change to handle update references in resolve

**Comment by bwitham** [comment]
This looks like its working.  I'm going to spot check some of the really large changesets that happen as a result of this in the Brazil data.  The large changeset saves are a little slow, so I'll also profile that part of the code and see if anything can be sped up.

**Comment by bwitham** [comment]
I'd say we're good on this one.  I actually am not running into the very large Brazil updates anymore.  That must be b/c the randomness of the starting review kicking in.  If I had time to click through all 12k reviews, then I would hit those reviews that cause the large changesets...which is ~25 of them from what I remember originally.
