### ISSUE TITLE
Unchecking default Line width makes red/blue review highlights invisible

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#231]
If you uncheck the default line width to adjust the thickness it inadvertently makes the review highlights disappear. It is more pronounced with road reviews but I did check POIs as well.  When that option is unchecked the POIs get a highlight that is transparent and has some thickness matching the value but certainly not the desired effect.

![image](https://cloud.githubusercontent.com/assets/7560096/12992975/62768a04-d0cc-11e5-8600-fd60a5b4cccf.png)

**Comment by mjeffe98** [comment]
@sisskind I see the commit fixed the issue with POIs but not lines or building polys
![issue-231](https://cloud.githubusercontent.com/assets/7560096/13087163/6dc719be-d49b-11e5-8e6c-0686a41c1a29.gif)

**Comment by sisskind** [comment]
@mjeffe98 Seeing that as well - a premature push.  Will take care of it.

**Comment by sisskind** [comment]
@mjeffe98 in develop branch.  pushing to release shortly.
