### ISSUE TITLE
Output name in export dialog clears name when you click in the field

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#232]
Similar issue to https://github.com/ngageoint/hootenanny-ui/issues/222, clicking in the output name field blanks out the value making it more cumbersome to users.  It should keep the existing name but let you edit the text without removing.

**Comment by sisskind** [comment]
Export dialog in manage tab has been fixed.

**Comment by sisskind** [comment]
Export dialog following review has been fixed.

**Comment by sisskind** [comment]
@mjeffe98 Committed to release and develop.  Ready for test.
