### ISSUE TITLE
Fix failing node tests

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#24]
node tests

IngestTest.js

* etl load should return a sensible error
* etl load should load a couple of ... shapefiles
* etl load should load a couple of ... shapefiles in a zip

**Comment by bwitham** [comment]
@jchoi1267 There are three failing ingest node.js tests in the nightlies.  I figured you could fix them quicker than I could, but let me know if you need help.  I think I almost have the cucumber test fixed.  Thanks.

**Comment by jchoi1267** [comment]
Looks like we are missing UTP.js . Tracking down

**Comment by jchoi1267** [comment]
UTP.js is fouo and need to modify the test script

**Comment by jchoi1267** [comment]
Committed the fix

**Comment by bwitham** [comment]
sent you an email...there's one test still commented out that needs to be fixed, if possible

**Comment by bwitham** [comment]
* some tests failing on selma
* the disabled test should test the case where empty input is sent to the ingest upload and verify an error response is returned

**Comment by bwitham** [comment]
There are two new tests failing under old-tests.child.  They're probably from changes from the 5496 merge.
