### ISSUE TITLE
Cannot create feature with different schema

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#242]
As a user of Hootenanny, I would like to create a feature using a TDSv61 schema type.  When I try to create a feature, though, I get an error:
```
GET http://localhost:8094/tdstoosm?fcode=AL010&translation=TDSv61 net::ERR_EMPTY_RESPONSE
```
![schema.png](https://files.zenhub.io/56c35ff816c1bcfd6293acb0)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by jchoi1267** [comment]
This was caused by not having hoot global variable not being passed to submdoule. Created local variable and also tested to make sure stxxxl gets clean up.

**Comment by mjeffe98** [comment]
@sisskind not seeing any issues with TDSv61 feature creation with version below.  Is that enough to close this?

Hootenanny Core - Version: 0.2.21_225_g56cba2b - Built By: root

**Comment by mjeffe98** [comment]
Recreated on both develop/rc on selma and got the ERR_EMPTY_RESPONSE.  Testing on my local dev that error doesn't occur when creating or editing features using TDS61/4.

**Comment by brianhatchl** [comment]
I'm still getting this error on my local vagrant vm, even with the commit, https://github.com/ngageoint/hootenanny/commit/009ef27894dcd6563e049f7b6bbaf0bb84ee40f9.  @sisskind can you confirm or deny?

**Comment by sisskind** [comment]
Reopening, as I'm getting it too.  Have been working through it this morning on vagrant VM.

**Comment by sisskind** [comment]
@brianhatchl @jasonsurratt @jchoi1267 the HootJs.node file is being created.

**Comment by mjeffe98** [comment]
On the latest develop I have any issue when making this point AL015, Settlement.  That seems to be a problem with both TDSv61 and v40 within the UI.  Adding @mattjdnv to discussion in case he has some insight.

GET http://10.194.71.96:8101/tdstoosm?fcode=AL015&translation=TDSv61 net::ERR_EMPTY_RESPONSE

GET http://10.194.71.96:8101/tdstoosm?fcode=AL015&translation=TDSv40 net::ERR_EMPTY_RESPONSE

**Comment by sisskind** [comment]
@mjeffe98 is this an AWS box?

**Comment by mjeffe98** [comment]
@sisskind no this is selma

**Comment by brianhatchl** [comment]
We have a solution to the vagrant vm problem here, https://github.com/ngageoint/hootenanny/pull/355.

The AL015 Settlement problem was the new 'logVerbose' undefined in the context of the translation server.  @jchoi1267 has fixed that here https://github.com/ngageoint/hootenanny/commit/ae97373f3ac9a6df5f1ecea1131798b3029d166a.

**Comment by brianhatchl** [comment]
@mjeffe98 @jchoi1267 Do we need to cherry-pick a couple of these commits for the release branch?

**Comment by mjeffe98** [comment]
@brianhatchl I'll leave that up to @sisskind @jchoi1267 and your discretion.  The release should probably be updated with #242, #355.

**Comment by sisskind** [comment]
Yes we do.  Will make sure to update with at least #242 and #355, unless someone wants to commit to release this evening (please advise if anyone does so: @brianhatchl @jchoi1267)

**Comment by brianhatchl** [comment]
https://github.com/ngageoint/hootenanny/pull/355 is not necessary because the commit that necessitated it is not in release, https://github.com/ngageoint/hootenanny/commit/606a5a56352f4c66876c6402230f2a34564548e9#diff-73ad4c834f30041f63419d3742bced2f

**Comment by sisskind** [comment]
@brianhatchl so just #242 then?

**Comment by brianhatchl** [comment]
Yes, I believe so.  I tested hoot-release-rc on selma:8093 and it presents this error.

**Comment by mjeffe98** [comment]
Has #242 been merged into the release branch?

**Comment by sisskind** [comment]
@mjeffe98 Just did. Closing ticket.
