### ISSUE TITLE
Write dataset ingest cucumber test

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#25]
The existing one was in nodejs with non-public data, so write a cucumber one so we don't go backward in test coverage after ngageoint/hootenanny#385.

* create test-files/ui/fgdb-ingest.feature
* create test-files/ui/osm-ingest.feature
* create test-files/ui/shapefile-ingest.feature

**Comment by sisskind** [comment]
@bwitham I see the existing node tests as:
* ConflateTest.js
* IngestTest.js
* LoadTest.js
* TestUtils.js

Accurate?  Could ConflateTest.js already be considered replaced by current nightly cucumber test?

**Comment by bwitham** [comment]
@sisskind I hadn't ever looked at ConflateTest.js before, but it does look as if it could be replaced by the existing cucumber conflate test at this point.

**Comment by bwitham** [comment]
Making an attempt at this now will reduce test setup work and overall complexity in hoot in the long run, so I'm going to take a stab at it.  Will leave the nightly nodejs tests against the non public data intact, since they provide additional value.

**Comment by bwitham** [comment]
Just opened other backlog issues for what I think would be useful cucumber tests outside of conflate/ingest/export.

**Comment by brianhatchl** [comment]
https://github.com/ngageoint/hootenanny/pull/751
