### ISSUE TITLE
Invalid version for specified element error when resolving features with unresolved merge

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#252]
This issue tracks the UI errors associated with https://github.com/ngageoint/hootenanny/issues/323 and https://github.com/ngageoint/hootenanny/issues/302

If user tries to resolve all remaining reviews with an unresolved merge they get

![image](https://cloud.githubusercontent.com/assets/7560096/13226231/40bb671e-d945-11e5-87fd-36d9e742462a.png)

`Dev console: http://localhost/hoot-services/osm/api/0.6/changeset/38/upload?mapId=15 409 (Conflict)`

Using the AllDataTypes example described in https://github.com/ngageoint/hootenanny/issues/302, after that error comes up the only option is for the user to refresh the browser.  Clicking the Save button doesn't resolve the issue.

**Comment by jchoi1267** [comment]
This has been fixex by #302

**Comment by mjeffe98** [comment]
tested and works.
