### ISSUE TITLE
Layer containing unresolved reviews get's loaded twice in UI

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#253]
If you conflate DcGisRoads/DcTigerRoads and then remove the merged layer with unresolved reviews and add it back in, it seems to get loaded twice. 

Dev Console: `Uncaught TypeError: Cannot set property 'loadable' of undefined` in tools.js:97

![image](https://cloud.githubusercontent.com/assets/7560096/13226899/b9303a14-d948-11e5-81a0-55bb93040062.png)

**Comment by sisskind** [comment]
Issue appears to exist because the conflated layers are not 'loaded layers' after conflation has occurred.

**Comment by sisskind** [comment]
On second thought, it looks like the rest.getMapTags may be getting called twice when loading in dataset with reviews.

**Comment by sisskind** [comment]
@brianhatchl Will you review?

**Comment by mjeffe98** [comment]
@sisskind appears to be working correctly now.

**Comment by mjeffe98** [comment]
This issue resurfaced on develop: Hootenanny Core - Version: 0.2.22_312_g5665795_dirty.

DevConsole reports lots of entity nX not found.

**Comment by mjeffe98** [comment]
Oddly in my local dev which is running Hootenanny Core - Version: 0.2.22_328_g952e74c, this is **NOT** an issue. Not sure which to base the testing off of since the commit addressing this bug should be on both.

**Comment by sisskind** [comment]
Just ran local with Hootenanny Core - Version: 0.2.22_330_gf59b9bd_dirty and Hootenanny iD Editor - Version: 0.2.22_330_gf59b9bd_dirty and can also confirm not an issue.

**Comment by mjeffe98** [comment]
@sisskind when I was speaking to @jchoi1267 this morning he observed this but after nuking my browser cache, I don't see this on selma develop anymore.  Let's leave this open for a little longer to see if @jchoi1267 confirms that.

**Comment by sisskind** [comment]
Appears that on Selma, commit https://github.com/ngageoint/hootenanny-ui/commit/ee485941801c359e518b0e67b232b39a2938a755#diff-10e0fba248eb29056c29dd82aada4104 does not seem to have been applied, but this is appearing locally in develop and release branch.

**Comment by mjeffe98** [comment]
redeploying the wars in tomcat seems to have fixed the issue of being out of sync.

**Comment by sisskind** [comment]
This has popped up again in develop branch (at least locally for me).  @mjeffe98 can you test to see if you encounter same issue?

**Comment by sisskind** [comment]
@mjeffe98 Specifically occurring with Haiti Demo data.  May be a data issue.

**Comment by mjeffe98** [comment]
@sisskind I can't reproduce right now because I cannot conflate Haiti data on either develop or release per https://github.com/ngageoint/hootenanny/issues/490

**Comment by sisskind** [comment]
Cannot replicate -- closing.
