### ISSUE TITLE
POIs are not merging immediately after pressing merge button

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#254]
This seems to be a recent phenomenon that when merging the first POI pair in a review (typically during the first merge for a review session), there is a long delay before the POIs actually merge.  I noticed this for the dcpoi/mapcruzin dataset as well as others.  Although the delay was more pronounced when hitting selma remotely via proxy, I did observe this locally.  To recreate:

1) select any two POI datasets and conflate
2) when review loads click merge for first pair and record time for merge to occur
3) if it doesn't appear that POIs are merging, pan map slightly and see if they merge.

I've seen delays up to and beyond 1 min and some cases where the merge does not occur on the screen until a map event is triggered (pan, zoom, etc.).  In dev console you see a lot of Uncaught Error: entity X not found.

**Comment by mjeffe98** [comment]
Also might be good if @brianhatchl confirms

**Comment by sisskind** [comment]
@jchoi1267 Do you have any insight?

**Comment by mjeffe98** [comment]
Similar behavior when deleting a review feature...

![delete feature](https://cloud.githubusercontent.com/assets/7560096/13261886/0dbb60a8-da17-11e5-9f6b-99bdb6a8c902.gif)

**Comment by sisskind** [comment]
@mjeffe98 Cannot replicate on develop branch.  Can you confirm this is still an issue?

**Comment by mjeffe98** [comment]
@sisskind with the latest develop I don't have this issue anymore.
