### ISSUE TITLE
Unmerged features in a review layer are white during initial layer load

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#256]
If you load a layer with unresolved reviews, the initial load displays all of the unmerged features (i.e. anything not green) as white.  Panning, zooming, or hovering over the merge button corrects this.  It consistently occurs for just the first feature upon layer reload.  This could be related to the Map redraw funkiness reported in https://github.com/ngageoint/hootenanny-ui/issues/254

**Comment by mjeffe98** [comment]
@brianhatchl if you prefer to have @sisskind looks at this when he investigates #254 feel free to reassign.

**Comment by mjeffe98** [comment]
![layerloadswhite](https://cloud.githubusercontent.com/assets/7560096/13261304/563449f6-da14-11e5-8b9e-954a1c60fa7d.gif)

**Comment by sisskind** [comment]
Appears that features are not tagged on load (tag-hoot-null).  Fixing this will fix the issue.

**Comment by sisskind** [comment]
Potentially a bug with loaded layers now adding tags for source layers.  Script now checks tags after searching loaded layers to assign feature color.

**Comment by sisskind** [comment]
@mjeffe98 ready for test
