### ISSUE TITLE
Fix Translation Assistant icons

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#257]
Looks like something has been inadvertently added to the TA buttons when you search for tags or set up the value mappings.  An added arrow and line.  Seeing this on develop and release.

![image](https://cloud.githubusercontent.com/assets/7560096/13263706/9fadd330-da1f-11e5-80d9-9cc0e9ba8f68.png)

**Comment by mjeffe98** [comment]
![image](https://cloud.githubusercontent.com/assets/7560096/13263767/e4c56dc0-da1f-11e5-8aef-4d2b42228c4c.png)

**Comment by brianhatchl** [comment]
I saw that too working #208 and I've fixed it as part of that.
