### ISSUE TITLE
Merged POI counts don't appear in Stats table

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#258]
When conflating POI datasets such as AllDataTypesA/B or dcpoi/mapcruzen, it doesn't appear that the merged counts for POIs are getting populated in the table.  Looks like there are POIs being merged during conflation based on the color (green) and tag values but the table shows 0 merged POIs.  I find cases where merged buildings and roads appear in the table but never POIs.  

![image](https://cloud.githubusercontent.com/assets/7560096/13265168/746ed1b8-da26-11e5-9b5c-8ac65806767d.png)

**Comment by brianhatchl** [comment]
This is most likely a bug in the stats computation for POIs.  Can you clip out a minimal set of data (like two points from each, with one being conflated in the output) and export to osm and open an issue in the main hoot repo?

**Comment by mjeffe98** [comment]
https://github.com/ngageoint/hootenanny/issues/378
