### ISSUE TITLE
Right-click menu dataset options not showing correct number of selected items.

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#260]
Select a dataset by highlighting it in yellow, then right click and delete.  First delete will show the correct number of features being edited (1).  However when you select additional datasets and right-click, the number shown in the menu (#) doesn't not reflect the number of selected features.  It looks like its getting a cumulative count rather than the actual selected dataset count.  

In below animation, a dataset is selected and deleted with the correct number identified (1).  After this delete, additional datasets are selected and the counts are wrong.  Should only show 1 dataset selected not 2 or 3.

![right-menu](https://cloud.githubusercontent.com/assets/7560096/13270357/6cb106be-da42-11e5-89f8-6f700160fbba.gif)

**Comment by mjeffe98** [comment]
This becomes a larger issue when that number of selected features becomes > 1, only certain menu options get presented like delete and move.  This has created a scenario where you have to refesh (F5) the application to reset the count so you get the full right-click context menu options associated with the data selected.

**Comment by sisskind** [comment]
@mjeffe98 ready to test in release or develop
