### ISSUE TITLE
Mapnik rendering not working with clipped layers

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#262]
When you use the clip tools, the mapnik tiles don't appear to get generated so you just have the empty bbox with the warning message indicating that you need to zoom.  Seems to me that we would want to be consistent when generating any new hoot layers using the clip work flow to ensure the visualization is the same across the board.

To reproduce, pick any larger layer ingested in Hoot that has mapnik rendering and clip an area out that exceeds the typical node/area threshold for displaying raw osm data in the viewer.  You should just get a bbox when you load the layer.

**Comment by brianhatchl** [comment]
I just tried this and the clip operation does not trigger the creation of a renderdb.  So the proper fix here is  to add the export render db job to the chain in the ClipDataResource.
