### ISSUE TITLE
Show all reviews associated with selected feature

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#264]
Provide mechanism to select POI or building, have a line segment connect selected feature with all associated review features, and provide click event for line segment to go to that specific review.  Will also need to turn off auto-advance on review resolve.

Why do we want to do this?

Providing this function will allow the user context for all reviews surrounding one feature, so that they will be able to make the most educated decision when deciding to merge, delete, or ignore a review.  They will also be able to jump to other reviews without having to make a decision on the current review pair.

First create for POIs, then move to buildings.

**Comment by sisskind** [comment]
Edges connecting the features should be created w/in the layer-data.

**Comment by sisskind** [comment]
@jchoi1267 did you make any progress/assign to a branch?

**Comment by jchoi1267** [comment]
@sisskind almost forgot. I will commit whatever I have to branch. Hold on

**Comment by sisskind** [comment]
@jchoi1267 Great.  Just reference this issue in commit and it should link up

**Comment by jchoi1267** [comment]
@sisskind created branch 264

**Comment by sisskind** [comment]
Suggested updates:
* When you click resolve, remain within other relations for feature if they exist
* Hide any merged relations

**Comment by sisskind** [comment]
@brianhatchl found error where initial review item is being resolved even after traversing to different pair.

**Comment by mjeffe98** [comment]
good job with this!
