### ISSUE TITLE
Search on feature creation/edit is not returning the expected results

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#265]
When I search #preset-search-input for desired feature type, it is not returning expected results.  This may be a filtering issue or a deeper issue that requires further investigation.

**Comment by sisskind** [comment]
Appears that the preset value was being overwritten by only the defaults and not the entire list.  This is remedied, but will test again before committing to develop and release.

**Comment by sisskind** [comment]
looks like it was only searching on list of presets as opposed to entire list of options. May need to find a happy middle ground between the two so not everything is returned, but all is probably better than none.

**Comment by jchoi1267** [comment]
@sisskind Is this ticket on search field for presets where you type in the name and list shows (i.e. for TDSv61 or TDSv40)?

**Comment by sisskind** [comment]
@jchoi1267 Yes, on feature creation.  It appears that it was only searching presets and not the entire list.

**Comment by sisskind** [comment]
@drew-bower Would like to demo this for you tomorrow/when you have time to see if it meets your needs.  Would then want to close and open a new ticket to limit number of returns or tighten the returned values based on input (i.e. 'soccer' shouldn't return 'shoemaker' if we can avoid it).

**Comment by drew-bower** [comment]
@sisskind I'll be in the office tomorrow.  Looking forward to it.

**Comment by sisskind** [comment]
@mjeffe98 ready for test

**Comment by mjeffe98** [comment]
typing "soccer" incidentally does return shoemaker but I do see the difference in search results before and after commit https://github.com/ngageoint/hootenanny-ui/issues/265.  Looks like prior when you search for "stadium" it didn't even return "Stadium" in the results and now it does.
