### ISSUE TITLE
Make tag value comboboxes default to sort alphabetically

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#266]
In the entity editor pane, currently it appears that there is no order to how tags are sorted.  They should at least be sorted alphabetically.

**Comment by mjeffe98** [comment]
@sisskind how is this different from the current behavior where you can sort the "All tags"?  For the entity editor pane, I notice that the non 'all tags' fields i.e. Name, Surface, Width, that are part of the OSM presets are not listed alphabetically.

I am using:  Hoot Core: 0.2.22_311_g76ba614

![image](https://cloud.githubusercontent.com/assets/7560096/13443698/1fab1060-dfb7-11e5-8e78-69ee63bde259.png)

**Comment by sisskind** [comment]
This alphabetizes the values within each combo box as opposed to each row.

This electronic communication and any attachments may contain confidential and proprietary information of DigitalGlobe, Inc. If you are not the intended recipient, or an agent or employee responsible for delivering this communication to the intended recipient, or if you have received this communication in error, please do not print, copy, retransmit, disseminate or otherwise use the information. Please indicate to the sender that you have received this communication in error, and delete the copy you received.

DigitalGlobe reserves the right to monitor any electronic communication sent or received by its employees, agents or representatives.

**Comment by mjeffe98** [comment]
Ok I see it now with the combo box amenity.  Before the kvp were just listed and now they are sorted alpha.

**Comment by mjeffe98** [comment]
While the "All Tags" combo-box values are sorted alphabetically, the default attributes for each schema type are not sorting properly e.g. Feature Function with TDSv61/40.

![attribute sort](https://cloud.githubusercontent.com/assets/7560096/13479873/d7e4d2ce-e08e-11e5-8062-f009dfd6ed1f.png)

**Comment by sisskind** [comment]
@mjeffe98 unable to replicate.  can you provide a specific example aside from the one above?

**Comment by mjeffe98** [comment]
@sisskind the gif shows three examples: 
1) POI, osm Place of Worship, _Religion _and _Denomination _drop downs
2) POI, osm Cafe, _Cuisine_
3) POI, TDS61, AL013:Building (Mosque), _Feature Function_ drop down
![dropdown sort](https://cloud.githubusercontent.com/assets/7560096/13538119/93ad0818-e1fd-11e5-8c74-c4255d820931.gif)

**Comment by sisskind** [comment]
Ok --- was talking about different drop down.  Will take care of that.

**Comment by sisskind** [comment]
@mjeffe98 Ready for test.  All combo boxes should be alphabetized now.

![issue-266](https://cloud.githubusercontent.com/assets/6191659/13540661/d49cc39a-e225-11e5-8aa0-dc945126d6b8.png)

**Comment by mjeffe98** [comment]
all working now.  Thanks @sisskind
