### ISSUE TITLE
Basemap upload ignores defined Basemap Name

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#267]
If you specify a Basemap Name for custom basemap it does not use that name but rather saves it using the file name.

**Comment by jchoi1267** [comment]
Fixed. It was caused by replacing with file name all the time.

**Comment by mjeffe98** [comment]
Seeing this issue again on Selma release.  When you try to rename the basemap to something other than the file name it defaults back to the basemap back to the file name.
[RomanColosseum_WV2naturalcolor_clip.zip](https://github.com/ngageoint/hootenanny-ui/files/176560/RomanColosseum_WV2naturalcolor_clip.zip)

**Comment by treycaldwell** [comment]
@jchoi1267 is correct, the filename is always overwriting the user-input Basemap Name.  Didn't see the fix so I'm assuming he just forgot to push it.

**Comment by treycaldwell** [comment]
This is currently fixed in develop by commit 38e8ef48d7b9470a406e8c292ad04f3a347b5a95

**Comment by mjeffe98** [comment]
tested it on develop and latest release and it works.  probably was just a matter of time for commit to cycle through.
