### ISSUE TITLE
Renaming layer breaks mapnik rendering for original layer

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#269]
If you rename a layer after it has been ingested, it appears that the renderdb loses the reference and cannot display the mapnik tiles for that layer.

To reproduce:
1) ingest a dataset that is large enough to use mapnik (test_MGCP.osm works)
2) display layer on map to confirm mapnik rendering is on
3) change the layer name in the datasets tab
4) reload layer and mapnik tiles will no longer display

**Comment by mjeffe98** [comment]
[test_MGCP.zip](https://files.zenhub.io/56cf809a596ff08d3a7b6318)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by brianhatchl** [comment]
The proper fix for this is to use the dataset map id in the renderdb name instead of the map name.
