### ISSUE TITLE
Entity Editor - Filter by type change doesn't search

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#280]
When changing the filter type for the entity editor, it should search on that filter if there is anything in the search field.  Currently, it will only provide the default values for that filter type.

**Comment by sisskind** [comment]
@mjeffe98 ready for test

**Comment by mjeffe98** [comment]
tried to test on latest develop but still getting the same errors not finding the feature with different filter by type options.  will try again tomorrow.

**Comment by mjeffe98** [comment]
tested on Version: 0.2.22_335_gae0ce65_dirty
