### ISSUE TITLE
Consider changing dataset ingest "Success..." warning message from red to Green

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#282]
I think that the red warning message that occurs every time during ingest causes users to think that there was an error with the files ingested.  The warnings indicate that there were issues identified in the log but the UI exposed error log does not show these messages and would then require the user to have access to the Catalina.out file to examine further.  Should we include this kind of warning message all together or consider changing it to green so as not to confuse the user?

@sisskind @brianhatchl @jchoi1267 thoughts?

SUCCESS: but the job has completed with warnings. For detailed log goto Manage->Log

**Comment by mjeffe98** [comment]
I would extend this to any message that says SUCCESS:.... i.e. after conflation.  I think there is an association with RED and error which although technically valid creates a false sense of security with the output.

**Comment by sisskind** [comment]
@mjeffe98 alternative -- instead of making warnings green, what about gold?

![issue-282](https://cloud.githubusercontent.com/assets/6191659/13532901/ede2e336-e1fb-11e5-984b-d1162af3b0b6.png)

**Comment by mjeffe98** [comment]
I think it's better than red. I just generally equate success with green that's all. Longer term we should provide users with more information on the warnings if they occur.  I've never seen an ingest that didn't come with warnings so maybe we should just turn these off.

**Comment by sisskind** [comment]
Can definitely turn them off completely for that specific warning if that is the desired approach.

**Comment by mjeffe98** [comment]
perhaps it would be good to get consensus from @brianhatchl and @bwitham.  Seems to me that if the default response to a successful ingest is always completed with warnings, the value of showing that is somewhat lost since a) there are no warnings to show and b) there aren't any cases (that I am aware of) where a successful upload would not trigger warnings.

**Comment by bwitham** [comment]
Determine what the warnings are and why they're occurring.  Should they be logged as warnings?  If so, how can they be eliminated?  Don't turn them off by default.  We generally get in trouble when exceptional behavior doesn't bubble up to the ui.

**Comment by sisskind** [comment]
@bwitham agree with that sentiment.  more inclined to lean gold in color vs. removal.

**Comment by sisskind** [comment]
@bwitham @mjeffe98 @brianhatchl is it possible to come to a consensus on this today?

**Comment by bwitham** [comment]
I vote for the three color idea...separate for success, warnings, error.  However, many of the jobs we run from the ui get warnings back from the core...so you're going to get gold a lot.  So, I'm wondering if those things that are happening are really warning worthy.  Will open a separate issue to look into that.

**Comment by mjeffe98** [comment]
I think you can do green - success, yellow - warning, red - error.  I don't know where "gold" came from but its kind of out of the standard color sequence.  Let's just stick with convention for now.

**Comment by sisskind** [comment]
Can go with any color -- went for something less threatening than red but harsher than green.  Gold shows up better than yellow.

**Comment by mjeffe98** [comment]
I'll leave that decision up to you then what looks best.  We're not going to resolve the issue with unnecessary warnings until later on in the sprint when @bwitham has a chance to dig in.

**Comment by sisskind** [comment]
So can we mark this as complete?

**Comment by mjeffe98** [comment]
Sure mark as complete.
