### ISSUE TITLE
When POI review loaded and if review against not in viewport we get entity not found error

### ISSUE THREAD

**Issue by jchoi1267** [ngageoint/hootenanny-ui#284]
When POI review loaded and if review against not in viewport we get entity not found error

1. Conflate Latvia data
2. Go into review item where review against item is not within view port
3. Press Merge
4. Throws Uncaught Error: entity n5487_630 not found

**Comment by mjeffe98** [comment]
@jchoi1267 I don't see this behavior on selma release running v0.2.22_129_g724dd7b.  However on latest develop, I get the entity X not found error when the review layer containing unresolved reviews is loaded and the layer appears twice as described in https://github.com/ngageoint/hootenanny-ui/issues/253.  When I merge a POI review where a review item is not visibly within the view port (not sure how you define "within view port" other than not visible on current map extent from your original comment), I don't get this error.

**Comment by mjeffe98** [comment]
I see the Uncaught Error in dev console.  How does this get manifested within the UI?

**Comment by jchoi1267** [comment]
@mjeffe98 committed to release branch.

**Comment by mjeffe98** [comment]
@jchoi1267 shouldn't this also be committed to develop?

**Comment by mjeffe98** [comment]
Rebuilt release to 0.2.22_144_gfd8b6bf_dirty and tested.  Not getting any errors for test case in UI or in the dev console anymore.
