### ISSUE TITLE
Hovering over Share Review button triggers error in dev console

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#285]
When you hover over the button the error, Missing en translation: review.sharereview.description, appears in the dev console.  It doesn't trigger an error in the UI but it might be indicative of something else happening that warrants additional attention.

**Comment by sisskind** [comment]
Did you rebuild? Can check core.yaml to see if the description was added.

**Comment by sisskind** [comment]
Can confirm that after running make, the proper description appears.

![issue-285](https://cloud.githubusercontent.com/assets/6191659/13496420/1c22dd0c-e11e-11e5-9522-33636bd4b4f7.png)
