### ISSUE TITLE
Fix the cucumber manage tab test

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#288]
Rename test-files/ui/features/manage_tab.fix-me --> test-files/ui/features/manage_tab.feature

**Comment by sisskind** [comment]
@bwitham Were you planning on doing this, or do you want to have a quick discussion and I can work on it?

**Comment by bwitham** [comment]
No, probably won't work on this one.  I fixed two of the other tests just so I could have something to run for testing out the move of the tests from nightly to hoot glacial.

**Comment by sisskind** [comment]
Ok -- you are referring to the current cucumber mange tag test, right?  Let's tag up next week to discuss but I can take this one on.

**Comment by bwitham** [comment]
yeah, the manage tab test on selma.  It will be a little more time until I can get the tests moved off of there and onto github, so it can be fixed on selma for now.

Sounds good.  I'm out tomorrow but will be working on Mon.

**Comment by sisskind** [comment]
@bwitham Wanted to double check with you RE: which manage tab cucumber test you were referring to.  The settings.feature test in hoot-ui/cucumber-tests doesn't have any tests against AllDataTypes.  Is there a different manage tab test out there?

**Comment by bwitham** [comment]
I wasn't aware of the hoot-ui/cucumber-tests directory...you must have put some tests in there awhile back.  The cucumber tests I know about are in hoot-tests/services.child/cucumber.child on selma.  

You may want to hold off on these changes...I'm maybe hours away at this point from having all the selma cucumber tests moved into the hoot repo (now that I know about hoot-ui/cucumber-tests, I may put them there instead...regardless, will merge with that dir).  You can work on the files on selma now if you want, but the merge may be a little messy at the end.

**Comment by sisskind** [comment]
No problem.  I'll push back a sprint and we can reconnect next week.

**Comment by bwitham** [comment]
Cool.  I should have it all moved over soon...will be easy to run the tests locally now.  I created a handful of issues in this repo with things I think might benefit from getting cucumber features added for them.

**Comment by sisskind** [comment]
Awesome!  Consolidating is a good idea for our tests.
