### ISSUE TITLE
Export hangs after resolving all reviews with cropped Haiti Port Au Prince data

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#290]
If you click the Export Data after resolving all reviews from the conflation of PortAuPrinceOsmPoiRoadBuilding.osm (ref) and MgcpCroppedPoiRoadBuilding.osm (secondary), the export job hangs for what seems to be an indefinite amount of time.  I'm only seeing this on the develop branch not in the release.  Appears to occur with all export file types.

Dev console reports: Uncaught TypeError: Cannot read property 'value' of null

ka.property	@	d3.min.js:3
d3.selection.value	@	d3.value.js:24
model_export.exportData	@	Export.js:21
(anonymous function)	@	tools.js:596
t	@	d3.min.js:1
(anonymous function)	@	Export.js:219
(anonymous function)	@	d3.min.js:1

**Comment by mjeffe98** [comment]
@sisskind we would want to make sure that any recent commits from develop which caused this problem don't make it back into the release inadvertently but it's my understanding this would only get merged into develop if its a real bug.

**Comment by sisskind** [comment]
@jchoi1267 is this something you'll be able to look at in the next 24 hrs?

**Comment by mjeffe98** [comment]
occuring with the Latvia500Pois datasets as well so not specific to the original datasets listed above.

**Comment by sisskind** [comment]
@mjeffe98 what file are you exporting to (OSM, FGDB, etc.)?

**Comment by jchoi1267** [comment]
@mjeffe98 Found the fix and about to commit.

**Comment by sisskind** [comment]
@jchoi1267 beat me to it!

**Comment by jchoi1267** [comment]
@sisskind Looks like this will be my last ticket. :-) Now I am watching cat channel.. LOL

**Comment by mjeffe98** [comment]
still seeing an issue after rebuilding selma develop Hootenanny Core - Version: 0.2.22_337_gf6a5ad4_dirty - Built By: ubuntu

@jchoi1267 @sisskind I wasn't planning on testing tomorrow and not sure everyone's schedule but maybe @jchoi1267 can just verify that the commit is in this release or pending a submodule sync.

**Comment by mjeffe98** [comment]
Re-tested and appears to be working as expected.
