### ISSUE TITLE
Add cucumber tests for translation ingest/edit

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#291]
Do this after ngageoint/hootenanny#385 is done.

Rename: 

* create test-files/ui/translation-ingest.feature
* create test-files/ui/translation-edit.feature

**Comment by sisskind** [comment]
@brianhatchl is this covered under translation assistant cucumber test?

**Comment by brianhatchl** [comment]
No, the TA test creates and downloads a translation, but does not save to hoot.  It could be modified to do that.

**Comment by sisskind** [comment]
No prob -- can create new test.  Wanted to reduce redundancy just in case.
