### ISSUE TITLE
Add cucumber test for datasets tab - all button clicks and right click operations

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#296]
Do this after ngageoint/hootenanny#385 is done.

Rename test-files/ui/features/dataset-tab.implement-me --> test-files/ui/features/dataset-tab.feature

**Comment by brianhatchl** [comment]
Many of these have been covered by the import/export features.

**Comment by sisskind** [comment]
@brianhatchl I believe you are correct.  I think we can close this one if you agree.

**Comment by sisskind** [comment]
Need to test:
* Add Dataset
* Add Folder
* Move/Rename Folder
* Multiselect Move
