### ISSUE TITLE
Merge VersionInfo.js and About.js

### ISSUE THREAD

**Issue by jchoi1267** [ngageoint/hootenanny-ui#297]
It appears that both VersionInfo.js and About.js shares most of the codes. Instead of having 2 copies of same code, refactor to share common code.

**Comment by sisskind** [comment]
@mjeffe98 this is ready for test.  you won't see any changes in UI.  To test, you should be able to view info via About tab or clicking upper left corner.

**Comment by mjeffe98** [comment]
@sisskind can you clarify what specifically I am looking for here?  I thought that I was able to view info via the About tab or Hootenanny upper left link before.  What changed?

**Comment by sisskind** [comment]
@mjeffe98 changes occurred behind the scenes.  If you are able to view info in upper right or about tab, then everything is kosher.  (One of those times where seeing no change means the change was made).
