### ISSUE TITLE
Delete during review at zoomed out causes failure when saved - 5496 branch

### ISSUE THREAD

**Issue by jchoi1267** [ngageoint/hootenanny-ui#30]
1 .go into review
2. Step to review item where review member has one to many relation
3. zoom out so we have only conflicts loaded
4. Delete the member
5. Press resolve

There should be error saving

**Comment by jchoi1267** [comment]
Made changes to

1. refs return all references including self. It had to be done since in one to many situation refs filtering on requested id also filtered other relation using the requested element, resulting failure to update correctly when deleted.

2. UI loads dependent elements before removing from map. This is to make sure to correctly update dependent relation when zoomed out which does not load all elements.

**Comment by bwitham** [comment]
@jchoi1267 do you have a dataset with an exact test case for this one?  I haven't seen it occur, but I may not be testing with the same data.

**Comment by jchoi1267** [comment]
I have seen this problem when using Brazil data.
1. load conflated Brazil data
2. Go to a reviewable
3. Zoom out till you see yellow triangle
4. Delete a POI which is not part of review
5. Press resolve

There should be no error from service during save..

**Comment by bwitham** [comment]
@jchoi1267 I haven't been able to reproduce the situation.  Every time in the Brazil data I zoom out to the yellow triangle, then all poi's except the ones in involved in the review disappear.  Is that expected?

**Comment by jchoi1267** [comment]
Yes. When we zoom out we load just reviewable item and references.

**Comment by bwitham** [comment]
Ok, got it.  This looks good then.
