### ISSUE TITLE
Bulk Import Improvements

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#300]
When running bulk import job, warnings can get lost in the messaging that is hidden unless user expands.  Provide better mechanism for informing user that there has been an error in processing.

**Comment by sisskind** [comment]
This ticket could also be interpreted as improving the UI of the bulk import window.

**Comment by sisskind** [comment]
To do:
- Validate layer name upon creation
- Validate layer name with custom suffix
- Check for duplicate layer names within table
- If error with one upload, continue to the next and do not hang (see ImportDirectory.js)

**Comment by sisskind** [comment]
Need to fix Cancel Jobs

**Comment by kweint** [comment]
Tested on hoot nightly with every data set at my disposal. Works great -- closing this issue.
