### ISSUE TITLE
Blue attribute box mostly off screen in some instances

### ISSUE THREAD

**Issue by curranMapper** [ngageoint/hootenanny-ui#304]
note from 3/9 training session:
Was not intuitive that when the blue attribute box appeared mostly off screen during conflict resolution was because there were no associated tags.  Is there a clearer way of visualizing so user doesn't think something is "wrong" in these instances?

**Comment by jcp2236** [comment]
CSS fixes to widen blue attribute boxes/column in #798

**Comment by kweint** [comment]
Tested on hoot nightly and the blue attribute box appears to look a-ok.
