### ISSUE TITLE
Hootenanny Snapping Toggle

### ISSUE THREAD

**Issue by curranMapper** [ngageoint/hootenanny-ui#306]
Training notes from 3/9
The current way of disabling snap feature is not intuitive and has to be re-enabled after turning off if so desired, is there possibility to temporarily suspend snapping utilizing a hot key?  ex JOSM does this when user holds down ctrl button.

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/VGI-team-repo/issues/77

**Comment by sisskind** [comment]
Create toggle to turn snapping on or off.  Would replace the pop up each time user enters mode to create new feature.  Shortcut button would also be preferred.

**Comment by sisskind** [comment]
@mjeffe98 ready for test.  should see toggle in side bar default to false and should not see pop up anymore.

**Comment by mjeffe98** [comment]
@sisskind nothing is visible in side bar.  Please provide a screencap or something to highlight this capability.  working on Hootenanny Core - Version: 0.2.23_670_g8ed167c - Built By: vagrant

**Comment by sisskind** [comment]
May have mislead -- meant Map Data

![issue-306](https://cloud.githubusercontent.com/assets/6191659/14506696/13647092-018d-11e6-836e-e99f8a51ef1d.png)

**Comment by mjeffe98** [comment]
yep see it in the Map Data panel.
