### ISSUE TITLE
Bounding box for clip is not drawing consistently in starting left mouse-click position

### ISSUE THREAD

**Issue by mikejeffe** [ngageoint/hootenanny-ui#307]
When clipping using bounding I have repeatedly observed that the bbox defined by the user does not consistently get placed in the correct starting position where the cursor is on the map.  Sometimes it does draw in the correct location, other times as shown in the animation, it draws the box way outside of where the cursor is placed on the map.  There does not appear to be any error triggered.  Observed primarily with Chrome. 

![clip boundingbox](https://cloud.githubusercontent.com/assets/7560096/13653659/ebfc4764-e607-11e5-9111-124e6e70637e.gif)

**Comment by sisskind** [comment]
https://github.com/ngageoint/hootenanny-ui/issues/536

**Comment by jcp2236** [comment]
#606 should fix this issue

**Comment by briandaviddavidson** [comment]
This needs another look. When trying to drag the box, the map moves instead.

**Comment by sisskind** [comment]
@briandaviddavidson are you clicking once to start drawing box, then clicking a second time to complete?

**Comment by briandaviddavidson** [comment]
No, I was clicking and dragging. I will try that and see if it works.

**Comment by briandaviddavidson** [comment]
On click, then drag, the bounding box works with no offset when the first point is added.
