### ISSUE TITLE
Hide color palette

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#31]
Hide color palette to avoid confusion over which dataset is which (user story).

Click icon next to dataset to show/hide palette.

**Comment by sisskind** [comment]
![color-palette](https://cloud.githubusercontent.com/assets/6191659/11223017/a8d70264-8d3b-11e5-939a-d0c2521eb348.gif)

**Comment by sisskind** [comment]
@mjeffe98 can you test?

**Comment by mjeffe98** [comment]
is this merged with develop?

**Comment by sisskind** [comment]
@mjeffe98 just merged/synced

**Comment by mjeffe98** [comment]
looks good.
