### ISSUE TITLE
Better UI Error reporting

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#311]
As opposed to just reporting what the error is, provide the line in the JavaScript where the error occurred for better debugging and determining what the actually error is.

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/dgis-devops/issues/85

**Comment by sisskind** [comment]
@mjeffe98 Ready to test.  Best way to do so:

1. Add dataset
2. Try adding same dataset (trigger error)
3. Clip dataset (get notice/success)
4. Check log

**Comment by mjeffe98** [comment]
Here's an example of conflation error: 

"3/28/2016, 3:01:16 PM: Requested job failed! For detailed log goto Manage->Log\nError\n    at http://localhost/hootenanny-id/js/hoot/model/rest.js:415:104\n    at Object.<anonymous> (http://localhost/hootenanny-id/js/lib/d3.min.js:1:10988)\n    at Object.t (http://localhost/hootenanny-id/js/lib/d3.min.js:1:1368)\n    at XMLHttpRequest.u (http://localhost/hootenanny-id/js/lib/d3.min.js:1:9850)"
3/28/2016, 3:01:16 PM: Requested job failed! For detailed log goto Manage->Log
Error
    at http://localhost/hootenanny-id/js/hoot/model/rest.js:415:104
    at Object.<anonymous> (http://localhost/hootenanny-id/js/lib/d3.min.js:1:10988)
    at Object.t (http://localhost/hootenanny-id/js/lib/d3.min.js:1:1368)
    at XMLHttpRequest.u (http://localhost/hootenanny-id/js/lib/d3.min.js:1:9850)

Ingesting same data (and not changing name) produced a log with break locations
