### ISSUE TITLE
Add the ability to set the default base map to DigitalGlobe imagery

### ISSUE THREAD

**Issue by treycaldwell** [ngageoint/hootenanny-ui#312]
Currently, this can't be done since the DigitalGlobe imagery background sources are constructed by dgservices.js after the default base map is selected.  We need to be able to set the "defaultBaseMap" in data/hootConfig.json to "digitalglobe" and have that imagery load by default.

Added a method to renderer/background.js that will set the default basemap to DG imagery when set to "digitalglobe"

**Comment by bwitham** [comment]
@treycaldwell If this is ready for review, then an associated pull request needs to be made for it and assigned to someone.

**Comment by treycaldwell** [comment]
Done.
https://github.com/ngageoint/hootenanny-ui/pull/403

**Comment by bwitham** [comment]
thanks

**Comment by treycaldwell** [comment]
Sorry about that, totally forgot to go back and close this.
