### ISSUE TITLE
Error occurs while trying to save edits in review layer

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#315]
Seeing the pop-up error, "Errors occurred while trying to save" along with associated 
errror message: 'Error uploading changeset with ID: 568 - data: (Batch entry 0 delete from current_nodes_220 where id='82024' was aborted. Call getNextException to see the cause. ERROR: update or delete on table "current_nodes_220" violates foreign key constraint "current_way_nodes_node_id_fkey__220" on table "current_way_nodes_220" Detail: Key (id)=(82024) is still referenced from table "current_way_nodes_220".) <osmChange version="0.3" generator="iD"><create/><modify><relation id="2" version="1" changeset="... (The feature may have been deleted by other user and may require reloading of the layer. Will jump to next valid review item)
Server returned status code 400'

This occurs when you delete one of the red/blue review features during review.

To recreate, follow conflation workflow described in:
https://github.com/ngageoint/hootenanny-ui/issues/314

**Comment by mjeffe98** [comment]
@sisskind not sure who to assign this to.

**Comment by bwitham** [comment]
services issue; recreated as ngageoint/hootenanny#575
