### ISSUE TITLE
Add the ability to hide all imagery from the Background menu except DG Imagery

### ISSUE THREAD

**Issue by treycaldwell** [ngageoint/hootenanny-ui#316]
We need a setting to hide Bing, Mapbox, Mapquest, etc. imagery from the menu.

**Comment by treycaldwell** [comment]
Confirmed with @damianblanck that we can leave the OSM layer which solves this without any code changes.  Simply go into data/imagery.json and remove every source except the OSM layer then bounce the server.

**Comment by sisskind** [comment]
@treycaldwell Let's coordinate to add instructions to documentation so we can close this out

**Comment by treycaldwell** [comment]
Spoke with @qwyjibojones about adding a customization or post-install section to the install doc.

**Comment by sisskind** [comment]
@qwyjibojones @treycaldwell have we added this to the post-install section of install doc?

**Comment by treycaldwell** [comment]
There is already a section, "Configure the Base Map List," at the end of  docs/install/HootenannyInstall.asciidoc.  This document is included in the main HootenannyInstall.asciidoc so we can close this issue if that existing section suffices (which, to me, it does).

**Comment by sisskind** [comment]
Agree.
