### ISSUE TITLE
Same review open in two different browsers at same time

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#320]
To replicate:

1. Ran DC POI Conflation in Chrome. 
2. Opened DC POI conflation in Firefox. 
3. Firefox opened to the same review as was open in Chome.  Also able to cycle thru the reviews to get to same review on both browsers.

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/VGI-team-repo/issues/57

**Comment by brianhatchl** [comment]
Remember that reviews now use "optimistic" locking (just like normal edits in OSM) so two users can load the same review, but the first one to save changes wins.  This is behaving as expected.

**Comment by sisskind** [comment]
@brianhatchl Thanks.  Will close.
