### ISSUE TITLE
Buttonology on the radial menu

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#321]
Options for editing pallet in review mode are no longer functioning because it has been changed to “Toggle conflated layer with inputs”. Users would like to be able rotate polygons. No keyboard shortcut workaround since “R” will resolve conflicts and not let you rotate in the conflict resolution mode.

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/VGI-team-repo/issues/56

**Comment by sisskind** [comment]
This is expected behavior.  See radial_menu.js:
```
 if(mergedLayer.length > 0){
            context.hoot().model.layers.layerSwap();
        }
```
What this is saying is that if there is a merged layer, instead of running the rotate or reverse operation, the toggle layers (or layerSwap) command is run.  If this is not the desired behavior, we can work to make it so!

**Comment by brianhatchl** [comment]
I would suggest we add a new option to the radial menu to swap layers instead of overriding the rotate feature button.
