### ISSUE TITLE
Update shortcuts list with overwrite and append

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#322]
Update the current shortcut list with the 'overwrite and append' command.

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/VGI-team-repo/issues/61

**Comment by mjeffe98** [comment]
@sisskind The help menu for the latest release already has the overwrite and append options listed in the shortcuts so I its just a matter of time for those to get installed onsite.
