### ISSUE TITLE
Clipped layer does not support space in output name

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#326]
When you clip using bounding box or map extent, there is the option to enter a name for the layer.  If the name has a space in between it causes the clip job to fail without reporting the reason why (example error below).  Since providing a space in the name is supported when renaming a layer it seems that we should support it with all functions that involve output name.

`2016-03-16 13:56:12,675 ERROR JobExecutionManager:225 - Job with ID: a0b658d9-6382-4bd1-882d-fe4015f0d732 failed: {"chainjobstatus":"a0b658d9-6382-4bd1-882d-fe4015f0d732","childrencount":"1","children":[{"id":"834e8d78-4d4b-4cdb-90c2-bd6c7864c342","detail":"Failed to execute.Error running crop-map:\ncrop-map takes three parameters.\nmake: *** [step1] Error 255\n","status":"failed"}]}`

**Comment by mjeffe98** [comment]
This also could be something that @sisskind might have some insight into since he worked on the implementation of clipping layers.

**Comment by sisskind** [comment]
This may also be causing issues on ngageoint/hootenanny#480.  Need to confirm space issue for ingesting datasets or creating through conflation.

**Comment by sisskind** [comment]
@mjeffe98 Ready for test.  Should not be able to use a space in dataset name when importing/clipping/conflating.

**Comment by sisskind** [comment]
https://github.com/ngageoint/hootenanny-ui/commit/d8e284dfe24fa30dabb4a034e34f33d4a5c3aacf#diff-23fb12fc4edecd0c5add7cbdc3dcca59

**Comment by mjeffe98** [comment]
Just adding a comment for a mental note.  Revisiting this to see if removing support for spaces altogether is the best approach or not.

**Comment by sisskind** [comment]
Appears that importing with spaces is also causing errors.

**Comment by sisskind** [comment]
This is a renderdb issue -- it appears it will not accept layer names with spaces.  @brianhatchl how do you want to proceed?

**Comment by sisskind** [comment]
@brianhatchl is it possible to change renderdb to use map id instead of name?

**Comment by sisskind** [comment]
@brianhatchl @mattjdnv changing hoot core code to replace map name with map id in issue-326 branch (will commit shortly).

**Comment by brianhatchl** [comment]
@sisskind replacing map name with id is the proper fix.  There should be tests that break at this point.

**Comment by sisskind** [comment]
@brianhatchl ok -- will let you know once it is ready for a review.  may miss some things along the way, but if i can import/clip/delete without warnings, I think I'll be on the right track?

**Comment by brianhatchl** [comment]
I'm still a bit uncertain because I thought there was a ticket for adding a export render db trigger to the clipping job, but maybe not.

This fix will settle this https://github.com/ngageoint/hootenanny-ui/issues/269

**Comment by brianhatchl** [comment]
See scripts/exportrenderdb.sh and then uses of RasterToTilesService job in ConflationResource and FileUploadResource.  Currently $INPUT=mapname and those resources would have to add the mapid to the available env vars for the exportrenderdb script.

**Comment by brianhatchl** [comment]
_createCommandObj in RasterToTilesService would need to accept the map id as a param.

As you can see, I just commandeered the old density map service infrastructure to run the exportrenderdb script instead of the gdal2tiles stuff.

**Comment by sisskind** [comment]
So that is the only change that would need to be made?  I also found map name being used instead of map id in a few places and made the change (see https://github.com/ngageoint/hootenanny/commit/467de2892c83ce8561eecd07d521abb525e248ab)

**Comment by sisskind** [comment]
Working on updating _createCommandObj now

**Comment by brianhatchl** [comment]
There is newish code in the core to delete render dbs within `hoot delete-map` so that's the first update in the commit you reference.  And the node-mapnik-server needs to know the render db naming convention as well.

**Comment by sisskind** [comment]
where in node-mapnik-server does that get defined?

**Comment by brianhatchl** [comment]
I think you already found it in your initial commit, I was describing what those commit changes affected in comment above.

**Comment by sisskind** [comment]
@brianhatchl think i changed too much -- hoot went boom

**Comment by sisskind** [comment]
@brianhatchl do you have bandwidth to review?  think I am missing something, since mapnik is running but not rendering.  Will create a pull request for easier viewing.

**Comment by sisskind** [comment]
https://github.com/ngageoint/hootenanny/pull/598

**Comment by brianhatchl** [comment]
The pull request above (replacing map name with map id in the render database nam) is ready to review.  But I don't think the clip tool in the UI generates a render db based on my testing.  This pull request should address https://github.com/ngageoint/hootenanny-ui/issues/269 however.
