### ISSUE TITLE
Remove flashing features

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#338]
The flashing features has created a GPU issue and can be distracting -- it may be creating more issues than helping solve.  Remove the flashing features, and depend on #264 to identify related reviews.

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/VGI-team-repo/issues/88

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/mapedit-id/commit/cfbb55935db767e3cca0318eea3daa6c372ec4dd

**Comment by sisskind** [comment]
@mjeffe98 ready for test

**Comment by mjeffe98** [comment]
@sisskind please define what is meant by remove flashing.  When I hover over either a blue/red highlighted feature it still flashes but I suppose this was referring to the unintended behavior of the feature continuing to flash?  Please clarify.  thanks

**Comment by sisskind** [comment]
Yes -- continuing to flash

**Comment by mjeffe98** [comment]
@sisskind so that's the intended behavior or unintended?

**Comment by sisskind** [comment]
It should not blink, but still highlight as red or blue on hover.

**Comment by mjeffe98** [comment]
blinking gone.  appears that I just needed to update Hoot.
