### ISSUE TITLE
Fix and run eslint tests

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#342]
Following iD v1.9.2, update and run eslint tests for iD editor/Hoot-UI.

**Comment by brianhatchl** [comment]
See branch here https://github.com/ngageoint/hootenanny-ui/pull/367

**Comment by brianhatchl** [comment]
eslint checks now passing in branch and configured to run as part of jenkins job http://selma:8765/job/hoot-ui-pull-request/
