### ISSUE TITLE
Fix and run mocha tests for UI

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#343]
1. Determine what mocha tests that currently exist in iD editor can be reused for Hoot-UI
2. Update existing mocha tests as needed
3. Create new mocha tests for functions not covered by existing/updated tests.

**Comment by brianhatchl** [comment]
Before fixing mocha tests and adding new ones, we've got some code cleanup to make eslint happy

eslint js/id
✖ 820 problems (683 errors, 137 warnings)

eslint js/hoot
✖ 4696 problems (4506 errors, 190 warnings)

**Comment by brianhatchl** [comment]
Ready to break out some global find&replace kung fu?

**Comment by brianhatchl** [comment]
See jenkins job output, http://selma:8765/job/hoot-ui-pull-request/
