### ISSUE TITLE
Add cucumber test for average conflation

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#344]

**Comment by jcp2236** [comment]
@brianhatchl This is the error I'm getting when running average conflation with the layers we use in cucumber tests
![screenshot from 2017-07-17 13 08 08](https://user-images.githubusercontent.com/17727812/28280611-5c1a57f0-6af2-11e7-9ad0-64898522284c.png)

**Comment by brianhatchl** [comment]
This option `ogr.esri.fcsubtype` was recently renamed in this PR, https://github.com/ngageoint/hootenanny/pull/1664/files#diff-321008ef2555f92f76799b5cf24ad765R1200, so you may just need to rebuild the code.

**Comment by brianhatchl** [comment]
Or just do `git submodule update` and redeploy the ui/services to tomcat.
