### ISSUE TITLE
Add conflation review style to node-mapnik-server

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#346]
When conflated layers with open reviews are added to the map, have the node-mapnik-server layer use a style that renders the features according to 1) reference layer, 2) secondary layer, 3) merged.  A fourth color designating the feature as marked for review may also be useful.

**Comment by curranMapper** [comment]
I am wondering if the above will also mitigate instances like this?  
![saveasgreenatfirst](https://cloud.githubusercontent.com/assets/15927720/14297136/6788f5a0-fb4b-11e5-92cd-75de9349c798.png)

**Comment by brianhatchl** [comment]
It might.  That behavior may be the node-mapnik-server layer drawing first in all green.  Then the editable vectors get loaded after some latency and they are colored by source/merged.

**Comment by brianhatchl** [comment]
probably put sql query in table param here:
https://github.com/ngageoint/hootenanny/blob/develop/node-mapnik-server/app.js#L82

```
select distinct(tags::hstore -> 'hoot:status') from line;
 ?column?  
-----------
 conflated
 unknown2
 unknown1
(3 rows)
```

**Comment by brianhatchl** [comment]
I created a branch for this work, with a necessary commit already, https://github.com/ngageoint/hootenanny/tree/ui-346

**Comment by sisskind** [comment]
@brianhatchl I don't think that mapnik is rendering a green layer at all...is that accurate?

**Comment by brianhatchl** [comment]
Yes, node-mapnik only renders a single color and it is pink by default (unless the user changes the selected color of the layer).

I believe @curranMapper is reporting another bug in that vector conflation review layers appear as all green until a map move event and then render in the proper ref source, sec source, merged color scheme.

**Comment by sisskind** [comment]
Tried with Haiti data and when you zoom out to trigger mapnik, only see pink/orange.

**Comment by brianhatchl** [comment]
You should see pink/orange for mapnik if you have two layers loaded in the map.

**Comment by sisskind** [comment]
I would think, though, with this issue that you should see green as well w/mapnik, right?

**Comment by brianhatchl** [comment]
Yes, that is the objective of this ticket.

**Comment by sisskind** [comment]
And we've come full circle.

**Comment by rmrice** [comment]
👋 Can someone please remove me as the assignee for this ticket? Thanks!

**Comment by brianhatchl** [comment]
OBE since we yanked node-mapnik-server
