### ISSUE TITLE
Users shouldn't be able to delete a review relation from the UI

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#35]
* click on a feature involved in a review
* scroll down to its relations
* select one with role "reviewee" and delete

The UI should prevent this from happening and pop up an error message to the user, as we want to control updates to review relations within the review code framework.

**Comment by sisskind** [comment]
@bwitham should reviewee text box be read-only too?

**Comment by bwitham** [comment]
I think so.  Anything involving that relation shouldn't be editable.

**Comment by sisskind** [comment]
Pushed to develop: https://github.com/ngageoint/hootenanny-ui/pull/81

@mjeffe98 Ready for testing.

**Comment by mjeffe98** [comment]
Now see a warning message and cannot delete reviewee field.
