### ISSUE TITLE
Brightness Control Does not Work

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#351]
Following the upstream merge, it appears that the brightness control is not working.

**Comment by sisskind** [comment]
@mjeffe98 Ready for test.  Should be able to adjust brightness levels as before.

**Comment by sisskind** [comment]
@mjeffe98 reopening - seems that it was not correctly mitigated.

**Comment by mjeffe98** [comment]
@sisskind the brightness controller does appear to be functioning correctly i.e. I have 4 brightness options from 100-25% and all behave properly.  Working off of 0.2.23_615_g933e088_dirty

**Comment by sisskind** [comment]
@mjeffe98 on Version: 0.2.23_622_gb0d8f4c_dirty and does not seem to be working.  Will see what changed and will fix/commit.  Also true for gap between tiles.

**Comment by mjeffe98** [comment]
@sisskind please send me a screencap of the gap between tiles.  I want to know what to look for sinece I'm on _624_ and the issue is not obvious to me

**Comment by sisskind** [comment]
@mjeffe98 Leaving gap on backlog since this appears to be a known issue that occurred prior to merge.

**Comment by sisskind** [comment]
Brightness issue has been resolved and is ready for test.

**Comment by mjeffe98** [comment]
@sisskind not sure exactly why but the gaps that appear for the same imagery basemap services were not visible in 0.2.23_615 has become strikingly noticeable in latest dev. Ignoring this issue, the background brightness controller works.

**Comment by mjeffe98** [comment]
@sisskind looking at Version: 0.2.23_643_g22548b4_dirty - Built By: vagrant and the brightness controller isn't responding.  Can you confirm on your version?

**Comment by mjeffe98** [comment]
disregard @sisskind I can see this working on  0.2.23_648_g963c3b4
