### ISSUE TITLE
Gap between basemap tiles

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#352]
There is a 1 pixel gap/border between basemap tiles.

**Comment by sisskind** [comment]
@brianhatchl This seems to be an artifact from the iD upstream merge to version 1.9.2.

**Comment by sisskind** [comment]
Determined where it was introduced: **js/id/renderer/tile_layer.js**
```
function imageTransform(d) {
            var _ts = tileSize * Math.pow(2, z - d[2]);
            var scale = tileSizeAtZoom(d, z);
            return 'translate(' +
                (Math.round((d[0] * _ts) - tileOrigin[0]) + pixelOffset[0]) + 'px,' +
                (Math.round((d[1] * _ts) - tileOrigin[1]) + pixelOffset[1]) + 'px)' +
                'scale(' + scale + ',' + scale + ')';
        }
```

Math.round was removed, and this is what created the artificial grid.

**Comment by sisskind** [comment]
@mjeffe98 Ready to test.  As long as you do not see gap between tiles, this can be considered complete.

**Comment by mjeffe98** [comment]
no gap visible
