### ISSUE TITLE
EGD plugin icons don't appear after upstream merge

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#353]
@sisskind Pretty sure @RDaviesDG has the solution for this

**Comment by sisskind** [comment]
@brianhatchl is there a way to get EGD plugin?  Don't think this is out of the box, is it?

**Comment by sisskind** [comment]
Icon now appears for DG Carousel, but unsure if this is the only missing one.  @brianhatchl will have you review pull request.

**Comment by sisskind** [comment]
![issue-353](https://cloud.githubusercontent.com/assets/6191659/14388311/8453c674-fd7b-11e5-9d87-45138c5c99d3.png)

**Comment by sisskind** [comment]
@mjeffe98 Ready for test.  Should be able to see icons displayed.
