### ISSUE TITLE
Warn user when deleting dataset if bookmark exists

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#356]
There have been issues when deleting a dataset if a current review bookmark exists (ngageoint/hootenanny#501).

Create a warning when a user is deleting a dataset that is affiliated with a current review bookmark.  Alert the user that if the dataset is deleted, bookmarks will be deleted as well.

**Comment by mjeffe98** [comment]
@sisskind the behavior described in the ticket works.  I'll close it but bear in mind that users will still fall into trouble if https://github.com/ngageoint/hootenanny-ui/issues/377 happens.
