### ISSUE TITLE
Fix EGD plugin layer controls expanded section position

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#357]
The EGD  plugin creates custom layer controls that have expanded sections that should be immediately next to their menu items.

- ~~Custom should be above DG Imagery header~~
- ~~Minimap should be below DG Collection expanded section ("Show ...")~~

![screenshot from 2016-04-08 10 14 47](https://cloud.githubusercontent.com/assets/2600932/14386433/c164c652-fd72-11e5-9dfc-53398fe15ffb.png)

**Comment by sisskind** [comment]
@mjeffe98 Ready for test.  Minimap should appear at bottom and custom/DG imagery should be flipped.
