### ISSUE TITLE
Attribute Select All function

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#365]
Create the ability to select all attributes at once while in review mode in order to copy/paste to other feature.

Original Text:
_This could be as simple as a blank box over top the column of values to indicate the 'select all' function.  Additionally, using traditional windows shortcuts like holding ctrl+shift and/or holding ctrl and selecting multiple at a time to select those fields to check the box would be great if possible._

**Comment by sisskind** [comment]
Select all check button implemented.  Will hold off on cntrl/shift for the time being to allow customer to test this functionality out.

**Comment by sisskind** [comment]
![issue-365](https://cloud.githubusercontent.com/assets/6191659/14859000/3a1fd01c-0c70-11e6-97cf-df048ed86f5d.gif)

**Comment by mjeffe98** [comment]
@sisskind right now I am testing the #343 hoot-ui branch in my local vagrant develop instance and this is not on the Vagrant Nightly develop build that @mattjdnv has set up.  So to avoid sabotaging my local #343 ui testing environment I'll hold off until this is done.

**Comment by mjeffe98** [comment]
tested in develop
