### ISSUE TITLE
Merge arrow appearing underneath merged feature layer

### ISSUE THREAD

**Issue by mikejeffe** [ngageoint/hootenanny-ui#372]
Pretty self explanatory but seeing the merge POI arrow under some of the features in the merge layer output.  Seems like the arrow should always be the top layer.

![image](https://cloud.githubusercontent.com/assets/7560096/14475679/0bf3bffa-00b8-11e6-9b65-5e085f0bf707.png)

**Comment by brianhatchl** [comment]
We can't solve this because if the arrow is on top, the mouse events will not be able to interact with the editable features

**Comment by sisskind** [comment]
https://github.com/openstreetmap/iD/issues/2934

**Comment by brianhatchl** [comment]
Unless we try to dynamically add/remove the svg "container" layer to the dom.  Right now we are dynamically adding/removing the svg path element when the merge button is hovered.

**Comment by sisskind** [comment]
So would you create a new HTML layer/blow it away on hover so that it appears above?

**Comment by brianhatchl** [comment]
A new svg element, but yes.

**Comment by mikejeffe** [comment]
@brianhatchl the arrow div is on top now but it looks like when I hit the ctrl key, the arrow doesn't switch directions dynamically.  I need hold the key first then hover over the merge button.  Can you confirm on your end?

**Comment by brianhatchl** [comment]
I did see that behavior once, but it is working for me now.  Try holding CTRL down longer.

**Comment by mikejeffe** [comment]
negatory.. doesn't appear to have a time dependency.

**Comment by mikejeffe** [comment]
ok working now. nevermind
