### ISSUE TITLE
Cannot zoom beyond current zoom level message when adding or editing features

### ISSUE THREAD

**Issue by mikejeffe** [ngageoint/hootenanny-ui#376]
If you add new features at say zoom level 16 there is the normal behavior but when you do this zoomed out (map=13.93), bad things seem to happen such as the pop-up error noted in the title and animation as well as the inability to use the mouse scroll wheel to zoom  in/out (hot keys seem to work though).  I need others to reproduce though so putting it as high priority for testing. @brianhatchl @sisskind please try to reproduce locally.

Because the size of the gif grew I am testing out hosting this on gdrive.
https://drive.google.com/file/d/0B3doASLmvtC7Z25YV3J2anNhajA/view?usp=sharing

**Comment by mjeffe98** [comment]
the other thing to note is that the digitizing cursor didn't fully trace my mouse cursor but that is kind of a known issue with some clipping functions.

**Comment by sisskind** [comment]
This only occurs when trying to zoom while in the process of editing.  Moving to medium priority and pushing to backlog for the time being.

**Comment by sisskind** [comment]
Note for when it is done -- appears that the minzoom value may be set incorrectly when entering edit mode.

**Comment by kweint** [comment]
@sisskind So interesting development regarding this ticket:
No issues adding or editing new elements regardless of zoom (no error messages either) So in that regard, the issue in resolved.
However, reference and secondary layer data disappears beyond map = 16.43 zoom. Thoughts?
