### ISSUE TITLE
Cannot select tags from selected feature for copy/paste

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#384]
When selecting a feature to copy individual tag(s) and/or tag values from, it appears that you can no longer click the box next to each tag you wish to append/overwrite.  I tried in release and my develop instance and was unsuccessful i.e. no check box appears when you click.

**Comment by mjeffe98** [comment]
I'm placing this at critical because it's a feature that is frequently used.  

@sisskind @brianhatchl FYI

**Comment by brianhatchl** [comment]
Fix pushed to release branch.  I've not updated selma.

**Comment by mjeffe98** [comment]
tested both append and overwrite.. works as expected.
