### ISSUE TITLE
Map panning warning while editing any value in the displayed fields in attribute panel

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#385]
When editing a field value exposed in the attribute panel under "all fields", a pop-up message will appear:"Please wait while panning to next review item".  When editing the same field under the all tags section this message does not appear.  In some cases when editing the field value the message will result in the feature getting unselected.  Also when typing letters that are also hotkeys like 'h' or 'b', the field editing will get disrupted.  It seems like we should disable any map behavior when editing field values the same way that this is done when editing tag values.

![map panning warning](https://cloud.githubusercontent.com/assets/7560096/14724915/e08750da-07cd-11e6-9ee5-d5f7932eba9d.gif)

To recreate, select a feature and begin typing in the "Name" field under the All Fields view as shown in animation.  For comparison, type the same value in the "name" tag in the all tags view to see that no map action is triggered.

**Comment by brianhatchl** [comment]
fix pushed to both release and develop, selma has not been updated.
