### ISSUE TITLE
Update the UI to allow for conflating MapEdit sourced datasets with hoot datasets (holy grail)

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#386]
https://github.com/ngageoint/hootenanny/wiki/MapEdit-Enhanced-Conflation-Workflow--(aka-%22Holy-Grail%22)

need to call the conflation web service with the correct parameters when a MapEdit data layer is chosen as the reference layer

* MapEdit data should only be allowed as a reference layer
* The input type for the reference dataset should be "OSM_API_DB".  Service should take care of setting all other input parameters.
* If the single osm api db connection is invalid, the error returned should make it obvious to the user that the connection hasn't been configured properly, whether it was due to the connection being disabled (osmApiDbEnabled=false), or bad credentials.

**Comment by bwitham** [comment]
good progress on this today...can now conflate from the ui with a mapedit ref layer.  lots of cleanup and testing left to do before moving onto export.

**Comment by bwitham** [comment]
Hit a bit of a snag here...  The MapEdit conflated from the UI is obviously suffering from element ID corruption.  

I realize that in the command line test workflow I'm taking osm api id's into account when originally writing the corresponding hoot layer to conflate with.  In the ui workflow this isn't possible, since that layer will have previously been written.  So I need to add a reading analog to OsmApiDbAwareHootApiDbWriter: OsmApiDbAwareHootApiDbReader.

**Comment by bwitham** [comment]
Fixed id reading problem with hack that #781 should fix in the future.

**Comment by bwitham** [comment]
Can now conflated dc streets data where one of the layers is source from MapEdit from the ui.  Probably corner cases left to fix, but moving onto MapEdit export in the ui for now.

**Comment by bwitham** [comment]
Will have this reviewed as part of #407.

**Comment by mjeffe98** [comment]
closed this based on my ability to complete the workflow of conflating an osm api db datasource with a hoot layer and exporting the changeset to the same osm api db.
