### ISSUE TITLE
Address eslint issues identified during regression testing

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#387]
Parent ticket for eslint testing issues
@sisskind @brianhatchl

**Comment by brianhatchl** [comment]
I've addressed the existing issues, if you want to regression test a bit deeper on the 343 branch.

**Comment by mjeffe98** [comment]
Not finding anything obvious.  We might be ok once @sisskind fixes https://github.com/ngageoint/hootenanny-ui/issues/399 to merge
