### ISSUE TITLE
Hoot core not reporting a version

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#389]
Only seeing Hootenanny Core - Version: WARN - Built By: 135 when clicking on about page.

**Comment by brianhatchl** [comment]
I think this a bug in the develop branch as well.

**Comment by brianhatchl** [comment]
This error is caused by a hadoop lib warning in the new vagrant environment:
>14:27:08.974 WARN  ...rc/main/cpp/hoot/core/Hoot.cpp( 135) Cannot load library HootHadoop: (libhdfs.so.0: cannot open shared object file: No such file or directory)
Hootenanny 0.2.24_212_gceaf16a Built By: vagrant
The warning is written to stdout which is what hoot-services parses to get the version.

**Comment by brianhatchl** [comment]
This could be fixed with smarter parsing in hoot-services AboutResource.java.

**Comment by bwitham** [comment]
Covered in #657
