### ISSUE TITLE
TypeError when merging POIs

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#390]
When trying to merge two POIs from input sources such as dcpoi/mapcruzin, I seem to be hitting the same error during the POI merge

`TypeError: Cannot read property of 'obj' undefined`

**Comment by brianhatchl** [comment]
Cannot reproduce on latest #343 branch.

**Comment by brianhatchl** [comment]
Doh!  Was on develop branch when testing this.
