### ISSUE TITLE
Clicking on Export dataset after resolving all reviews is not working

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#392]
When I complete a review session or click on resolve all remaining, and then click Export, nothing happens.  Just left with the merged dataset shown in the layers view.  

```
Export.js:67 Uncaught TypeError: Cannot read property 'append' of undefined
   exp.activate @ Export.js:67
   (anonymous function) @ tools.js:350
   (anonymous function) @ rest.js:771
   (anonymous function) @ d3.min.js:1
   t @ d3.min.js:1
   u @ d3.min.js:1

```

**Comment by mjeffe98** [comment]
Also the application appears to be a broken state after.  You can't delete the dataset or click on anything, just F5 to refresh.

**Comment by brianhatchl** [comment]
Cannot reproduce on latest #343 branch.

**Comment by brianhatchl** [comment]
Doh!  Was on develop branch when testing this.
