### ISSUE TITLE
Cannot upload files for Translation assistant

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#395]
Getting the following error when trying to upload files to create a new translation in the Translation Assistant:

```
Retrieving unique attributes failed. SyntaxError: Unexpected token : in JSON at position 2 Files can be one or more shapefiles, consisting of .shp, .shx, and .dbf components at a minimum. Or a zip file containing one or more shapefiles or a folder that is a file geodatabase. Folders can contain one or more shapefiles or be a file geodatabase.
```

Dev Console:
```
SyntaxError: Unexpected token : in JSON at position 2(…)
error on line 168: translation_assistant.js
```

**Comment by mjeffe98** [comment]
Seems to also occur with .gdb folders

**Comment by brianhatchl** [comment]
Wasn't able to reproduce with the data I tried.  What dataset was used?

**Comment by mjeffe98** [comment]
any .zip or shp (standard shapefile files).  If you can't reproduce then we can test it again when its merged into develop.  @sisskind can you check to see if you can upload a file into the Translation Assistant from the #343 branch?

**Comment by mjeffe98** [comment]
I checked on develop (Hootenanny iD Editor - Version: 0.2.24_219_g634c811_dirty - Built By: vagrant) and same issue so I am not entirely sure what is going with this particular issue.

**Comment by brianhatchl** [comment]
check tomcat log, it could be permissions related if you need to uncomment the group ownership option in Vagrantfile.

**Comment by mjeffe98** [comment]
not getting a server log for this in catalina.out,  Vagrantfile is uncommented for tomcat6 group ownership.

**Comment by brianhatchl** [comment]
seems data related that it's having trouble parsing the json response.  Can you get the attribute json from the network tab in dev console?

**Comment by brianhatchl** [comment]
another issue caused by https://github.com/ngageoint/hootenanny/issues/611

**Comment by mjeffe98** [comment]
once I added the HADOOP_HOME entry in /etc/default/tomcat6 this issue disappeared.
