### ISSUE TITLE
The brightness background basemap palette is reversed

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#397]
It appears that the ordering of the brightness controller is reversed from OSM's iD editor.  I don't recall if this was done intentionally but after Rob Walton pointed this out to me, it now seems counter intuitive. From a user/training perspective, the 100% brightness icon should be the one closest to white as OSM does it rather than the 100% black one that we show.  The palette just needs to be reverse.

OSM's iD editor:
![image](https://cloud.githubusercontent.com/assets/7560096/14827796/dfcd284e-0b98-11e6-9bdc-711c530e7e40.png)

Hootenanny iD editor:
![image](https://cloud.githubusercontent.com/assets/7560096/14827888/5cff3db6-0b99-11e6-93dc-b0682b3f49b3.png)

**Comment by sisskind** [comment]
@mjeffe98 Please double check develop branch, as I believe this has been fixed.
