### ISSUE TITLE
Measure tool no longer allows changing zoom level when capturing new measurement

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#399]
appears that we lost https://github.com/ngageoint/hootenanny-ui/issues/163 with the eslint changes.

**Comment by mjeffe98** [comment]
appears that we lost https://github.com/ngageoint/hootenanny-ui/issues/163 with the eslint changes.

**Comment by brianhatchl** [comment]
This feature seems to have some issues in develop too.  The measure drawing persists, but the map gets in a weird state and doesn't load tiles.  This error is present in the dev console:
`map.js:299 Uncaught TypeError: Cannot read property 'trim' of null`

**Comment by sisskind** [comment]
Will look into now

**Comment by sisskind** [comment]
Can replicate only with measure area, not measure line on develop.

**Comment by brianhatchl** [comment]
Yep, I was testing with area.

**Comment by sisskind** [comment]
Think I have a fix -- stand by.

**Comment by sisskind** [comment]
Little more involved then I thought -- will revisit and fix in the morning.

**Comment by sisskind** [comment]
Just merged into 343 branch with update.

**Comment by brianhatchl** [comment]
Great.  Shall we merge this into develop?  @mjeffe98 mentioned he didn't find any more glaring bugs.  And I hesitate to keep merging pull requests with new features until these eslint changes make it back into develop.

**Comment by brianhatchl** [comment]
And by this I mean #367

**Comment by sisskind** [comment]
I think we are good to go at this point and continue to work in develop as things bubble up.

**Comment by brianhatchl** [comment]
Heh, found a bug.  When zooming after creating an error measurement, the last point in the poly is removed.

**Comment by sisskind** [comment]
Right.  Meant to do that ;)

Stand by...

**Comment by sisskind** [comment]
Should be fixed now.
