### ISSUE TITLE
Add geojson of conflation review features to map-in-map

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#4]
When the map-in-map is displayed during conflation review, show dots representing review features.

**Comment by jchoi1267** [comment]
Committed service rest end point

**Comment by jchoi1267** [comment]
Looks like need additional fix to match geojson

**Comment by jchoi1267** [comment]
Now generating following 
{
    "type": "FeatureCollection",
    "info":
    [
        {
            "type": "Feature",
            "properties":
            {
                "class": "open"
            },
            "geometry":
            {
                "type": "Point",
                "coordinates":
                [
                    -104.907037158172,
                    38.8571566428667
                ]
            }
        },
        {
            "type": "Feature",
            "properties":
            {
                "class": "open"
            },
            "geometry":
            {
                "type": "Point",
                "coordinates":
                [
                    -104.719645881956,
                    38.8745941427829
                ]
            }
        },

**Comment by jchoi1267** [comment]
fixed geojson and added locked class

**Comment by jchoi1267** [comment]
Added bounding box
http://localhost:8080/hoot-services/job/review/getallreviewableitems?mapId=3&minx=-104.919&maxx=-104.7196&miny=38.859&maxy=38.8746

**Comment by brianhatchl** [comment]
@sisskind Can you review and merge this?
https://github.com/ngageoint/hootenanny-ui/compare/develop...mapinmap

**Comment by sisskind** [comment]
@brianhatchl will do

**Comment by brianhatchl** [comment]
Sorry, had one more local change I just pushed.

**Comment by sisskind** [comment]
@brianhatchl is it mapinmap branch for hoot-ui and hoot?

**Comment by brianhatchl** [comment]
I asked @bwitham to review and merge the hoot mapinmap branch containing services code.  You can just review and merge the hoot-ui portion.

**Comment by sisskind** [comment]
@brianhatchl sounds good

**Comment by sisskind** [comment]
Merged.  @mjeffe98 -- ready for testing.

**Comment by mjeffe98** [comment]
I see the poi dots in the overview map.  Looks like the red dot is fairly obvious but the blue features don't necessarily show up.  Also there are green dots that I assume refer to the mreged features?  I'll close once you confirm that this is by design.

**Comment by mjeffe98** [comment]
Closing after completing testing.

**Comment by brianhatchl** [comment]
The key for review features in map-in-map is:
Yellow = Open
Green = Resolved
Red = Locked
