### ISSUE TITLE
UI writes duplicate relation review members - 5496 branch

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#40]
* conflate all data types
* merge first review (you'll get a different one, depending on the randomness, but the behavior should occur regardless)
* resolve

The database will contain a relation with duplicate members.  It should not.

**Comment by bwitham** [comment]
@jchoi1267 I had this fixed in the 28 branch, but after I got the latest 5496 commit today, it was broken again.  When you merge 28 for me, look at my attempt at a fix, which isn't working.

**Comment by jchoi1267** [comment]
This bug was caused by change in base line assumption of 2 deletes and 1 add to 1delete to 1 modify during POI merge. Code had to be realigned with new logic

**Comment by bwitham** [comment]
looks good
