### ISSUE TITLE
Bug when right-clicking to export data 

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#402]
@curranMapper commented on [Mon Apr 18 2016](https://github.com/ngageoint/hootenanny/issues/619)

When right-clicking to export data, options are cancelled by another pop-up, please see graphic

![righclick_exportdata](https://cloud.githubusercontent.com/assets/15927720/14612124/a94dcb74-0563-11e6-880c-d89a609f48bf.png)

**Comment by mjeffe98** [comment]
@curranMapper if a user happens to right-click twice in a row that will happen but I haven't seen it occur with just the single right-click.

**Comment by curranMapper** [comment]
That might be unique to SBU network....will confirm

**Comment by curranMapper** [comment]
User pointed this out to me today.  This occurs when user apply's a single right click with Firefox on SBU.  Hitting 'esc' closes that top box so user can see the export options but not intuitive, anything that can be done to fix?

**Comment by mjeffe98** [comment]
@curranMapper I can't confirm the SBU component to this issue but I've been testing from firefox and I only get that condition when right-clicking twice in FF.  Does this occur outside of this env?

**Comment by curranMapper** [comment]
@mjeffe98 Nope

**Comment by sisskind** [comment]
@curranMapper can you try to confirm again?  Otherwise will be OBE.
