### ISSUE TITLE
Update the UI to allow for exporting conflated data to a MapEdit database (holy grail)

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#407]
https://github.com/ngageoint/hootenanny/wiki/MapEdit-Enhanced-Conflation-Workflow--(aka-%22Holy-Grail%22)

* need to wire the UI correctly for exporting a conflated dataset to MapEdit; export type should be: osm_api_db
* the export option should not be available unless the osm api db has been enabled in services ("conflation/osmapidb/enabled")
* the export option should verify that the layer being exported has the "osm_api_db_export_time" tag so that we know its a valid layer to export into mapedit
* export should be available both immediately after the conflation and from the datasets tab
* show the changeset stats text after the operation completes (after conflation only??)
* An exception can be thrown by this operation if conflicts occur in the MapEdit database with the changeset being exported, so code should be able to handle it (see holy grail wiki page).
* If the single osm api db connection is invalid, the error returned should make it obvious to the user that the connection hasn't been configured properly.
* I think we need to force all reviews to be resolved (if we don't already) since review relations won't make any sense in an osm api db.

**Comment by bwitham** [comment]
Work for this is being done on the #386 branch.

**Comment by bwitham** [comment]
TODO:

* make export work from datasets tab
* make export work from post conflation ui
* disable translations for export dialogs

**Comment by bwitham** [comment]
Have the conflation working but have been unable to access the export button so far...working on that now.

Also having trouble getting the text of the alert popups.

**Comment by mjeffe98** [comment]
closed this based on my ability to complete the workflow of conflating an osm api db datasource with a hoot layer and exporting the changeset to the same osm api db.
