### ISSUE TITLE
Add the element cache options to advanced UI settings

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#409]
element.cache.size.node
element.cache.size.way
element.cache.size.node

**Comment by sisskind** [comment]
@bwitham Do these fit into a existing category currently (i.e. Road Options, General Conflation)?  Also, are the default values the same for all conflation types (Reference, Average, Horizontal)?  Thanks!

**Comment by bwitham** [comment]
I think you could probably put it under "General Conflation".  They would have the same default values for every conflation type.  

Its the in memory cache size used when streaming from osm to an ogr format, which could occur either during export or conflation.  The idea is to start with a a reasonable default setting which doesn't allow one user to suck up all the memory in a system for a large conflation job (maybe one they kicked off not realizing how big it was), but then allow for increasing the sizes in cases where someone has a legitimately big conflation job and is needs to do a one time cache size increase to accommodate the job.

**Comment by sisskind** [comment]
@bwitham default size in ascii doc is 2000000.  Will go with that unless you had diff. value in mind.

**Comment by bwitham** [comment]
Yeah, I guess use those.  They are the biggest values we've encountered so far during use... all from populating the render db I think.  If they get raised any higher, it almost doesn't even make sense to have limits anymore.

element.cache.size.node: 2 million
element.cache.size.way: 200k
element.cache.size.relation: 200k

**Comment by sisskind** [comment]
![image](https://cloud.githubusercontent.com/assets/6191659/16162899/4732a160-34a4-11e6-8d78-4bdbd7e0a992.png)
