### ISSUE TITLE
Undo merge does not change color back to source layer

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#416]
When in review mode, if you undo a merge operation, the color of the point does not return back to the source layer.

**Comment by brianhatchl** [comment]
Could be a complementary bug to this https://github.com/ngageoint/hootenanny/issues/658.

**Comment by mjeffe98** [comment]
tested merge, then undo.  Looks like when merging 1 orange (layer1) with 1 pink (layer2), it takes two undo's to revert back to the original colors.  That seems expected since a merge is actually > 1 update to the data.

**Comment by brianhatchl** [comment]
@sisskind had the same question and yes, a POI merge is an update tag event and a delete event, so two steps.
