### ISSUE TITLE
Translation Assistant scroll with arrows shows odd results

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#418]
Translation assistant shows odd values when scrolling through potential mapping values with arrow keys.  Could be related to values in the overflowTags array.

**Comment by sisskind** [comment]
https://github.com/ngageoint/hootenanny-ui/blob/f705d786540079f037cfd2c098f905639f50bf44/js/hoot/control/translation_assistant.js#L634

**Comment by brianhatchl** [comment]
Can you categorize odd values?  Or add a screenshot?

**Comment by brianhatchl** [comment]
I think I've found what you mean,
![screenshot from 2016-05-17 11 50 23](https://cloud.githubusercontent.com/assets/2600932/15329145/9f19dd5e-1c25-11e6-865a-713ce4118045.png)

**Comment by sisskind** [comment]
Bingo

**Comment by mjeffe98** [comment]
not seeing <span class...  as shown in https://cloud.githubusercontent.com/assets/2600932/15329145/9f19dd5e-1c25-11e6-865a-713ce4118045.png
