### ISSUE TITLE
Error when loading layer that exceeds max node count for a map query

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#419]
When I try to load a layer like Congo_MGCP_Roads_Bridges.osm from https://github.com/DigitalGlobe/dgis-devops/issues/85 the UI just spins in Loading... mode for an indefinite period of time.  This occurs at zoom level 10-17 generally for this data (map=10.17/22.5090/2.4938).  The error in the Error log reports that the max number of nodes exceeds the limit of 50K but we didn't used to have this issue when this limit was at 10K (that's what @brianhatchl recalls the previous max node count limit being).  Although you can stop the loading behavior as soon as you zoom far enough, this is a pretty serious issue and one worth taking a look at to see what has changed because when the UI is stuck in this loading state you cannot conflate until you zoom farther in.  The best data to reproducing seem to be the Congo_MGCP_Roads_Bridges.osm dataset or in Haiti, PortAuPrinceOsmRef1.osm.  

2016-05-06 20:40:48,063 ERROR MapResource:48 - The maximum number of nodes that may be returned in a map query is 50000.  This query returned 105924 nodes.  Please execute a query which returns fewer nodes.

**Comment by mjeffe98** [comment]
@bwitham @dmylov @brianhatchl not sure who best to look at this issue.

**Comment by mjeffe98** [comment]
Another side effect is that when you conflate, you cannot go into review mode automatically.  The client just spins in Conflating... mode.  When I conflated the congo data I waited quite a bit, then looked at the UI error log and saw that the conflation job had finished but it error'd out even though nothing had changed in the map window (was still trying to process the conflation).  I zoomed to level 13 and the first review loaded.  

```
"5/6/2016, 1:57:45 PM: SUCCESS: but the job has completed with warnings. For detailed log goto Manage->Log\nError\n    at Function.Hoot.model.REST.WarningHandler (http://localhost:8888/hootenanny-id/js/hoot/model/rest.js:1109:129)\n    at http://localhost:8888/hootenanny-id/js/hoot/model/rest.js:406:39\n    at Object.<anonymous> (http://localhost:8888/hootenanny-id/js/lib/d3.min.js:1:10988)\n    at Object.t (http://localhost:8888/hootenanny-id/js/lib/d3.min.js:1:1368)\n    at XMLHttpRequest.u (http://localhost:8888/hootenanny-id/js/lib/d3.min.js:1:9850)"
5/6/2016, 1:57:45 PM: SUCCESS: but the job has completed with warnings. For detailed log goto Manage->Log
Error
    at Function.Hoot.model.REST.WarningHandler (http://localhost:8888/hootenanny-id/js/hoot/model/rest.js:1109:129)
    at http://localhost:8888/hootenanny-id/js/hoot/model/rest.js:406:39
    at Object.<anonymous> (http://localhost:8888/hootenanny-id/js/lib/d3.min.js:1:10988)
    at Object.t (http://localhost:8888/hootenanny-id/js/lib/d3.min.js:1:1368)
    at XMLHttpRequest.u (http://localhost:8888/hootenanny-id/js/lib/d3.min.js:1:9850)
```

**Comment by dmylov** [comment]
@mjeffe98 

Are you seeing anything being reported on the Tomcat side, in its log files?

**Comment by mjeffe98** [comment]
@dmylov just the same one reported from the Error log:

2016-05-06 21:46:21,556 ERROR MapResource:48 - The maximum number of nodes that may be returned in a map query is 50000.  This query returned 117992 nodes.  Please execute a query which returns fewer nodes.

**Comment by bwitham** [comment]
The 50k limit is the correct API behavior, assuming the count query is still working (think there's a test for it).  public openstreetmap uses the same limit, so we shouldn't change it on our end.  I thought that the UI does a node count query at each zoom and if the count is higher than that limit, it doesn't try to display the nodes.... could that part no longer be working correctly.

**Comment by mjeffe98** [comment]
@brianhatchl perhaps this is something you can investigate. The UI should be able to correctly handle the query when it exceeds the max node count.

**Comment by brianhatchl** [comment]
This commit has already been merged into develop, so should be ready to test under 5/11 milestone.
