### ISSUE TITLE
Filter by Type not providing the option to go from TDS back to OSM

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#42]
If you load an OSM layer you can pull down the Filter by Type to see the tags in TDS 6x/4x.  Clicking on the feature displays the TDS tags for that feature but you cannot go back to OSM.  Should fix the drop down menu to support displaying the tags back in OSM.

**Comment by jchoi1267** [comment]
This was caused by not having OSM as one of capabilities returned from service. Since OSM is default for UI I am adding as default in UI code now.
