### ISSUE TITLE
Reviews appear to be taking longer to load

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#420]
Could be me but it seems as if the reviews are taking longer to load when stepping through.  This could be a side-effect of #419 or something entirely different all together.  By this I am referring to the load time that it takes from moving to the next review to releasing it for the user to take action.

**Comment by bwitham** [comment]
This is where having the load tests running would be useful.

**Comment by mjeffe98** [comment]
Going to mark this as cannot reproduce for now.
