### ISSUE TITLE
End of review error messages

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#423]
Reaching the end of PaP conflation reviews. When going to delete a red feature, a neverending stream of red error notifications occurs eventually culminating the the complete and total meltdown of Chrome or Firefox and the world burns.

Error stream consists of:
TypeError: Cannot read property of id undefined.

There are no members in the review relation.

![image](https://cloud.githubusercontent.com/assets/6191659/15122270/464e82ae-15ec-11e6-9de5-30709a689a55.png)

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/VGI-team-repo/issues/110

**Comment by sisskind** [comment]
It appears that the code is getting stuck in a loop with LoadMissing, etc.  This does not occur when the features in the review are points/nodes.

**Comment by sisskind** [comment]
This will occur no matter how many reviews are left.  Causation appears to be when all review features in relation are deleted.  This is ready for review in pull request.

**Comment by sisskind** [comment]
Seems that this could be due to node relations not being deleted when they are empty, which is what occurs with way relations.  This should be fixed and then the code should be updated to work with empty relations with deleted features contained in history (as it currently stands, but needs to be updated when user resolves a review).

**Comment by mjeffe98** [comment]
@sisskind there are 429 + reviews when you conflate the full PaP dataset but I've verified that you can delete all of the red/blue highlighted road segments in a review (including those that are part of a relation), click resolve and move onto next review.  I'm not entirely 100% certain what the conditions to fully recreate this are but it does appear that the previous errors associated with loading missing members of a relation have been resolved.
