### ISSUE TITLE
Return of Batman Mode

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#424]
I have occasionally been getting this issue when adding the a merged layer in Hoot and the result is black space with the exception of red and blue boxes containing the attributes.The coordinates say NAN_NAN_NAN_NA. I refresh Hoot and screen zooms out to the globe. Has this happened to other users and is there a fix?

![image](https://cloud.githubusercontent.com/assets/6191659/15122401/f8617bcc-15ec-11e6-8264-0fe9face8d03.png)

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/VGI-team-repo/issues/115

**Comment by sisskind** [comment]
Adding checks for map extent, center, zoom to ensure coordinates are accurate.  This should mitigate issue, and will mark closed at that point.  If it continues, new ticket will be opened with details and how to reproduce, if possible.

**Comment by sisskind** [comment]
Using San Diego data, should get error message instead of going to NaN NaN

**Comment by mjeffe98** [comment]
@sisskind I could only reproduce this error on selma:8093 and no where else with the same San Diego rivers data.  On selma got the NaN error below but on my local vm and on the new AWS I did not get the NaN so it may be difficult for me to reproduce.  

d3.min.js:1 Error: <path> attribute d: Expected number, "M0.5,0.5v8hNaNv-8".u @ d3.min.js:1
d3.min.js:1 Error: <text> attribute x: Expected length, "NaN".u @ d3.min.js:1

**Comment by sisskind** [comment]
I think we should mark OBE.
