### ISSUE TITLE
"No Members in Review Relation" following conflation job

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#425]
After conflation job is run, "No Members in Review Relation" error appears.

"There are no members in review relation"

Work around: Bookmark review and reload.

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/VGI-team-repo/issues/103

**Comment by brianhatchl** [comment]
Is this because the bookmarked review was resolved, and resolving a review removes the features from the review relation?

**Comment by sisskind** [comment]
@brianhatchl will double check that, but I believe when it was shown to me was the first bookmark review prior to any work being done on the layer.  For example, ran conflation job, created bookmark, then tried going to bookmark.

**Comment by sisskind** [comment]
Awaiting further guidance as this cannot be replicated.

**Comment by sisskind** [comment]
Believe this was fixed with #423, but will leave open for verification.

**Comment by sisskind** [comment]
Possible that "Load Missing" is not being checked initially, causing Hoot to believe that there are no members in the review relation.

**Comment by sisskind** [comment]
Check r411 or r409

**Comment by sisskind** [comment]
Marking OBE for now as this is not a detrimental bug, just a nuisance.
