### ISSUE TITLE
Area measurement is invalid

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#43]
When you click on Tools | Measure Area and digitize a building you will see that the area calculation will actually increase when you decrease the size of the polygon Note that the feature shown is the Woodley Park Marriot (Delano) hotel in DC.
![calculate_area](https://cloud.githubusercontent.com/assets/7560096/11406705/96787318-9363-11e5-97a3-5b8e6bb7e3c7.gif)

**Comment by sisskind** [comment]
@mjeffe98 Ready for test. https://github.com/ngageoint/hootenanny-ui/pull/69
