### ISSUE TITLE
Remove Hootenanny Default from non-default Hootenanny Translation Schemas listed

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#44]
Minor quip but we should probably remove the words (Hootenanny Default) from any non-default translation.  They appear on all listed (MGCP, TDS, etc.) except for custom translations.  The word default should only apply to any translation that is actually used as the default value rather than on all of the possible translation schemas.

**Comment by sisskind** [comment]
@mjeffe98 Ready for Test
