### ISSUE TITLE
Not getting 'delete bookmark' warning in UI in bulk delete

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#441]
If multiple datasets are deleted, there is no warning that one of the datasets has an affiliated bookmark.  This will cause the error where Map Sizes cannot be found.

This may be solved by ticket to remove bookmarks on services end.

**Comment by sisskind** [comment]
Fixed from #356

**Comment by mjeffe98** [comment]
confirmed on release 0.2.25
