### ISSUE TITLE
Import should support zipped osm and gdb datasets (not just shapefiles)

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#449]

**Comment by treycaldwell** [comment]
When importing a Dataset there are two potential error conditions a user could encounter when attempting to upload an osm file that has been zipped (here, named sample.osm.zip).

1. User chooses (shp,zip) as Import Type, selects the file, and then encounters a UI error generated by ImportDataset.js indicating "Please select only single type of files. (i.e. can not mix zip with osm)"
2. User chooses (osm) as Import Type, selects file and clicks Import, and then encounters a server-side generated error (FileUploadResource.java) "Failed upload: Hootennany does not support zip files containing .osm data."

**Comment by brianhatchl** [comment]
If the hoot command (using ogr) does not accept a zipped osm or fgdb file, then I suggest the service do the work of unzipping.  See how the OgrAttributesResource handles things.

**Comment by treycaldwell** [comment]
Don't invoke the `makeetl` makefile from the command line without setting the appropriate environment variables or it will do a `rm -rf $HOOT_HOME`

**Comment by bwitham** [comment]
nasty

**Comment by bwitham** [comment]
I'd do all my debugging for this by using junit test drivers that invoke the java resource file which is actually calling that make script.  Less tedious imo.

**Comment by treycaldwell** [comment]
Yeah, I'm not going to dwell on the inner workings of the JobControllerBase and JobExecutioner and why we're calling makefiles.  I'm just going to get in there, get it working, and get out as @brianhatchl said.  However, we should have a discussion about alternatives to calling the core without using makefiles, parsing STDOUT, etc.

**Comment by bwitham** [comment]
There definitely may be ways to make it more that interface more straightforward I think.  All involve a lot of work.  The brick wall you'll always hit is that hoot core is largely not thread-safe.  Hoot lived its life completely on the command line a few years before it was service enabled, and at the time the services were created we realized the level of effort to make that code threadsafe was far beyond what we were willing to invest or were capable of investing given the much smaller team size at the time.  That decision was actually made a few years ago, so I can't imagine how much harder it would be to make all of it threadsafe now.  

I didn't work any on the services calling command side of things, but I'm guessing the makefiles were utilized as templates that allowed the java code invoking the commands to be less complex and take advantage of existing scripts used by the core tests.  As the makefiles are taken away, the complexity of the java command invoking code would go up, but you would be able to eliminate a layer of indirection, so maybe that would be a good thing (?).  But even with those changes I don't think you're going to be able to get rid of the message passing via stdout.  There's no other way for the core to communicate info/error statuses back to the services.

Another approach would be more utilization of the hoot nodejs interface.  At that point you'd be talking about making the java command side merely a shell around nodejs scripts...which may be even better.  But with that you're talking about not only major java but also major c++ changes to nodejs enable some things...and some of the thread safety concerns could still be there in certain cases...not sure.  I would always want to see any heavy lifting code (looping over tons of data) remain in C++ (preferrably) or Java, and never purely within JS for performance reasons.

**Comment by treycaldwell** [comment]
The UI currently allows selecting multiple files for upload, but the following error is received when attempting to upload two OSM files:  "Failed to execute.Error running convert: convert takes two parameters."  We will just support uploading a single zip file containing a single osm or a single gdb dataset.

**Comment by treycaldwell** [comment]
Since the controller code is now working (minus a test of zipped osm ingest which still needs to be finished), the UI task is to allow a "osm.zip" file to be chosen through the file chooser and to add "gdb.zip" to the "File (shp,zip)" Import Type text (already allows choosing a "gdb.zip" in the file chooser).

**Comment by treycaldwell** [comment]
Currently, when using Firefox the first Import Type option is "File (shp,zip,gdb.zip)".  In Chrome the option is "File (shp,zip)".  I commented out the browser check so the user is always presented with the former and this works just fine in Chrome.
