### ISSUE TITLE
WFS Export is not working

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#45]
When you select the WFS as your export type and submit, the WFS layer does not appear in the WFS Export tab.  Opening the dev console, it appears that the job is submitted but has failed.

ex: http://server/hoot-services/job/status/ex_5b30549caac24d86aa450094e9a9aa68".

Clicking on the URL exposes the WFS failure message:

{"lasttext":"","jobId":"ex_5b30549caac24d86aa450094e9a9aa68","statusDetail":"{\"chainjobstatus\":\"ex_5b30549caac24d86aa450094e9a9aa68\",\"childrencount\":\"2\",\"children\":[{\"id\":\"8350d98b-1a11-4583-90af-4313fe958760\",\"detail\":\"hoot.services.controllers.wfs.WfsManager.createWfsResource(java.lang.String)\",\"status\":\"failed\"}]}","status":"failed","percentcomplete":50}

**Comment by jchoi1267** [comment]
It has been fixed while code clean up

**Comment by mjeffe98** [comment]
Ok I will re-test on Monday.
