### ISSUE TITLE
Phantom Pallet

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#453]
Pallet goes invisible - not sure what's making it do it, both Hilary and I have seen it. You click a feature and it seems that nothing happens...except that the pallet is actually there and you can mouse over where the invisible buttons are and get the tool-tips and even click and use the pallet.

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/VGI-team-repo/issues/137

**Comment by sisskind** [comment]
1) Open up a dataset that has reviews
2) Go to a review that has a blue and a red feature (I have had it work with just a read feature but it wasn't reliable)
3) Click a feature so the pallet appears
4) Click and hold on another feature (I usually click a road) and then drag/pan the screen
5) Should now be experiencing a phantom pallet

**Comment by briandaviddavidson** [comment]
I'm unable to recreate this on my machine, however I will continue to try throughout today. If I'm not successful, I'll reassign it to @sisskind

**Comment by mikejeffe** [comment]
Also unable to reproduce this based on the steps provided.  At no point does a phantom pallet appear.

**Comment by curranMapper** [comment]
I am still experiencing the phantom pallet by following the 5 steps @sisskind wrote out above

**Comment by sisskind** [comment]
really? :(

**Comment by sisskind** [comment]
OBE // revisit in iD 2.x
