### ISSUE TITLE
Show review relations for one to many reviews triggers type error when traversing

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#458]
Using Latvia POI (geonames, osm) as an example where you get a lot of POI reviews with hotels, it seems that the Show Review Relations option is causing a disruption when traversing to the next review.  I've isolated a subset of POI data from Latvia to reproduce this issue.  

To reproduce:
1) Conflate OSM and Geonames as layer 1 and 2, respectively
2) During review, click on one of the POIs and show all reviews to display the 1 to many starburst.  (Keep this open as you proceed to next review).
3) Click merge/resolve for current review
4) Next review doesn't get loaded and a type error appears in dev console.
`Uncaught TypeError: Cannot read property 'type' of undefined`

[Latvia_Hotel_Pois.zip](https://github.com/ngageoint/hootenanny-ui/files/283090/Latvia_Hotel_Pois.zip)

**Comment by mjeffe98** [comment]
@sisskind take a look at this with the attached data and let me know if you don't get the error.  Basically what should happen is after resolving a review with show review relations displayed, you won't get the review table to load for subsequent reviews.

**Comment by sisskind** [comment]
Able to replicate - working on fix now.

**Comment by sisskind** [comment]
@mjeffe98 try now
