### ISSUE TITLE
OSM/TDS switcher is not translating the attribute key/values

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#473]
Previously when you select a feature like Residential Road with the Filter By Type = OSM and switch to TDSv61/40 and the attribute context menu would display the tag values using the TDS schema spec.  Now it appears that when you switch to TDS none of the attribute values reflect the "active" schema and the tag values are not updated.  Something seems to be jamming up the translation and preventing the fields from updating.  If you just stay in OSM, everything seems to work correctly.

**Comment by mjeffe98** [comment]
Perhaps @mattjdnv can also see what is happening on the back end with the translation switcher in the UI.

**Comment by mjeffe98** [comment]
Another oddity that could be related with the preset selector.  Notice that the previous schema presets remain when you switch to TDS.  If you try to select those, nothing happens, but if you select a valid present based on the schema they work.

![osm_tds preset issues](https://cloud.githubusercontent.com/assets/7560096/15787300/6350a830-2976-11e6-8874-55ee48e5a969.gif)

**Comment by brianhatchl** [comment]
The requests to the translation service are coming back with valid responses.  This is a UI-only bug.

**Comment by mjeffe98** [comment]
The fields and values now appear to be updating when you toggle b/w different schemas.
