### ISSUE TITLE
Expose pbf as available import/export format

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#475]
Expose pbf as a data type for import or export.  Should be an OGR-accepted format.

**Comment by treycaldwell** [comment]
@brianhatchl did I need to leave this open?

**Comment by brianhatchl** [comment]
Yeah, I think we want @kweint to validate these PRs after they are merged.

**Comment by curranMapper** [comment]
Downloaded .osm.pbf file from http://download.geofabrik.de/africa.html
Imported and viewed on map, looked good
exported a files from data management that was imported as geonames/osm and had no issues on export.

Think this is good to close!
