### ISSUE TITLE
Warning before closing Hootenanny

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#481]
On several occasions I've hit Ctrl-R or closed the browser without thinking. It would be nice to add a pop-up warning when trying to close the Hoot session if a review session dataset is loaded, "Are you sure?".

**Comment by brianhatchl** [comment]
https://github.com/ngageoint/hootenanny-ui/pull/513

**Comment by mikejeffe** [comment]
tested ctrl-r, closing tab, closing browser but as the description states this only get's instantiated if the user firsts invokes review mode.  There are no warnings if the user is just loading a normal layer and making edits but I believe that's the original intention of the ticket.

**Comment by sthorneloe** [comment]
@mikejeffe That sounds sufficient to me, thanks!

**Comment by sthorneloe** [comment]
@mikejeffe Is this in the nightly yet?
