### ISSUE TITLE
Alt+B shortcut has conflict on Firefox

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#483]
Alt+B is the shortcut in Hootenanny for swapping review layer with reference layers, but it is also the shortcut in Firefox to show the bookmarks bar. Either override in Firefox or change the shortcut.

**Comment by sisskind** [comment]
@treycaldwell It appears that the Alt+B shortcut is not working at all.  Can you confirm?

**Comment by sisskind** [comment]
Changed to Shift + T

**Comment by mikejeffe** [comment]
The only issue that might cause confusion is that when a feature is not selected (with review layer loaded), T toggles the Hide/Display Table
