### ISSUE TITLE
Review Bookmark Improvements (Medium) 

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#484]
* ~~"Missing en translation: review.sharereview.description" appears when you mouseover the button. (_This is occurring because the make file was not properly run._)~~
* ~~Ability to go back to bookmarks list when looking at current review. (Current workaround is to click on tab again)~~
* ~~Layers and creators option should only include those involved in bookmarks~~
* ~~Instead of drop down filters, change to side bar with checkboxes~~
* ~~Implement pagination or remove it~~

**Comment by sisskind** [comment]
Test along side UI ticket (ngageoint/hootenanny-ui#484). Should be able to filter bookmarks using checkboxes on side bar as opposed to drop downs. Both have been merged into develop.

**Comment by mikejeffe** [comment]
functioning properly but it seems like we've included more filters than necessary. I think it may end up cluttering the list since it's unlikely someone would filter by Map ID vs. Relation ID or Review ID, etc..

**Comment by mikejeffe** [comment]
Doesn't appear to be working on FF.  The Filter By Creator/Layers isn't functioning.

**Comment by sisskind** [comment]
Can confirm not working on FF.  Will fix as well as remove some filters per above comment.
