### ISSUE TITLE
User added tags/values not getting copied using ctrl-c/ctrl-v

### ISSUE THREAD

**Issue by mikejeffe** [ngageoint/hootenanny-ui#485]
In reference to https://github.com/DigitalGlobe/VGI-team-repo/issues/151, it appears that user added tags such as a description or note field are not getting copied when the user selects that feature and creates a copy.  I was able to use the append/overwrite, i.e. checkbox, mechanism to copy the note and description tags from an existing feature to another but this should work when creating a copy of any feature in iD.  

To reproduce, pick any feature and add a note or description then save.  Click ctrl-c and ctrl-v to create a copy of the feature then look at the attribution.  No note or description will appear.

**Comment by brianhatchl** [comment]
Is the point that copy is not working on unsaved attributes of feature?

**Comment by mjeffe98** [comment]
The point is that copy is not working on "saved" attributes of a feature.  I presume they are saved because I clicked save prior to the copy.

**Comment by brianhatchl** [comment]
This is the default behavior of iD.  I guess it is assumed that fields like description are unique to a feature and should not be conveyed to copies of it.  This exclusion list is in use to copy/pasting features, https://github.com/ngageoint/hootenanny-ui/blob/develop/js/id/behavior/paste.js#L4-L18.

We have disabled this list for paste attributes, except for hoot tags.  https://github.com/ngageoint/hootenanny-ui/blob/develop/js/id/behavior/paste_tags.js#L5-L27

If we'd like to disable this tag filtering on feature copy/paste we can do that.

**Comment by brianhatchl** [comment]
There is a PR that will disable the tag filtering.  We just need to decide if this is what we want to do.
