### ISSUE TITLE
Advanced Options CSS

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#486]
Enabled fields should not appear disabled (faded gray).

**Comment by sisskind** [comment]
@brianhatchl so it isn't just the advanced options placeholders that look "disabled", it is the entire app.  Take a look at any input when it loses focus - it has the same light gray text color.

**Comment by brianhatchl** [comment]
screenshot?

**Comment by sisskind** [comment]
![image](https://cloud.githubusercontent.com/assets/6191659/16153205/5cf8fb74-3473-11e6-84cb-69050b6d61f6.png)

See how input fields have same text color.

**Comment by sisskind** [comment]
Adjusting CSS so that disabled input field will have light gray background though.

**Comment by brianhatchl** [comment]
okay
