### ISSUE TITLE
Search not working when MGCP is active schema

### ISSUE THREAD

**Issue by mikejeffe** [ngageoint/hootenanny-ui#499]
Seems that I can't search for a feature type when the MGCP filter by type option has been selected as a result of https://github.com/ngageoint/hootenanny-ui/issues/487.  Other searches work for osm, tds but not for mgcp.  I tested this by searching for known feature types for each schema e.g. osm: soccer*, tds: ford, etc...

@brianhatchl @sisskind

**Comment by mikejeffe** [comment]
Doesn't look like the search is working with MGCP yet.  I created a feature, flipped the filter to MGCP and searched for bridge.  None of the search results had the name "bridge" in it.  Contrast this with OSM and TDS where search terms appear in result.

**Comment by brianhatchl** [comment]
MGCP presets are now there (they weren't at all before), the search fix is being tracked here https://github.com/ngageoint/hootenanny/issues/907

**Comment by mikejeffe** [comment]
thanks @brianhatchl.

**Comment by mikejeffe** [comment]
this ticket was originally opened because search wasn't working with MGCP selected so I don't think I can close it based on whether the presets are there.  I'll track this with ngageoint/hootenanny#907.  Once that work is done, we can probably close this ticket.

**Comment by mikejeffe** [comment]
closed after testing ngageoint/hootenanny#907
