### ISSUE TITLE
Error when loading a HGIS validation layer

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#500]
Run through the HGIS workflow to create a validation layer. When you add it to the map the following error occurs:

Uncaught TypeError: validation.loadFeature is not a function

**Comment by mjeffe98** [comment]
I'm getting the error message below on certain POIs in my test layer (
[Samoa_MGCP_Validation.zip](https://github.com/ngageoint/hootenanny-ui/files/319166/Samoa_MGCP_Validation.zip)
) making this had to confirm as fully functional.

![image](https://cloud.githubusercontent.com/assets/7560096/16130337/7de88248-33bd-11e6-9466-0abc80ca9be4.png)

**Comment by mjeffe98** [comment]
It seems that the same POIs are getting loaded twice which doesn't look right as I would expect only tagging a feature once.  Also if you click the Save button it tries to commit a deleted relation.

**Comment by brianhatchl** [comment]
There is another bug https://github.com/ngageoint/hootenanny/issues/846 that might be causing this.  This ticket was just to remove the error that occurred when loading a validation layer and going into validation mode.

**Comment by mjeffe98** [comment]
Ah ok.  I won't conflate the two issues then.
