### ISSUE TITLE
OSM API DB Ingest/Display Design

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#502]
Based on great work by @bwitham, need to determine best way to display OSM API DB reference.  Currently it is listed as a dataset, but this may be confusing for users.  Two possibilities are:

* Create separate tab in Settings page for user to create connection(s) to database(s).  This could either just be a place to configure the one and only connection, or a place to add multiple connections.  Either scenario could allow user to add these to map (albeit with no data currently) or run conflation job from that tab, by selected a dataset.  UI would then jump to map view for review resolution.
* Create data type of OSM API DB and allow user to ingest as they would an OSM dataset or a SHP.  User could then use manage tab feature to move (rename, add to folder) or delete (connection only).

Personally, I am more inclined to the first option, but open to discussion and thoughts of other ideas.

**Comment by bwitham** [comment]
I'd discourage the second option, since it changes the workflow over the entire codebase...but it is in theory possible with some significant refactoring (haven't tried that workflow).  Current workflow delays the reading of osm api data into hoot until conflation time (so there's really no need for a separate ingest step).  This reduces the overall time osm api data sits in hoot and reduces the chances of external conflcts when the changeset gets exported back into the osm api db.

**Comment by sisskind** [comment]
@bwitham I was leaning more towards first option, as it would keep this feature contained to one section and could potentially allow user to configure in the UI.

**Comment by brianhatchl** [comment]
The second options wouldn't actually ingest, just create an object with the db connection parameters that would make it available for conflation.

**Comment by sisskind** [comment]
That is true, but it would also display in the datasets list.  If we went with first option, it would only appear in the Manage tab for database config (or something to that extent).

**Comment by bwitham** [comment]
It may be worthwhile talking to the users/stakeholders directly.  For the first option, I'm not seeing a lot of utility in the current design, b/c hoot only supports a single osm api db connection.  To support multiple, there would be a lot of services/core changes that need to be made.  So, if user a wants to point to MapEdit on aws and user b wants to point to it somewhere else, they're effectively messing each other up.  Also, not sure how comfortable admins are going to be sharing passwords directly with users in the first place.

**Comment by sisskind** [comment]
@bwitham even if it is just one connection, if we had in separate tab we could avoid the "why isn't the data loading" question.  My thought is user would go to the "Database Connection" tab, and choose a dataset to conflate with the current database connection, which is set by an admin in a conf file.  Future development could allow for choosing which connection.

**Comment by bwitham** [comment]
yeah, I think that makes sense.

**Comment by sisskind** [comment]
@bwitham can UI portion be worked on, or is there still some work required on back end?

**Comment by bwitham** [comment]
This may end up being obsoleted by the tasking manager integration work being discussed today...not sure yet.

**Comment by bwitham** [comment]
I think this can be considered OBE, given work on a tasking manager integration prototype.
