### ISSUE TITLE
Layers are remaining in sidebar

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#508]
Appears that layers that are loaded are not removed from sidebar after they are loaded and removed. This may be a feature of iD editor.

![123](https://cloud.githubusercontent.com/assets/6191659/16134625/39755fe4-33ec-11e6-8b7a-96a7df1e0516.png)

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/VGI-team-repo/issues/165

**Comment by sisskind** [comment]
It is possible that we are inadvertently adding layers to the iD layer list and the Hoot layer list.

**Comment by briandaviddavidson** [comment]
Looks like the layer needs to be there for the bottom layer list to render. Not sure why, but for now, I'm going to work on hiding the list item, then work on removing it completely.

Might be something that happens in the refactoring process.

**Comment by briandaviddavidson** [comment]
Testing when looking at the PR revealed more issues that I will be looking into

**Comment by briandaviddavidson** [comment]
Looks like this was relying on another PR that was not in the feature branch. After pulling in changes from `develop`, everything is operating as expected.
