### ISSUE TITLE
Limit how far the user can expand the conflation area

### ISSUE THREAD

**Issue by briandaviddavidson** [ngageoint/hootenanny-ui#515]
Currently, the dataset area can be expanded to cover the entire screen. This should be limited to at max, half the screen

Example:
![example](https://cloud.githubusercontent.com/assets/2423402/16240097/ef4e24dc-37b5-11e6-9804-00277c462450.png)

**Comment by mikejeffe** [comment]
@briandaviddavidson did you do a submodule sync after merging?  I just rebuilt and there didn't appear to be any changes in hoot-ui. I can still expand to full screen.

**Comment by briandaviddavidson** [comment]
No, I didn't. I'm not sure how to do that either. Is there something special I need to do in the commit?

**Comment by sisskind** [comment]
@mikejeffe pull request hasn't been done yet.

**Comment by mikejeffe** [comment]
Ok. I was just looking at the label change so I'll wait till the PR
