### ISSUE TITLE
Disable the locator overlay when switching away from Satellite imagery

### ISSUE THREAD

**Issue by briandaviddavidson** [ngageoint/hootenanny-ui#518]
There are black labels that can be added and removed to the satellite imagery. Since the OSM layer has it's own labels, it would be nice if these automatically turned off when the user switches to that layer.

Imagery:
![overlay_no_labels](https://cloud.githubusercontent.com/assets/2423402/16241013/d32dd9f6-37b9-11e6-8bd1-86562604a62a.png)

Imagery with labels:
![overlay_labels](https://cloud.githubusercontent.com/assets/2423402/16241009/d0874e26-37b9-11e6-9d5d-e0dbdda762ee.png)

OSM:
![osm_no_labels](https://cloud.githubusercontent.com/assets/2423402/16241030/df7be25c-37b9-11e6-80e5-2b2d5e751a87.png)

OSM with labels:
![osm_labels](https://cloud.githubusercontent.com/assets/2423402/16241017/d9360f94-37b9-11e6-861b-e41e7475eac6.png)

**Comment by briandaviddavidson** [comment]
A pull request has been submitted with fixes for this

**Comment by mikejeffe** [comment]
@briandaviddavidson the locator overlay is disabled when switching to the OSM basemap but was it your intention to override the option if the user selected the overlay for OSM?  I see that it will turn it on in the Minimap when selected but not in the main map (for OpenStreetMap (standard) only).

**Comment by briandaviddavidson** [comment]
@mikejeffe Not sure I follow. So you're saying that if you're on the OSM base map layer, it won't turn on at all? My intention was to turn it off whenever the user has it on and switches to the OSM base layer. They should be able to toggle it on and off once switching base maps though

**Comment by mikejeffe** [comment]
@briandaviddavidson it turns off so that part is functioning.  When I enable the location overlay with the OSM basemap on, it puts the black labeling on the minimap not the main map.  Thats all I am trying to say here.

**Comment by mikejeffe** [comment]
@briandaviddavidson after rebuilding the latest, it looks like it is adding the location overlay with labeling to the main map when you check it with the osm basemap.  I may have been hitting it in a half baked state.
