### ISSUE TITLE
Load dataset from the Manage Tab

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#519]
Add a "Load as Reference//Secondary Dataset" to the context menu in the Manage Tab. Either hide the option if dataset(s) are loaded or give warning.

**Comment by mikejeffe** [comment]
@sisskind the functionality associated with loading either the Secondary/Reference is there and functioning but it looks like after you add both, "Add Secondary" remains as a right-click option.  I'm going to close this ticket and add a separate bug ticket.
