### ISSUE TITLE
Update to include line snap shortcut in help menu and remove "Enable line snap" checkbox

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#520]
Currently, the line snap option is unchecked when Hootenanny starts. Yet, the line snapping feature is turned on. When the checkbox is checked and then unchecked, snapping turns off. Snapping should be off when Hootenanny starts.

https://github.com/ngageoint/hootenanny-ui/issues/306

**Comment by bwitham** [comment]
sorry, didn't mean to close this.

**Comment by curranMapper** [comment]
Hoot session does begin with snapping feature disabled.  However, once I enable it, I am not seeing any difference in snapping behavior when editing.  @kweint Can you take a look and report if you are seeing same thing?  Thanks

**Comment by kweint** [comment]
@curranMapper Just played with the snapping feature and experienced the same phenomenon as well.

**Comment by sisskind** [comment]
@brianhatchl do you remember anything legacy with line snapping?

**Comment by brianhatchl** [comment]
only that a customer wanted to be able to drop points on top of other features without them snapping.

**Comment by jcp2236** [comment]
There is a shortcut to disable line snapping, just hold the Alt key down
reference: openstreetmap/iD#2316

**Comment by jcp2236** [comment]
I'm going to make a note of the shortcut in the help menu, remove the line snap checkbox in the map data menu, and remove any instances of enableSnap (the function tied to the checkbox) in various JS files.
