### ISSUE TITLE
Clip to geographic bounds coordinates input dialog 

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#522]
The clip to geographic bounds needs to support the option of direct input of coordinates by entering those values through some kind of dialog, ideally with multiple coordinate formats (ex. DDDMMSS, DDD.dddddd, MGRS).

**Comment by sisskind** [comment]
What needs to be done:
* Finish styling
* Add in try/catch or some sort of error handling if drawing bounding box goes awry (perhaps on trying to add again, just remove any instance of the form and start over with fresh)
* Wire up 'Next' button with coordinates

**Comment by sisskind** [comment]
Fix error in map.js when drawing bounding box.

**Comment by mikejeffe** [comment]
Looks great @sisskind
