### ISSUE TITLE
Expanded sidebar offsets radial menu

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#536]
If the sidebar is expanded, it appears that the radial menu is offset by the amount the sidebar is expanded. Once the sidebar is reset, the radial menu adjusts back as well.

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/VGI-team-repo/issues/102

**Comment by briandaviddavidson** [comment]
Example:

![hootenanny](https://cloud.githubusercontent.com/assets/2423402/16457787/bc0af6e6-3dea-11e6-8393-9187978015bf.png)

**Comment by mikejeffe** [comment]
radial menu now appears above or adjacent to the selected feature.
