### ISSUE TITLE
Hoot not using full real estate

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#538]
1. Open Chrome
2. Snap Chrome to left or right of desktop so that it fills half the desktop real estate
3. Open Hoot
4. Maximize Chrome

![image](https://cloud.githubusercontent.com/assets/6191659/16461227/83038e26-3df9-11e6-858e-fdf8b83d01f7.png)

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/VGI-team-repo/issues/172

**Comment by curranMapper** [comment]
boooyaaaaaa! Works, ready to close
