### ISSUE TITLE
Make "Go To Review" bubbles draggable

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#539]
There are time when the "Go To Review" bubbles are on top of each other, and it may be helpful to drag them for a clearer view.

https://github.com/DigitalGlobe/VGI-team-repo/issues/166

**Comment by brianhatchl** [comment]
https://bl.ocks.org/mbostock/4062045

U can do it!

**Comment by sisskind** [comment]
It's like a DNA diagran!

**Comment by jcp2236** [comment]
That's awesome!

**Comment by curranMapper** [comment]
@sisskind Is this the message that should be draggable?  Thanks

![image](https://cloud.githubusercontent.com/assets/15927720/18554989/215cd0ce-7b34-11e6-92d2-7b1530cfb084.png)

**Comment by jcp2236** [comment]
The green bubbles that pop up in review mode (right option in the review radial menu).
![screenshot from 2016-09-15 12 25 22](https://cloud.githubusercontent.com/assets/17727812/18558159/09c88abe-7b40-11e6-964b-6672d88c2f83.png)

**Comment by curranMapper** [comment]
Thanks @jcp2236 

Yes.  Able to move bubbles around, went to next reviews, came back and they were back in default position.  Looks good to close to me!
