### ISSUE TITLE
Cannot zoom further error when editing geometry in layer

### ISSUE THREAD

**Issue by mikejeffe** [ngageoint/hootenanny-ui#540]
In Firefox when you add a layer, then click on Point, Line or Area to create a new geometry then click on the map and drag by holding down left click of mouse you get an error message like https://cloud.githubusercontent.com/assets/15252833/16462310/a1194ef0-3dfe-11e6-956d-2ba6e0f10af5.png  

In Chrome I am seeing some inconsistencies with this behavior.  Can't hit the AWS instance at the moment but my vagrant build is having similar issues.  If I add a layer like PortAuPrince and try to create a polygon in the water at zoom level 16, I get the Cannot zoom further error.

**Comment by mikejeffe** [comment]
@sisskind can you confirm this?

**Comment by sisskind** [comment]
Yes -- but this ticket already exists.  https://github.com/ngageoint/hootenanny-ui/issues/376
