### ISSUE TITLE
Hitting Enter on Add Folder Refreshes Hootenanny

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#541]
Hitting enter/return key when adding a folder on Hootenanny refreshes the browser on Chrome.  This is unfortunate.  Should either do nothing, or submit the form.

**Comment by mikejeffe** [comment]
Looks like the first time you hit return after creating a new folder it refreshes the browser but all subsequent times, it works correctly.  @sisskind can you confirm whether this occurs on your end.

**Comment by mikejeffe** [comment]
I think this is working fine now.
