### ISSUE TITLE
Fix issue of appending id when not available

### ISSUE THREAD

**Issue by briandaviddavidson** [ngageoint/hootenanny-ui#542]
In https://github.com/ngageoint/hootenanny-ui/issues/518, some of the code ([specifically this commit](https://github.com/ngageoint/hootenanny-ui/commit/c32a30f17a3e70a04562711e0c5366aa3deeb7cc)) appended an ID which broke other parts of the code. This needs to be corrected.

**Comment by briandaviddavidson** [comment]
This was fixed in the PR above.

If `d.ImageryUsed()` is a string, an ID will be appended, otherwise it will pass over that attribute.

**Comment by mikejeffe** [comment]
no need to keep this open.  If a developer can confirm than just close it.

**Comment by briandaviddavidson** [comment]
@jcp2236 Can you please confirm and close.

PR has already been merged: https://github.com/ngageoint/hootenanny-ui/pull/543

**Comment by jcp2236** [comment]
Confirmed.
