### ISSUE TITLE
Disappearing features on zoom

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#546]
If I draw a shape and zoom down all the way and can't see the features (lines/points) and then zoom out - it vanishes. For instance, draw a big square, zoom down within that square as far as you can (I don't know the threshold), and then zoom out. Square gone! In the following example, I zoomed down just to the point where the sides of the square are off screen and it disappeared (the save & undo buttons reset). Upon zooming back out, it's gone.

![image](https://cloud.githubusercontent.com/assets/6191659/16626630/d2fa38c0-4377-11e6-8a3d-d19b625bd101.png)

![image](https://cloud.githubusercontent.com/assets/6191659/16626633/d6a36942-4377-11e6-80e6-f0e823361f25.png)

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/VGI-team-repo/issues/177

**Comment by briandaviddavidson** [comment]
Going to see if I can recreate this

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/VGI-team-repo/issues/183

**Comment by briandaviddavidson** [comment]
https://github.com/DigitalGlobe/VGI-team-repo/issues/183 appears to be just related to the highlight as opposed to the entire feature. I'm going to create a new ticket for it.

**Comment by briandaviddavidson** [comment]
Unable to recreate this

**Comment by briandaviddavidson** [comment]
Finally able to recreate with data provided by @mikejeffe.

Steps to recreate:

1. Add data and set it as the reference dataset (in my case, `PortAuPrinceOsmRef1`)
2. Turn on Feature Highlight
 * Shortcut is the `f` key
 * Expand Map Features
 * Select `Hightlight edited features`
3. Draw an area
 * The highlight lags slightly
4. Zoom all the way out to z0
5. Zoom back in and the feature will disappear.

The feature can be seen up until z16, so there must be some code that's running to remove those features when z16 is hit. Going to investigate further.

**Comment by briandaviddavidson** [comment]
Looks like there is no need to turn on the highlight for the feature to disappear. Once z16 is hit, whether zooming in or out, the feature drawn will disappear

**Comment by briandaviddavidson** [comment]
After debugging with @sisskind looks like the contents were being removed when zoom 16 was passed in `connection.js`.

There are other areas where `context.flush()` is being called. Not sure if a variable need to be passed in those either. Going to investigate further.

**Comment by briandaviddavidson** [comment]
Doesn't seem to be necessary anywhere else. Submitting PR now.

**Comment by briandaviddavidson** [comment]
Small datasets no longer have this problem. I have created a new ticket for large datasets, so I'm going to close this ticket.
