### ISSUE TITLE
Adding an id might interfere with other already created IDs

### ISSUE THREAD

**Issue by briandaviddavidson** [ngageoint/hootenanny-ui#552]
Related to: #542 

If for some reason, the `typeof` is a string, but the value is a number (so for example, `9`), this could potentially cause a duplicate of IDs which will be a problem down the road.

After some initial testing this morning with @sisskind, I am going to do some more research into the problem.

**Comment by sisskind** [comment]
Will be OBE RE: Hoot 2.0
