### ISSUE TITLE
When 2 datasets are loaded, first dataset lags on refresh

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#560]
Appears to occur with newer versions of Chrome.  Does not occur on Firefox.

Only occurs when two datasets are loaded, and it is the first dataset that was loaded that appears to lag.

**Comment by sisskind** [comment]
After some further investigation, appears to only be occurring with lines or highlights, not points or polygons.

**Comment by sisskind** [comment]
![560](https://cloud.githubusercontent.com/assets/6191659/17027637/a833a240-4f32-11e6-81f4-2d8ec7b22613.gif)

**Comment by sisskind** [comment]
Appears to occur after the second dataset is added, but will persist even if that dataset is removed.

**Comment by mikejeffe** [comment]
I wonder if this is a gpu acceleration issue:  https://bugs.chromium.org/p/chromium/issues/detail?id=117032

**Comment by sisskind** [comment]
It is possible, but if that were the case I would expect it to have a lag with all features, not after adding a second layer

**Comment by sisskind** [comment]
It's the ticket I just can't quit.  It is definitely layer dependent, as a created feature does not have lag until after it is saved and part of layer.  Measurement lines, unsaved features, do not lag.  The aforementioned highlight issue still exists though (but was part of previous layer, so that may work out if this bug is fixed).

![560-1](https://cloud.githubusercontent.com/assets/6191659/17036616/0ca83240-4f5b-11e6-9612-c25e8d8d1f9d.gif)

**Comment by sisskind** [comment]
After testing with version prior to upstream merge, I can safely assume that this has nothing to do with the new version of iD.

**Comment by sisskind** [comment]
Where paths are being returned for draw: https://github.com/ngageoint/hootenanny-ui/blob/develop/js/id/svg.js#L15

**Comment by sisskind** [comment]
It is possible that it is not the feature lagging, but just the highlight.

**Comment by sisskind** [comment]
It appears that it is the line-shadow that is lagging, not the line-stroke.

**Comment by kweint** [comment]
Testing the lagging issue right now, and haven't found any lag on refresh when two datasets are loaded thus far. Currently testing with DC Street_Centerlines_Light and district_of_columbia_highway. Will expand testing to more datasets.

**Comment by kweint** [comment]
Gave this ticket another go with every test dataset at my disposal. Could not replicate the lag bug.
