### ISSUE TITLE
Field Dropdowns

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#566]
When setting up the conflation process in Hoot if the user clicks the field area (Path, Type, Attribute Reference Layer, etc) the field option only drops to either what is currently populated or the first item in the list. To get the full list of options the user has to click the dropdown arrow at the end of the fields. For newer users they may be unknowingly forced to pick a limited option when many more exist. This issue is inconsistent as it's only found in the conflation fields and is not present in the Add Dataset fields.

**Comment by sisskind** [comment]
It appears that this is **not** a bug.  Rather, when the user selects the input box, it is only showing what matches that set filter.  If the drop-down is set to read-only, this is not an issue.  May have to 2x check to make sure that if blank, the default value is used (placeholder in most situations), and that a placeholder is being set.

**Comment by briandaviddavidson** [comment]
I've added a prototype of the dropdown for consideration. To see it, add data (I used `dcpoi_clip`) and add a point to the layer. You'll see the dropdown as opposed to the combobox.

Commit: https://github.com/ngageoint/hootenanny-ui/commit/353bc3f3dd84a459e0ef2e0f10c1b0769778ca5c

**Comment by briandaviddavidson** [comment]
Per discussion with @sisskind, I'm going to change back to the d3 combobox, then create a class that will be applied to comboboxes that should have the same event as the caret as well as be `readOnly`

**Comment by sisskind** [comment]
Reaching out to stakeholders, as we may be overthinking this one.  It isn't a bug, and maybe just need to include in our documentation that it is a filtering drop down...

**Comment by briandaviddavidson** [comment]
I think that's the best way to move forward as well. I can't figure out a way to have the dropdown while still filtering with text.
