### ISSUE TITLE
Paste Attributes Button

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#570]
Create a new button alongside the select all attributes to paste attributes. Will require a toggle for either append or overwrite.

**Comment by brianhatchl** [comment]
This feature request is problematic for a few reasons.  The paste tags feature requires the user to select the target features for pasting.

1. If one target feature is selected, the raw tag editor is updated with that features values.  The selected tags are displayed, but the copied values only change when the set of selected tags changes.  Having a paste attributes button here would be confusing as to which values are being pasted.
2. If two or more target features are selected, the raw tag editor is not shown at all (i.e. the paste attributes button could not be accessed.

Appearing on the tool bar when tags have been copied may be a better location for the Paste Attributes Button.

**Comment by sisskind** [comment]
@brianhatchl good points.  I think the LOE of adding to the "Tools" Menu or on the toolbar is the best bet, as it will fulfill the same objective.

**Comment by brianhatchl** [comment]
![screenshot from 2016-07-29 16 20 25](https://cloud.githubusercontent.com/assets/2600932/17262311/a5cab49a-55a8-11e6-9f59-44f0e41634e4.png)

**Comment by sisskind** [comment]
Will take a look at tonight.  Icon skills are most impressive on this one.

**Comment by curranMapper** [comment]
Unable to copy & paste tags prior to conflation or during conflict resolution process.

**Comment by brianhatchl** [comment]
Both of those buttons are paste actions.  To enable them you have to select a feature and Ctrl+C or use the raw tag editor to select a subset of tags to copy.  Then select the destination feature(s) and the paste attributes buttons should enable.

Could that be the problem?

**Comment by curranMapper** [comment]
@brianhatchl Followed those steps to verify was unable to perform paste append or paste overwrite option.

**Comment by brianhatchl** [comment]
Ok, I tried it and the buttons do enable, but when clicked the tags in the sidebar are not updating.  (The change tags action does seem to be applied as the Undo button becomes enabled and there is a Change Tags step in the edit history.  I'll look into it.

**Comment by brianhatchl** [comment]
https://github.com/ngageoint/hootenanny-ui/issues/700
