### ISSUE TITLE
Disappearing Highlight

### ISSUE THREAD

**Issue by briandaviddavidson** [ngageoint/hootenanny-ui#571]
Original Ticket: https://github.com/DigitalGlobe/VGI-team-repo/issues/183

1. Open a dataset in review mode.
2. Turn on Highlight Edited Features.
3. Make a change to a feature.
4. Pan AWAY from the changed & highlighted feature.
5. Pan BACK to the changed & highlighted feature.
6. Highlight is GONE.
7. Zoom out a little bit at a time.
8. Highlight is BACK!!!

Alternatively, if you make a change & zoom out substantially and then zoom back in, the change is reset (same thing as previously reported, when you draw a feature (point, line, or poly))

AND if I zoom out far enough, when the highlighting disappears the map goes into refresh mode and says "Please wait while loading missing features"

This is occuring in stable AWS build and the nightly build.

**Comment by mikejeffe** [comment]
I am seeing this issue resurface in both the release and nightly AWS.  Two tests I run are panning away from a highlighted yellow feature and zooming way out with the mouse scroll wheel.  In both cases the highlight turns off.  When I tested this prior it did not appear that the highlight was disappearing.

**Comment by mikejeffe** [comment]
Note that when I zoom out to the point of getting the message, Please wait while loading missing feature, the highlight disappears.

**Comment by briandaviddavidson** [comment]
@mikejeffe:
I'm unable to reproduce the error on the `develop` or `release` branch. Can you check my process to make sure I'm doing it correctly?

1. Add dataset (in my case, `dcpoi_clip`)
2. Draw a polygon
3. Label it as something (I pick park since it's the first option)
4. Turn on `Highlight edited features`

From there, I zoom out as far as I can and I still see the highlight. I can also pan away from the area and zoom all the way out and the highlight still appears when I pan back. Could it be an AWS issue?

**Comment by mikejeffe** [comment]
@briandaviddavidson 

I think this is reproducible on larger datasets like the Port Au Prince Ref1/Ref2 data.  Do you have those?  On smaller datasets, it looks like hoot never needs to load missing features and I noticed with some Samoa data that issue didn't occur i.e. highlighted features remained highlighted, but on larger datasets like Haiti with a dense feature count, when I zoom out it seems to trigger that feature load message which loses the handle on the highlight.  Make sense?  I can point you to the data that can recreate if you don't have access to it.

**Comment by briandaviddavidson** [comment]
I've tested with PortAuPrince data locally and still have the highlight render properly. Once I can access the nightly build, I will test there as well and will update when completed.

**Comment by mikejeffe** [comment]
@briandaviddavidson I'm also going to test both my local develop and release branch again.  It wouldn't be the first time that issues appear only on my local environment which is why I wanted to confirm this on the nightly AWS.

**Comment by mikejeffe** [comment]
@briandaviddavidson can you try on your local with the attached dataset?  Ingest it and make changes to a feature with highlight on.  Then zoom way out and back in.  If you get the message about the feature reloading then the highlighting is likely disappearing.

[PortAuPrinceOsmRef1.zip](https://github.com/ngageoint/hootenanny-ui/files/384341/PortAuPrinceOsmRef1.zip)
PortAuPrinceOsmRef1

**Comment by briandaviddavidson** [comment]
Thanks for that dataset @mikejeffe. So the highlight doesn't disappear for me, but the feature itself disappears, which up until now I hadn't been able to recreate.

**Comment by briandaviddavidson** [comment]
Unable to recreate. I've assigned it to @jcp2236 to see if he can recreate it

**Comment by jcp2236** [comment]
The feature is disappearing on me when I use the Port Au Prince dataset. I'm drawing a polygon, turning on highlight and zooming out rapidly until I get the "loading missing features" message.

**Comment by jcp2236** [comment]
Both the feature and highlighted border disappear from the map.

**Comment by briandaviddavidson** [comment]
Ahh ok. I haven't been trying with a conflated dataset. I will look into that.

**Comment by briandaviddavidson** [comment]
Going to create a new ticket for the issue of a conflated dataset disappearing
