### ISSUE TITLE
Center Text inside "Go To Review" bubbles

### ISSUE THREAD

**Issue by mikejeffe** [ngageoint/hootenanny-ui#582]
Just a minor quip but one worth pointing out, in cases where you get a lot of related reviews (Lativa POI for example), when the letter count goes into double digit e.g. AA, BB, CC, etc., the text appears off-center from the bubble making it look a little sloppy.  See EE, GG in pic below.

![image](https://cloud.githubusercontent.com/assets/7560096/17041402/af4cf158-4f5a-11e6-8437-33a29d8fb4b6.png)

**Comment by sisskind** [comment]
@jcp2236 FYI

@mikejeffe is there a solid dataset to replicate?

**Comment by mikejeffe** [comment]
@sisskind datasets below work.  

[Latvia_Geonames_Poi_hotel_crop.zip](https://github.com/ngageoint/hootenanny-ui/files/378908/Latvia_Geonames_Poi_hotel_crop.zip)
[Latvia_OSM_Poi_hotel_crop.zip](https://github.com/ngageoint/hootenanny-ui/files/378907/Latvia_OSM_Poi_hotel_crop.zip)

**Comment by jcp2236** [comment]
I'm on it, thanks for letting me know.

**Comment by briandaviddavidson** [comment]
Code has been added through this PR: https://github.com/ngageoint/hootenanny-ui/pull/600
