### ISSUE TITLE
Loading review layer from manage dataset tab should open map after pop-up

### ISSUE THREAD

**Issue by mikejeffe** [ngageoint/hootenanny-ui#583]
I noticed when adding a review layer that had open reviews from the Manage | Dataset list (either as reference or secondary), the pop-up appears that layer has unresolved reviews but it doesn't open the map view.  It should probably open the map since that might be confusing to the user.

**Comment by sisskind** [comment]
@mikejeffe good point!  Will do for current develop branch.

**Comment by RobMaps** [comment]
Completed testing for this issue.  Attempted to add a layer that still has open reviews via the data manager window.   Adding this file as the Reference or Secondary layer does not automatically change Hootenanny to the map view.  The prompt notifying the user that the layer has open reviews does automatically appear.  Further attention is needed for this issue.

**Comment by sisskind** [comment]
@RobMaps @kweint Can you take a second look at this one?

**Comment by kweint** [comment]
@sisskind I just tested the issue myself and had the same results.

**Comment by sisskind** [comment]
@kweint thanks -- looking into now

**Comment by sisskind** [comment]
@kweint can you test this one again?

**Comment by kweint** [comment]
@sisskind This issue appears to be resolved!
