### ISSUE TITLE
Cannot edit tag values when active schema is TDS/MGCP

### ISSUE THREAD

**Issue by mikejeffe** [ngageoint/hootenanny-ui#584]
I have been trying to edit tag values for different features and it appears on my end at least that you can only save changes made to tags when the active schema is OSM (filter by type = osm).  When I change this to either TDS or MGCP and try to edit the Name (NAM) or other attributes, the Save button does not appear.  If however I edit the name field for a feature while OSM is the active schema, the feature is highlighted in yellow and the save button appears.  I tested the release and the nightly AWS.

**Comment by mikejeffe** [comment]
I should add that clicking on the Feature Type e.g. Secondary Road, works regardless of schema type.  In otherwords it triggers the save option.  However clicking in the MGCP field, Condition of Facility and changing from Destroyed to UNK does nothing.

**Comment by brianhatchl** [comment]
After digging around, this seems to have broken between the Changes for 1.75 commit d77d3cc171bf2978357434b1881767ee3ac47f44 and the Changes for v1.92 commit 5377b4d9076b5d56439a06ed0f495cf379c57616

**Comment by brianhatchl** [comment]
So it seems like the preset and raw tag editor controls that get created for the non-OSM schemas are not getting the change handler set, which is happening here https://github.com/ngageoint/hootenanny-ui/blob/develop/js/id/ui/entity_editor.js#L12-L15

>    var presetEditor = iD.ui.preset(context)
        .on('change', changeTags);
    var rawTagEditor = iD.ui.RawTagEditor(context)
        .on('change', changeTags);

**Comment by brianhatchl** [comment]
I take it back, it seems like the callback for updateEntityEditor() is never getting reached.

>    function changeTags(changed) {
        var entity = context.entity(id);

        // for all non OSM translation
        if(currentTranslation !== 'OSM') {
            plg.updateEntityEditor(entity, changed, rawTagEditor, currentTranslation,
            function(OSMEntities){
                           // store to internal
                //entity.tags = {};
                changeTagsHandler(OSMEntities);

            });


        } else {
            changeTagsHandler(changed);
        }

**Comment by brianhatchl** [comment]
Tag changes to a feature with non-OSM schema should now enable the Save buttonu / update edit history

**Comment by mikejeffe** [comment]
@brianhatchl @sisskind is this going to be merged into the release branch?  I was looking for it on the develop branch but don't think it's there yet.

**Comment by brianhatchl** [comment]
There is an open PR #584 on the develop branch.  Commit can then be cherry-picked to release branch.

**Comment by brianhatchl** [comment]
Actually, yes.
