### ISSUE TITLE
Rename the list of translations to make them easier to understand

### ISSUE THREAD

**Issue by mattjdnv** [ngageoint/hootenanny-ui#586]
Currently, the list of translations uses up heaps of screen real estate in the UI and looks like this:
```
"NSG Topographic Data Store (TDS) v6.1",
"NSG Topographic Data Store (TDS) v4.0",
"Multinational Geospatial Co-production Program (MGCP) TRD3&4",
"OpenStreetMap.org (OSM)",
"GeoNames.org",
```

How about something like this:
```
"TDSv61 NSG Topographic Data Store v6.1",
"TDSv40 NSG Topographic Data Store v4.0",
"MGCP TRD3&4 Multinational Geospatial Co-production Program TRD3&4",
"OSM OpenStreetMap.org",
"GeoNames.org",
```

or, even better, just have the short name/acronym and have the full name appear in a popup/tool tip.

It would be nice to do this before we add in GGDM & TGD:
"Ground-warfighter Geospatial Data Model (GGDM) v3.0"
"Theater Geospatial Database (TGD) v2.2"

**Comment by mattjdnv** [comment]
They come from the "DefaultTranslations" file.

**Comment by rmrice** [comment]
Went with the tooltips option. I simply took the description/long name and put it in a tooltip so now the translations list just shows the short name. Passed cucumber test locally. 

![screenshot from 2016-08-02 16 12 50](https://cloud.githubusercontent.com/assets/17434033/17343517/1c0397a0-58cc-11e6-8ed5-bbf9da5cbe41.png)
See PR #616.

**Comment by sisskind** [comment]
Great job!
