### ISSUE TITLE
Cannot multiselect datasets using crtl key on a Mac

### ISSUE THREAD

**Issue by mikejeffe** [ngageoint/hootenanny-ui#591]
Similar issue to https://github.com/ngageoint/hootenanny-ui/issues/579 where the control key on a mac does not have the same functionality that the ctrl key on windows/linux has.  This prevents users from multiselecting data.  It didn't seem to work with the command key as well.

**Comment by mikejeffe** [comment]
@sisskind fyi

**Comment by sisskind** [comment]
Blocked by #595
