### ISSUE TITLE
Review Bookmark settings missing user option.

### ISSUE THREAD

**Issue by mikejeffe** [ngageoint/hootenanny-ui#602]
In previous versions of bookmarked reviews prior to refactoring, different users could add comments to an existing review bookmark by clicking on the "user icon" in the top right corner but it appears now that the user icon ![image](https://cloud.githubusercontent.com/assets/7560096/17189850/47b8d53c-53f8-11e6-9eb5-02ad97a51065.png) has been removed and the comments will always appear from the last user to create a bookmark.

![image](https://cloud.githubusercontent.com/assets/7560096/17189761/d88e4c46-53f7-11e6-8141-43a2076081bf.png)

**Comment by curranMapper** [comment]
The user icon (upper right corner, referenced in first comment of ticket) is displayed and functional to user.

![screenshot from 2016-09-06 16 10 07](https://cloud.githubusercontent.com/assets/15927720/18289199/6c5bf102-744c-11e6-9cda-8e543ed75322.png)
