### ISSUE TITLE
Expanded sidebar offsets review bubbles when dragged

### ISSUE THREAD

**Issue by jcp2236** [ngageoint/hootenanny-ui#605]
If the sidebar is expanded, it appears that the review bubbles are offset when holding down the mouse to drag by the amount the sidebar is expanded. Once the sidebar is reset, the bubbles adjust back as well.

**Comment by briandaviddavidson** [comment]
Code that might be of use

Offset radial menu: https://github.com/ngageoint/hootenanny-ui/pull/550
Sidebar expanding: https://github.com/ngageoint/hootenanny-ui/pull/533

**Comment by jcp2236** [comment]
#606 should have fixed this issue

**Comment by briandaviddavidson** [comment]
#606 has fixed this issue. Going to close this ticket.
