### ISSUE TITLE
Sidebar expanding over map

### ISSUE THREAD

**Issue by briandaviddavidson** [ngageoint/hootenanny-ui#606]
This is a research ticket to try to figure out how to drag the sidebar and not move the map container to alleviate the issue of adjusting the width for all the svg elements (radial menu, drawing tools, etc.)

Related ticket: https://github.com/ngageoint/hootenanny-ui/issues/605

**Comment by briandaviddavidson** [comment]
@jcp2236 is going to take over as primary since this relates to tickets he is completing

**Comment by briandaviddavidson** [comment]
An initial prototype can be found on [branch `606`](https://github.com/ngageoint/hootenanny-ui/tree/606)

**Comment by briandaviddavidson** [comment]
This is ready for review. The map is now 100% stationary with the bars/sidebar moving over top the map instead of moving along the same plane as the map. This solves a lot of issues involving offsetting the review bubbles, radial menu, delete menu, etc.

cc @brianhatchl @sisskind

**Comment by sisskind** [comment]
Great work team!

**Comment by brianhatchl** [comment]
Can you create a pull request?

**Comment by curranMapper** [comment]
Yes, sidebar and top bar slide over bubbles/dial
