### ISSUE TITLE
Merged POI result feature isn't being selected

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#61]
During conflation review, if two POIs were merged, the resulting feature was selected so that an orange halo appeared and the sidebar showed the tag info for that merged feature.  This behavior seems to have been lost in the refactor of reviews as relations.

**Comment by bwitham** [comment]
behavior reproduced. rolling back commits locally to find last working codebase.

**Comment by bwitham** [comment]
code works correctly at b0469a, so problem most likely caused by 77cef2

**Comment by bwitham** [comment]
correction...occurring before 77cef2....still trying to find the commit...

**Comment by bwitham** [comment]
too hard to nail it down before 77cef2, as there are some broken commits where the review code errors out...will proceed from that commit
