### ISSUE TITLE
Node appears when line is split

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#617]
To replicate:

1. Run conflation job
2. Find "T" intersection or something similar.
3. Split the top part of the "T" at the intersection.
4. Delete each segment separately.
5. A node will appear on the intersection point

https://github.com/DigitalGlobe/VGI-team-repo/issues/104

**Comment by briandaviddavidson** [comment]
Customer has decided to leave this as is. Closing this ticket.
