### ISSUE TITLE
hoot:status tag

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#618]
Within hootenanny, the hoot:status tag value (1,2,3) represents the data as reference, secondary, and auto-conflated respectively.

When exported as OSM, this tag does not carry over.

It may be useful for this tag to carry over for users to be able to filter by outside of Hoot, particularly to identify those roads that were auto-conflated that were not part of manual review.

**Comment by sisskind** [comment]
DigitalGlobe/vgi-team-repo#113

**Comment by sisskind** [comment]
@mattjdnv where are we with this one?

**Comment by sisskind** [comment]
@mattjdnv pinging for status (when you get back that is)

**Comment by sisskind** [comment]
@mattjdnv anything I can do to help on this one?

**Comment by sisskind** [comment]
Need to add checkbox/option to export with **-D writer.text.status=true**, only for exports with OSM schema.

**Comment by sisskind** [comment]
@mattjdnv getting something weird in output -- can you confirm this should be happening or not?

Updated osm2ogrscript to add writer.text.status=true (https://github.com/ngageoint/hootenanny/commit/d536d5075ed002c61fbf6783f6ba832c6bc6ad55)

Ran export with OSM schema and shapefile and opened in QGIS -- but seeing this:
![image](https://cloud.githubusercontent.com/assets/6191659/20220140/5c5425d6-a7fa-11e6-967f-2423341dc387.png)

Thoughts?

**Comment by mattjdnv** [comment]
Hmmm, not expected.

Working on it.

**Comment by mattjdnv** [comment]
Done.  Updated the branch and created a pull-request.

**Comment by mschicker** [comment]
PR Merged.
