### ISSUE TITLE
Review features are not re-centering on reference feature

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#62]
During conflation review, when the next review item is retrieved, the map should re-center on the reference review item haloed in red.  It seems when the next review items are within the current map extent, this is not happening.  Not sure if this has always been a bug or if it was introduced in the refactor of reviews as relations.

**Comment by bwitham** [comment]
I'll look into #61.  This one is more of a @jchoi1267 task.

**Comment by bwitham** [comment]
I think the code to calculate bounds in the review services was removed as a result of 5496, but it seems like it wouldn't be too hard to resurrect it if its needed. However, its possible there are missing feature load considerations in iD that I'm not fully aware of that prevents the change ... @jchoi1267 may be more familiar with that than I am.

**Comment by sisskind** [comment]
This appears to be on purpose: 
```
function panToEntity(entity, force) {
        	//only pan if feature is not on screen
```
https://github.com/ngageoint/hootenanny-ui/blob/develop/js/hoot/control/Conflicts.js#L115

**Comment by brianhatchl** [comment]
It could be that is only being noticed now with the introduction of the geohash/hilbert curve index that increases the chances that the next review item will be within the current visible map

**Comment by sisskind** [comment]
Should be fixed by https://github.com/ngageoint/hootenanny-ui/pull/79.

**Comment by mjeffe98** [comment]
@sisskind we do zoom to the entity (review pair) now by default but we no longer recenter on the reference POI since we are zooming to an extent where both review POIs are in the current map extent.  Can we close based on that behavior?

![image](https://cloud.githubusercontent.com/assets/7560096/11695281/39d31310-9e63-11e5-855a-187022d5c1c1.png)

**Comment by sisskind** [comment]
I am okay with that.
