### ISSUE TITLE
Intermittent issue jumping to review features

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#621]
When in review mode, if user zooms out to extent, and then zooms back into map away from the extent of the review layer, clicking the red/blue review table does not jump to feature. Happens in both Chrome and FF.

DigitalGlobe/vgi-team-repo#54

**Comment by briandaviddavidson** [comment]
Haven't been able to reproduce the error, so it could have been fixed in a prior release unknowingly. I'm checking with the customer to see if they've noticed an issue and if so, on what dataset so I can work on recreating it here.

**Comment by briandaviddavidson** [comment]
Just recontacted the customer after a week to get an update

**Comment by sthorneloe** [comment]
I think this was actually one of mine...March was a long time ago.  I think this has been fixed.

**Comment by briandaviddavidson** [comment]
OK sounds good @sthorneloe. I will go ahead and close this ticket. If the issue arises again, we can reopen this ticket as necessary.
