### ISSUE TITLE
Disappearing features in large conflated dataset

### ISSUE THREAD

**Issue by briandaviddavidson** [ngageoint/hootenanny-ui#622]
To recreate:

1. Get a large, conflated dataset
 * I used `PortAuPrinceOsmRef1` and `PortAuPrince_OSM_Roads` conflated together 
2. Draw a line or polygon
3. Turn on `Highlight Map Features`
4. Zoom out quickly

If the `Loading Missing Features` message appears, all of the changes that have been made are cleared.

Related to: #571 #546

**Comment by briandaviddavidson** [comment]
I have only been able to recreate this once. @jcp2236 recreated it once using the steps above and @rmrice couldn't recreate at all. Going to put this in the `Backlog` until we can find a reliable way to recreate this issue.

**Comment by sisskind** [comment]
Closing.  Can reopen or create new ticket if we can recreate.
