### ISSUE TITLE
Review mode not showing both pairs in extent

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#624]
Review mode should show all review features in extent.  Used to work, now it doesn't.  :(

See:
https://github.com/ngageoint/hootenanny-ui/issues/84
https://github.com/ngageoint/hootenanny-ui/issues/62

**Comment by briandaviddavidson** [comment]
When going to a new pair of review features, both should now be visible on the map

**Comment by curranMapper** [comment]
Went through reviews, all conflicts zoomed to extent that included both features in conflict
