### ISSUE TITLE
When a review layer is loaded change color to green

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#63]
When loading a layer that has open review items, and the user enters review mode, change the layer color to green.  This is a reasonable default because the two conflation inputs will be colored orange and pink.  The merged layer needs to use a third color so the use can tell the difference between merged features ("green") and untouched input features ("orange" or "pink").

**Comment by sisskind** [comment]
@mjeffe98 Ready for test.

https://github.com/ngageoint/hootenanny-ui/pull/73
