### ISSUE TITLE
Create iD info button on sidebar

### ISSUE THREAD

**Issue by rmrice** [ngageoint/hootenanny-ui#633]
DigitalGlobe/VGI-team-repo#198

**Comment by rmrice** [comment]
I've identified the files necessary to make a change:
`js/id/actions/info.js` - new file
`js/id/operations/info.js` - new file
`js/id/ui/radial_menu`
`data/core.yaml`

The radial menu calls functions from the operations folder and data from the yaml file. 

I've also added an info button to the sprite sheet and `iD-sprite.json`, but I'm not sure where this button should get called.

Still trying to figure out how to append an additional button from the operations folder. I might be missing something else. 

I'm removing the milestone tag since I am going on PTO for 2 weeks. If anyone else wants to pick it up, feel free. If not I'll pick it up once I get back.

**Comment by sisskind** [comment]
Shortcut key is good enough; button not required.
