### ISSUE TITLE
Tag search with OSM schema selected returns other schema values

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#638]
When the tag search is run, it returns matches from all schemas supported by the switcher.  Not sure if this is intended behavior, but it results in duplicates as shown here:
![screenshot from 2016-08-15 16 33 26](https://cloud.githubusercontent.com/assets/2600932/17678751/77e949b8-6306-11e6-825b-dfd444d7efc5.png)

I would expect only OSM schema tags to be found by the search.

**Comment by sisskind** [comment]
@brianhatchl still relevant?

**Comment by brianhatchl** [comment]
This has been addressed in the schema switcher refactor and should be ready for test.

**Comment by brianhatchl** [comment]
Actually, schema switcher refactor hasn't been merged back into hoot-ui yet, so need to do that.

**Comment by brianhatchl** [comment]
Yet, it appears a commit was made to fix this particular error, back to ready to test

**Comment by brianhatchl** [comment]
This will have to wait until https://github.com/ngageoint/hootenanny-ui/issues/637 is complete

**Comment by kweint** [comment]
Cool news: the search results now reflect whatever the chosen tag schema may be.
