### ISSUE TITLE
In conflation review, 'Previous' and 'Next' are misnomers

### ISSUE THREAD

**Issue by jcp2236** [ngageoint/hootenanny-ui#643]
Clicking 'Previous' doesn't guarantee that you will visit the actual previous review item.

**Comment by briandaviddavidson** [comment]
What datasets were you using?

**Comment by jcp2236** [comment]
I was using the Latvia OSM POI data, but it seems to be consistent for most if not all, it's just easier to notice in the large datasets. I got those from Mike Jeffe here -> #582

**Comment by sisskind** [comment]
Possible solution:  change to arrows?

**Comment by sisskind** [comment]
Also for Validation!

**Comment by sisskind** [comment]
Or...are they not doing what they should be doing?

**Comment by jcp2236** [comment]
This has been verified to be working as intended.
