### ISSUE TITLE
Add poi to polygon conflation to the UI

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#644]
Do after ngageoint/hootenanny#979 is complete.

* make sure the following matcher gets added to the server configuration:  hoot::PoiPolygonMatchCreator (already the default in ConfigOptions.asciidoc)
* make sure the following merger gets added to the server configuration:  hoot::PoiPolygonMergerCreator (already the default in ConfigOptions.asciidoc)
* for poi to polygon reviews, hook up to the poi/polygon merge service created by ngageoint/hootenanny#979 - see plugins/test/ElementMergeServer.js for examples
* only a single POI and a single poly should be passed to the merge service

**Comment by sisskind** [comment]
@bwitham pinging on status

**Comment by bwitham** [comment]
I'm finishing up the core code by tomorrow, Monday at the latest.  After that, I think the services tasks in this epic would need to be done before this could be done probably.

**Comment by bwitham** [comment]
So I don't forget...as part of the ngageoint/hootenanny#979 changes all references to 'p2pmerge' are now replaced with 'elementmerge' to reflect the multiple types of merging now done by the nodejs service.

**Comment by sisskind** [comment]
@bwitham @mattjdnv 

Advanced options now includes hoot::PoiPolygonMatchCreator and hoot::PoiPolygonMergerCreator.  Is anything else required?

**Comment by bwitham** [comment]
hook up to to the merger; see description, third bullet.

**Comment by sisskind** [comment]
![issue644](https://cloud.githubusercontent.com/assets/6191659/21662072/c16f5c30-d2a5-11e6-83d2-75e7580c9c7d.gif)

**Comment by sisskind** [comment]
@bwitham is there a good poi-building dataset to test?

**Comment by brianhatchl** [comment]
I found https://github.com/ngageoint/hootenanny/blob/develop/test-files/cmd/slow/PoiPolygonConflateStandaloneTest/PoiPolygon1.osm and https://github.com/ngageoint/hootenanny/blob/develop/test-files/cmd/slow/PoiPolygonConflateStandaloneTest/PoiPolygon2.osm but the conflation seems to return only poi-to-poi reviews.  @bwitham should there be some poi-to-building reviews with these datasets?

**Comment by brianhatchl** [comment]
Nevermind.  I imported https://github.com/ngageoint/hootenanny/blob/develop/test-files/cmd/slow/PoiPolygonConflateStandaloneTest/output1.osm and see that there are POI to Polygon reviews.  Maybe the branch I'm running doesn't have poi-to-poly enabled for default conflation.

**Comment by sisskind** [comment]
@brianhatchl so this is good to go?

**Comment by brianhatchl** [comment]
No but there is data to test poi to poly reviews with.

**Comment by bwitham** [comment]
Ok, cool.  I thought there were a few reviews in that command test data.

**Comment by mattjdnv** [comment]
I merged @sisskind 's UI changes into develop so the POI Polygon option now appears in the advanced options.

**Comment by kweint** [comment]
With the data provided, point to poly is both present and quite functional.
