### ISSUE TITLE
Cannot remove added field to feature

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#647]
When a new field is added to a feature, you are unable to delete it (no trash icon appears).

![image](https://cloud.githubusercontent.com/assets/6191659/17905609/9fc4f3b0-6941-11e6-9f6c-f74d84ea0d26.png)

**Comment by briandaviddavidson** [comment]
@sisskind It's to be default iD behavior that the field persists when the trash icon is clicked. Should we modify this?

**Comment by curranMapper** [comment]
Works great, think it is ready to be closed.
