### ISSUE TITLE
Merge occurring in the wrong direction

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#67]
Conflating DC POI datasets, the red feature is Kalorama Post Office and the Blue Kalorama Park.  The arrow points in the correct direction from blue to red but the merge is reverse making the park POI the Post Office. 
![snapshot3](https://cloud.githubusercontent.com/assets/7560096/11601874/373b1818-9a8b-11e5-9daa-96e1a0c85090.png)
![snapshot4](https://cloud.githubusercontent.com/assets/7560096/11601875/3b5d4aba-9a8b-11e5-9059-d2d51e32b51c.png)

**Comment by bwitham** [comment]
Going to guess this was caused by the work I did in #28.  Which way the merge goes is determined by the number of outstanding review links the two POI's have.  Let me know if I can help...may be able to fix, but I'm not familiar with the arrow display code so would need some assistance there.

**Comment by brianhatchl** [comment]
The direction of the arrow is determined by the feature and againstFeature arguments:
```
                        var arw = { "type": "LineString",
                                    "coordinates": [ againstFeature.loc, feature.loc]
                        };
```
https://github.com/ngageoint/hootenanny-ui/blob/release/js/hoot/control/Conflicts.js#L530

So is the feature no longer always from the reference layer?

**Comment by brianhatchl** [comment]
Remove the direction indicator now, as the review relation does not capture feature vs againstFeature

**Comment by brianhatchl** [comment]
With the relation review refactor, the concept of feature vs. againstFeature held in the review table reviewitem is lost.  In the future, the POI merge tool should allow the user to choose the merge direction with Ctrl button or something.  However, the code to perform the update and delete for the two input POIs must also honor this setting.

**Comment by mjeffe98** [comment]
merge now occurs without the arrow.
