### ISSUE TITLE
During building conflation user not seeing data at the zoom levels they expect to see it

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#671]
See https://github.com/DigitalGlobe/VGI-team-repo/issues/207

This task has no dependencies.

**Comment by sisskind** [comment]
This may be solved when all users are on CentOS 7 and have mapnik available.

**Comment by bwitham** [comment]
Since we're not using this scenario for the HOT integration demo, this doesn't really belong in this epic anymore.  Can be dealt with at the VGI repo level at a later point, if desired.
