### ISSUE TITLE
Add data button bug

### ISSUE THREAD

**Issue by curranMapper** [ngageoint/hootenanny-ui#673]
Select "Add dataset", select "data type", select "import data", the button that is a folder on aws isn't there.

**Comment by briandaviddavidson** [comment]
@sisskind Do you know what the IDs are for all the various icons? Is there a master list somewhere?

**Comment by sisskind** [comment]
Can get to them through inkscape (by looking at the object properties) or take a look at id-sprite.json.  Let me know if you can't find what you are looking for.

**Comment by briandaviddavidson** [comment]
Got the folder icon showing. PR created: https://github.com/ngageoint/hootenanny-ui/pull/691

@curranMapper When this gets merged in, can you test it on AWS to make sure it's rendering properly?

**Comment by curranMapper** [comment]
Will do, thanks Brian!

**Comment by curranMapper** [comment]
I plan on being at NCE tomorrow so will verify this functionality on the highside.

**Comment by curranMapper** [comment]
Current version on highside is 2.27 vice newest 2.82 availble on AWS.  Will keep tracking and test once newest version is pushed on highside.

**Comment by sisskind** [comment]
@curranMapper have you gotten a chance to test?

**Comment by curranMapper** [comment]
No, still need to do so.  Anticipate being there tue or wed of next week.

**Comment by sisskind** [comment]
@curranMapper Just a reminder to test this one out.

**Comment by curranMapper** [comment]
Will be at NCE wed am, just took note to test this first thing and report back

**Comment by curranMapper** [comment]
This persists on highside of hoot.  Current version on highside remains 2.27, and doesn't appear to be updated with newer version yet, so imagine it will remain this way untill changes are pushed.  If changes are already pushed and I am missing something let me know.

**Comment by kweint** [comment]
Per @curranMapper above methodology, the button that is a folder is both present and functional on hoot nightly. Closing issue.
