### ISSUE TITLE
Right clicking in the sidebar gives zoom to layer button

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#674]
The zoom to layer context menu is appearing in the parameters/options/statistics area as opposed to only on the map.  This should not happen!

![image](https://cloud.githubusercontent.com/assets/6191659/18096841/a4463bb6-6ea9-11e6-9e1b-52d1de4c83a0.png)

**Comment by curranMapper** [comment]
works great.  Think its ready to close
