### ISSUE TITLE
When sidebar is expanded, 2 fields are too long in stats

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#676]
When the sidebar is expanded, some fields in the statistics table are too long.  They should either be wrapped or use an ellipsis.  See below for example:

![image](https://cloud.githubusercontent.com/assets/6191659/18097758/4964743e-6ead-11e6-8abb-f7071b2cee5b.png)

**Comment by briandaviddavidson** [comment]
So the text should always fit inside the text area, yes? Just want to make sure I have that right.

**Comment by briandaviddavidson** [comment]
The lines now wrap when the sidebar is expanded and shrunk. PR created: https://github.com/ngageoint/hootenanny-ui/pull/692

**Comment by jcp2236** [comment]
Looks good, text wraps when sidebar is expanded. Should we close?

**Comment by curranMapper** [comment]
agree with @jcp2236
