### ISSUE TITLE
Map-in-Map overview map not displaying review points

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#68]
Observed this any conflation, the overview points (yellow, red, green) that appeared before not appearing in the overview map.
![image](https://cloud.githubusercontent.com/assets/7560096/11602630/9d42d9b6-9a90-11e5-8026-3a02dee3194d.png)

Uncaught TypeError: Cannot read property '0' of undefined
@ map in map.js:71
(anonymous function) @d3.min.js:1

**Comment by brianhatchl** [comment]
@jchoi1267 looks like the rest.js part of this got whacked in the relation review merge :-(

**Comment by brianhatchl** [comment]
This whole method disappeared
https://github.com/ngageoint/hootenanny-ui/blob/4c59e27be08491b1d70f2027d05548a6fbcb0ceb/js/hoot/model/rest.js#L797

but I don't see it going away in the diff with the next commit so I'm confused,
https://github.com/ngageoint/hootenanny-ui/compare/4c59e27be08491b1d70f2027d05548a6fbcb0ceb...c4d4b5be6c0c71d8e176cbac1b95706aea374fe9#diff-f0adadf4d487dfd2e3e8e466cd757a10

**Comment by brianhatchl** [comment]
Here it is, this commit:
https://github.com/ngageoint/hootenanny-ui/compare/4c59e27be08491b1d70f2027d05548a6fbcb0ceb...dbef6c7add07626b6aab7c3ca9bd10969f6edca3#diff-f0adadf4d487dfd2e3e8e466cd757a10

**Comment by brianhatchl** [comment]
Here is a diff of the map-in-map review additions (along with some sorta unrelated egd plugin cleanup unfortunately) we can use to reconstruct what's missing.
https://github.com/ngageoint/hootenanny-ui/compare/8922e3ee171011f5f4907d818cd2ec7d4693d98c...4c59e27be08491b1d70f2027d05548a6fbcb0ceb

**Comment by jchoi1267** [comment]
Actually I have been working on fixing this. See ticket https://github.com/ngageoint/hootenanny/issues/45

**Comment by jchoi1267** [comment]
Committed  ngageoint/hootenanny#45 after code review will try to link it in

**Comment by jchoi1267** [comment]
@brianhatchl 
I have wired up the new rest end point and looks like it is working. Can you take a look at it?
BTW structure changed ittle where returned object looks like (if there is warning which happens total returned features are greater than limit set in service it will add "warning" json object)

{"total":122, "geojson":{}}

**Comment by mjeffe98** [comment]
@brianhatchl @jchoi1267 I am not getting the red dot (current unresolved review), just the yellow (unresolved) and green dots (resolved and merged).  Is that intended?

![image](https://cloud.githubusercontent.com/assets/7560096/11821669/8cd1fe80-a31f-11e5-94cf-3aeea3d1ef6e.png)

**Comment by brianhatchl** [comment]
Not so much intended, but unavoidable.  The red dots represented "locked" review items.  With the refactor of review items as relations, and the optimistic locking of osm changesets, review items are no longer ever in a "locked" state.  I was just thinking if there was an way to show the current review item in red if it wasn't too much of a hack (the map-in-map and request for review items as geojson currently has no knowledge of the current review item being viewed).  Is that worth adding?

**Comment by mjeffe98** [comment]
Personally I see value in it because it helps with orientation on the overview map i.e. if I know which dot represents which feature I am resolving, then it's easier to get a grasp on the spatial distribution of reviews.  Also since the zoom is no longer centered on the Reference POI but map extent containing both reviewed features, having the red dot would add further location awareness.  I say bring back the red dot as long as it is a sustainably supported hack that won't require overhead to support.
