### ISSUE TITLE
Display Tasking Manager overlays and ME/hoot data after launching hoot iD

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#680]
When using ME with HOT, the overlay info gets passed in as json (?) in a url from HOT.  We need to make the same thing work with hoot's iD.

This task depends on ngageoint/hootenanny-ui#679

**Comment by brianhatchl** [comment]
see https://github.com/ngageoint/hootenanny-ui/commits/taskmgr
