### ISSUE TITLE
Propagate user id to services on HOT task data save

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#684]
By passing the user id into the web services, which will then pass it into the core, we'll be able to keep track of which user saves the conflated data changeset back into MapEdit.

This task is dependent on ngageoint/hootenanny-ui#679 , ngageoint/hootenanny#869 , and ngageoint/hootenanny#1018.

**Comment by sisskind** [comment]
Related services task: ngageoint/hootenanny#1018

**Comment by bwitham** [comment]
will track this in #1018
