### ISSUE TITLE
Double-click sidebar is not working

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#686]
![image](https://cloud.githubusercontent.com/assets/6191659/18144765/48c2c780-6f96-11e6-8f3b-984c4a173e67.png)

When double-clicking the sidebar, it is setting the sidebar under the toolbar.  When you then slide, it resets itself.  Double-clicking the sidebar edge should set sidebar to the smallest possible size (initial).

**Comment by briandaviddavidson** [comment]
Should be fixed and good to go. PR has been created: https://github.com/ngageoint/hootenanny-ui/pull/687

**Comment by curranMapper** [comment]
Works beautifully.  Good to close. @sisskind
