### ISSUE TITLE
Create cucumber test to ensure highlights appear

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#693]
For both review mode and new edits.

**Comment by brianhatchl** [comment]
Review highlights (in blue and red) and Edited feature highlights (in yellow):
![screenshot from 2016-09-19 12 46 06](https://cloud.githubusercontent.com/assets/2600932/18640673/24a63258-7e67-11e6-8310-65bb44669b5b.png)

Edited feature highlights show edited but unsaved features and display when the map data option is checked:
![screenshot from 2016-09-19 12 47 58](https://cloud.githubusercontent.com/assets/2600932/18640737/68c629fc-7e67-11e6-885c-c5015f8d3b0c.png)

The css classes for these highlights, whose presence should be asserted in the cucumber tests, are .activeReviewFeature/.activeReviewFeature2 and .edited.unsaved respectively.
