### ISSUE TITLE
Do not allow conflation job if outstanding edits exist

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#694]
_I believe this should be the case, but please sound the alarms if I am wrong._

Hootenanny should prevent a conflation job from occurring within the UI if there are outstanding edits that have not been saved.  This is similar to preventing a user from moving on from a review if edits exist while in review mode.

CC @brianhatchl @mattjdnv @bwitham

**Comment by brianhatchl** [comment]
Sounds like correct desired behavior to me.
