### ISSUE TITLE
Reconfigure manage tab

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#7]
Change from having two rows (one of tabs and one of content) to two columns, similar to Google Settings page.

**Comment by sisskind** [comment]
Updated: Rows --> Column for tabs https://github.com/ngageoint/hootenanny-ui/commit/5b61d0fd867874347732eb9323be8b2ce2a73426

**Comment by sisskind** [comment]
@mjeffe98 @jchoi1267 @brianhatchl  Merged changes into develop (https://github.com/ngageoint/hootenanny-ui/commit/7b9621084fa924850d7252a942e070e83e19b468).  Testing would be limited to making sure functionality is there, but would prefer testing/review focused on UI/UX.

**Comment by sisskind** [comment]
![issue-7](https://cloud.githubusercontent.com/assets/6191659/11502585/ba45ea64-9809-11e5-859d-24f9467269e9.gif)

**Comment by mjeffe98** [comment]
Had a quick look through all of the tabs and they are working the same as the previous horizontal layout.
