### ISSUE TITLE
Paste tags buttons not updating UI tag fields in sidebar

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#700]
Ok, I tried it and the buttons do enable, but when clicked the tags in the sidebar are not updating.  (The change tags action does seem to be applied as the Undo button becomes enabled and there is a Change Tags step in the edit history.  I'll look into it.

**Comment by kweint** [comment]
Tested this in the latest hoot nightly build, and appears to be working.
