### ISSUE TITLE
Get translation server port from HootConfig.json instead of service call

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#702]
In order to configure clients of the translation server to use other url routes, change the UI code to get the port (or path) from HootConfig.json rather than querying from hoot-services.

**Comment by olearytd** [comment]
@brianhatchl @sisskind  for hoot's workflow - does the 'Ready for Test' label mean the tests needed to run before it goes into the code base and built into the nightly?

Or are they present already in the nightly build?

**Comment by brianhatchl** [comment]
Yes, the Ready for Test label means the issue fix or feature has been merged into the develop branch which is built and deployed nightly.

**Comment by olearytd** [comment]
ah cool, I'll try it out then!  Thanks

**Comment by sisskind** [comment]
@olearytd only thing I'll add is that the feature/bug fix may still need to be worked on if it doesn't pass the test.  if something doesn't seem right with it, feel free to comment and the dev will take a second look.

**Comment by olearytd** [comment]
will do!  I'm going to take a snapshot of the latest nightly and try plugging it into the VPC

**Comment by olearytd** [comment]
working!
