### ISSUE TITLE
Paste Attributes with translated tags copied will misbehave

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#708]
I think copied tags will need to be translated to OSM for proper behavior

**Comment by sisskind** [comment]
@brianhatchl is this something that is blocked by fixes to translation server, or can it be worked on?  If so, let's assign to @jcp2236 to offload your plate a bit.

**Comment by brianhatchl** [comment]
Sure.  So the issue is that when copying discrete translated tags (using the check mark in the raw tag editor), those get copied as-is in the translated schema.  If they are pasted, they are pasted directly onto the feature in translated form when they should be OSM.  (All tag translations are done on the fly and are really at the display level only.  In Hoot, only OSM+ tags are written and stored on features.)

It's possible to try and translate these selected tags back into OSM before writing them to the feature, but it's also likely that the subset of tags won't be translatable to anything by themselves.  If that's the case we may just have to disable copy discrete tags when a schema translation is in effect.

**Comment by jcp2236** [comment]
I'll start digging and get back to you with questions. I'm sure I'll have a few.

**Comment by brianhatchl** [comment]
See https://github.com/ngageoint/hootenanny-ui/blob/develop/js/id/ui/entity_editor.js#L235-L265 for the call to translate tags from translated schema to OSM.

Something similar needs to be done when copying translated tags which happens here https://github.com/ngageoint/hootenanny-ui/blob/develop/js/id/ui/raw_tag_editor.js#L63-L70.

It's possible that the copied subset of tags won't be able to translate, so some kind of error handling will occur, maybe in here https://github.com/ngageoint/hootenanny-ui/blob/develop/js/id/services/translationserver.js#L219-L249.

**Comment by sisskind** [comment]
@brianhatchl it should be slightly different than entity editor, though, since the entity does not make a difference, just the tags -- right?  

@jcp2236 may be worth looking at translation server to see if you can translate tags directly as opposed to using entity.

**Comment by brianhatchl** [comment]
@sisskind sort of, but right now the translation server does not offer a way to just translate just a set of tags, it can only translate an osm xml (the full entity) to and from the supported schemas.  Here is a link to the API for the translation server.  https://github.com/ngageoint/hootenanny/blob/develop/plugins/TranslationServer.MD  Right now it reflects the "as-is" that exists today.  In the future when we work towards a standalone npm module for translations, we could improve on the API.

I'm actually going to strikethrough (indication deprecation) some of the methods in that API doc that schema switcher no longer uses since it was refactored.

**Comment by sisskind** [comment]
@jcp2236 did you make a pull request for this yet?

**Comment by jcp2236** [comment]
Yeah, I did just now.

**Comment by kweint** [comment]
Tested and the issue appears to be resolved on hoot. I want to try one more data set just to be thorough, but it appears to be working a-ok.

**Comment by kweint** [comment]
Tested on additional datasets. Works on hoot nightly and hoot NOME -- closing issue ticket.
