### ISSUE TITLE
Edit Advanced Options Cucumber Test

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#723]
Edit Advanced Options Cucumber Test to include invalid entries.

**Comment by rmrice** [comment]
So some things that I think should be invalid are not outputting an invalid input warning??

![screenshot from 2016-10-04 15 22 11](https://cloud.githubusercontent.com/assets/17434033/19089008/892072f8-8a46-11e6-8f1c-7cf04d043970.png)

Is this correct? Should I just test for invalid input warnings where it currently works?

**Comment by brianhatchl** [comment]
Like we discussed, I think you should write tests that fail when the expected validation warning doesn't get triggered for these fields and then fix the UI code so validation does occur and these tests pass.

Also report back here if there's a way to loop in cucumber passing a list of invalid entries to used in a list of input field selectors.  If this isn't possible, testing this validation code may be better suited by a mocha test.

cc: @sisskind
