### ISSUE TITLE
"/" shortcut not working

### ISSUE THREAD

**Issue by curranMapper** [ngageoint/hootenanny-ui#729]
/ shortcut does not launch map inset

**Comment by brianhatchl** [comment]
Let's add a cucumber test for this too.

**Comment by briandaviddavidson** [comment]
Looks like the problem was due to the sidebar. The inset never got pushed over when the sidebar was changed to slide over the map. Should be fixed and visible now. It also slides with the map now.

**Comment by kweint** [comment]
Tested on hoot NOME and current release branch so far; "/" shortcut doesn't function in either environment at the moment.

**Comment by kweint** [comment]
"/" shortcut for inset doesn't function on the hoot nightly build.

**Comment by kweint** [comment]
"/" shortcut works on the latest hoot nightly build!
