### ISSUE TITLE
Searched, translated presets send wrong translation param to server when selected

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#730]
![screenshot from 2016-09-15 17 39 49](https://cloud.githubusercontent.com/assets/2600932/18568461/71497222-7b6b-11e6-8c47-2ec5c34141c4.png)

**Comment by brianhatchl** [comment]
@kweint If you change the tag schema and search for something and select a preset from the result, you should not see the network error in the dev console that's shown above.

**Comment by kweint** [comment]
@brianhatchl Could you elaborate on this issue? Is this something Curran or I could test, or is this more on the developer side of things? (noticed the cucumber test mentioned above)

**Comment by kweint** [comment]
@brianhatchl Good news, replicated your tag schema methodology, and did not get the network error
