### ISSUE TITLE
 Create conflation task project from Hoot

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#744]

**Comment by brianhatchl** [comment]
see https://github.com/ngageoint/hootenanny-ui/commits/taskmgr

**Comment by brianhatchl** [comment]
If the tasking manager url in hootConfig.json is set, display this context menu option for Hoot datasets

![screenshot from 2016-09-26 12 22 54](https://cloud.githubusercontent.com/assets/2600932/18962409/b0de706c-863e-11e6-8a89-f9463b9cbb2c.png)

**Comment by kweint** [comment]
Testing this ticket on hoot nightly build and the current release branch. Context menu pops up with right-click, but "Create Conflation Task Project" does not.

**Comment by kweint** [comment]
The above issue persists on hoot nightly build as well.

**Comment by brianhatchl** [comment]
Yeah, sorry, this ticket would need a tasking manager instance stood up for it to work.  And my customizations to the osm tasking manager aren't in the mapedit repo version yet.  This will take a lot more coordination to be testable.

**Comment by kweint** [comment]
Good news: The latest nightly hoot build displays the full Context Menu!
