### ISSUE TITLE
Enable POI merge in either direction

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#75]
See #67.  Merge used to occur from secondary feature to reference feature.  Review relation refactor changed this default behavior.  It would be useful to allow the user to choose to merge in either direction.

**Comment by brianhatchl** [comment]
I should mention that holding the Ctrl key down will reverse the merge direction when hovering over and clicking the merge button.  Reversing the merge direction is not possible when using the 'm' hot key.

**Comment by mjeffe98** [comment]
The behavior works as designed but for some reason in Chrome (windows/ubuntu) when you hold the ctrl key and hit the merge button a new browser tab opens.  I think this will negatively impact users as they'll end up with numerous tabs open during review.
