### ISSUE TITLE
Deleting folder with same name deletes data within all folders with that name

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#753]
When you have a folder with the same name as another folder, it will delete all data within any folder with that name.

**Comment by sisskind** [comment]
This is not an issue as I can not replicate.

**Comment by sisskind** [comment]
Replicated!  Deleting a child folder deletes all other sibling folders if it shares the name of the parent.

**Comment by kweint** [comment]
Attempted to replicate same name folder deleting issue. Could not get sibling folders to delete when parent folder was deleted.
