### ISSUE TITLE
Import individual shapefiles in folder

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#757]
Hootenanny shall allow a user to select a folder of shapefiles and import each individual dataset as a separate dataset within Hootenanny.  The user shall have the ability to select a custom syntax on import that would be added to each dataset.  For example, "_ABC" would be added to each dataset on import.

**Comment by sisskind** [comment]
First version will only support shapefile and OSM (.osm, .pbf).  Future iterations will support .zip, .fgdb, and GEONAMES as requirements dictate.

**Comment by sisskind** [comment]
Making update, since Firefox does not allow for ingesting a directory.  @kweint FYI for your benefit on this.  Firefox will have user select multiple files, while Chrome allows user to select entire folder in one shot.  Will chat with stakeholder tomorrow, as this may change to have Firefox and Chrome act the same (multi-select).

**Comment by kweint** [comment]
Tested this with smoketest data and shapefile data pulled off QGIS -- appears to work dandy in both Chrome and Firefox. @sisskind, are there any considerations before closing this ticket?
