### ISSUE TITLE
Provide option to add syntax to all datasets in bulk import

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#759]
Provide user the ability to add custom syntax on bulk import, either by new folder import or by current bulk import process.  For example, add "_ABC" to the end of each dataset.

Related to https://github.com/ngageoint/hootenanny-ui/issues/757

**Comment by kweint** [comment]
Wanted to test on various bulk import sizes (3 to 7 data sets), but appears to work a-ok!
