### ISSUE TITLE
Invalid inputs for some parameters in advanced options not registering

### ISSUE THREAD

**Issue by rmrice** [ngageoint/hootenanny-ui#765]
Discovered while creating cuke test for ngageoint/hootenanny-ui#723. This is a problem for "Element Cache Size" inputs.

![screenshot from 2016-10-04 15 22 11](https://cloud.githubusercontent.com/assets/17434033/19089008/892072f8-8a46-11e6-8f1c-7cf04d043970.png)

cc: @sisskind

**Comment by sisskind** [comment]
@rmrice found the bug.  Script does not currently validate against long data type.  Will fix and push in branch for your review.

**Comment by rmrice** [comment]
That's what I suspected but couldn't figure out how to make it work. Looking forward to seeing the fixed code. Thanks @sisskind :smile:

**Comment by sisskind** [comment]
It appears to be something weird where the services is reading those in as a long even though they are coded as int in the json file.  It's a good riddle right now.

**Comment by sisskind** [comment]
may need to be reviewed after changes to https://github.com/ngageoint/hootenanny/pull/1115

**Comment by kweint** [comment]
This issue has been resolved!
