### ISSUE TITLE
Schema switcher: tag dropped when choosing value with space in field

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#769]
For example, when using MGCP schema and adding the "Condition of Facility" field and choosing the "Fully Functional" value, the tag is dropped when translated back to OSM schema.  This is because the iD fields are programmed to replace spaces with underscores.  The translation code needs to "unsnake" these values before sending to translation server.

**Comment by kweint** [comment]
Hey @brianhatchl , tested this over a few data sets on hoot nightly -- my results are consistent with your above description.
