### ISSUE TITLE
Update Smoke Test for Bulk Import, Import Directory

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#773]
With the updates to the UI for #757 and #759, need to update smoke test to reflect these changes.

**Comment by sisskind** [comment]
@kweint was this done?

**Comment by sisskind** [comment]
@kweint Has smoke test been updated?

**Comment by sisskind** [comment]
@kweint Has smoke test been updated?

**Comment by kweint** [comment]
Hootenanny Smoke Test documentation has undergone the above updates, and several additional updates since the creation of this ticket. The most recent version of the Hootenanny Smoke Test can be found on the shared NOME Google Drive, or is available by request.
