### ISSUE TITLE
Sidebar Issues in Hoot Release (Firefox)

### ISSUE THREAD

**Issue by kweint** [ngageoint/hootenanny-ui#780]
The side bar is funky when adding layers or initiating conflation. Please see attached images: 
![screenshot from 2016-10-20 15-57-34](https://cloud.githubusercontent.com/assets/18521019/19576902/e9c0f8b4-96e2-11e6-8556-1f66dbdb4b94.png)
![screenshot from 2016-10-20 16-02-08](https://cloud.githubusercontent.com/assets/18521019/19576908/ed3d27c4-96e2-11e6-9b5a-8af95fd8007e.png)

**Comment by briandaviddavidson** [comment]
PR has been submitted and assigned to @jcp2236. It's going through tests now

**Comment by briandaviddavidson** [comment]
@kweint This has been merged in by @rmrice and should be in the `develop` branch

**Comment by brianhatchl** [comment]
Don't forget to update the hoot-ui submodule in hoot develop

**Comment by kweint** [comment]
@briandaviddavidson Tested it in hoot develop and I'm still running into the same sidebar issues.

**Comment by kweint** [comment]
Tested via hoot nightly -- the sidebar looks great! Awesome work :100:
