### ISSUE TITLE
Shift+R shortcut after dragging review bubble does not work

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#786]
The Shift+R shortcut works to show associated reviews with a feature, but once you drag a review bubble, it no longer is active.

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/VGI-team-repo/issues/304

**Comment by jcp2236** [comment]
This may be an issue where one feature is working as intended, but may be hindering the performance of a separate feature. Clicking the node pulls up the radial review menu, where you can use the Shift+R shortcut, but clicking anywhere outside the node (including a review bubble) closes the menu so you can't use the shortcut.

**Comment by sisskind** [comment]
After further review, I agree that this is expected behavior.  The Shift+R shortcut works on the **node** not the "bubble".
