### ISSUE TITLE
Import directory not putting files in specified new folder 

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#794]
I specified a new folder but if you look to the datasets behind the window, its not putting the datasets in that specific folder. See files with suffix in datasets:

![](https://cloud.githubusercontent.com/assets/16801432/20398889/0f0f0d28-acbd-11e6-808c-7f95d58c6ffc.png)

**Comment by sisskind** [comment]
Appears this is happening when trying to import within an existing folder.

**Comment by kweint** [comment]
Hey Josh, good news: this works as it should now! Closing ticket
