### ISSUE TITLE
CSS styling broken for some things

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#799]
When integrating the schema-switcher code, I changed the order that two css files are loaded because I was getting some undesirable style inheritance.

https://github.com/ngageoint/hootenanny-ui/commit/2c6ed42167e355459077c4405b71d45791a30109#diff-eacf331f0ffc35d4b482f1d15a887d3b

However, some styling was adversely affected by this change, such as the review tag table losing it's transparency:
![screenshot from 2016-11-29 12 08 04](https://cloud.githubusercontent.com/assets/2600932/20720265/8328aa52-b62c-11e6-92c2-7ebfc50a3777.png)

**Comment by sisskind** [comment]
FYI @kweint

**Comment by kweint** [comment]
Attempted to replicate the issue on hoot nightly on multiple occasions --> the review tag table looks good :+1:
