### ISSUE TITLE
Make Append to ESRI FGDB Template option disabled by default

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#8]
When the "append to template..." option is checked in export FGDB, I've noticed that exports can sometimes file due to missing dependencies.  We should either add a check for the dependency or just have it unchecked by default so that when users select FGDB it doesn't throw an exception like the one below.

2015-11-05 19:25:14 ERROR JobResource:494 - Failed to execute.Error running osm2ogr.....

**Comment by sisskind** [comment]
Commit: https://github.com/ngageoint/hootenanny-ui/commit/ce0efeaa6e4c31e0b43e28579f26af591bdb520a

**Comment by mjeffe98** [comment]
@sisskind is this merged and sync'd?  I was seeing it enabled by default in the latest.  will check again tomorrow.

**Comment by sisskind** [comment]
@mjeffe98 did this morning.
