### ISSUE TITLE
Following conflation, cannot access palette to change color

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#822]
After running a conflation job, you cannot access the palette by clicking on the database icon next to the layer name.

**Comment by sisskind** [comment]
@brianhatchl did this get fixed indirectly?  Ran a conflation job and am able to access palette.

![822](https://cloud.githubusercontent.com/assets/6191659/21952011/1fc0dfd0-d9df-11e6-990a-77fe2261d1f2.gif)

**Comment by brianhatchl** [comment]
Must have, or else I broke it temporarily while fixing whatever I was working on when I noticed it.
