### ISSUE TITLE
Dataset folder icon is no longer clickable to expand/collapse folder

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#83]
Now only the folder label can be clicked to expand the folder.  This threw me for a while.  Anyway to restore folder icon clickability?

**Comment by sisskind** [comment]
@brianhatchl Will fix -- but think it was always this way.

**Comment by sisskind** [comment]
![folder-issue](https://cloud.githubusercontent.com/assets/6191659/11728499/3fa0a05a-9f58-11e5-9b5c-a1ac61859b10.gif)

**Comment by sisskind** [comment]
@mjeffe98 Ready for Testing

**Comment by mjeffe98** [comment]
Was the folder icon supposed to change depending on whether it was expanded or collapsed?

**Comment by mjeffe98** [comment]
Closing since the current behavior is as described in the issue.
