### ISSUE TITLE
Background Settings//Attribute Box Bug

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#830]
**clicking Backround Settings, then trying to scroll on the blue/red attribute box results in re-opening Background settings**

while reviewing a feature, clicking Backround Settings, then closing background settings, then trying to scroll on the blue/red attribute box results in re-opening Background settings. When reviewing if I click on the blue/red attribute box without clicking on background settings first, it works fine.

**Comment by sisskind** [comment]
@briandaviddavidson @rmrice what is the status of this ticket? Can we close since parent is closed as well?

**Comment by rmrice** [comment]
I think so since it was confirmed no longer an issue.
