### ISSUE TITLE
Add poi/polygon and poi/poi conflation options to advanced opts

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#836]
Currently, these would be the most useful to add:

* **poi.polygon.name.score.threshold** - default = 0.8; range: .01 to 1.0
* **poi.polygon.type.score.threshold** - default = 0.7; range: .01 to 1.0
* **poi.polygon.match.distance.threshold** - default = 5; range: 0 to 5000
* **poi.polygon.review.distance.threshold** - default = 125; range: 0 to 5000; must always have a larger value than the match dist thresh
* **poi.polygon.review.if.matched.types** - this should be a list of key=value pairs; the user can add as many as they want; passed to services as semicolon delimited list, like: -D poi.polygon.review.if.matched.types="key1=value1;key2=value2"; this one depends on https://github.com/ngageoint/hootenanny/issues/1410
* **poi.ignore.type.if.name.present** - boolean field; default = false; this one depends on https://github.com/ngageoint/hootenanny/issues/1409

**Comment by bwitham** [comment]
@sisskind @curranMapper 

Josh, Curran is going to need this one done for the poi/poly VGI work he is doing.  I put it into the next Sprint in case anyone is available to do it.  thanks.

**Comment by sisskind** [comment]
10-4

**Comment by sisskind** [comment]
@Bwitham what skills does one need to knock this out?

Cc: @mattjdnv

**Comment by bwitham** [comment]
UI - its adding new advanced options to the UI

**Comment by sisskind** [comment]
@bwitham @curranMapper is the bulleted list above still relevant to add to advanced options?

**Comment by bwitham** [comment]
It is.

**Comment by bwitham** [comment]
@curranMapper expressed interest today in picking poi to poly back up for a demo, so maybe we work on this next sprint...

**Comment by sisskind** [comment]
@bwitham @curranMapper Can do -- will crank out for next sprint.

**Comment by curranMapper** [comment]
Awesome, some more background on this, with a planned trip to ORNL July 17-19ish timeframe, Will and Ed wanted to demo the poi/poly capability in Hoot.

**Comment by sisskind** [comment]
Sounds good.  I will front load so that we can get a new version of Hoot (even if testing) available for that trip.

@sputnam is that feasible?

**Comment by sputnam** [comment]
@sisskind if we plan in a couple weeks to create and test that release that should be feasible.

**Comment by sisskind** [comment]
@sputnam @olearytd will get commits to develop.  @curranMapper in worse case may be able to use testing site when at ORNL.

**Comment by sisskind** [comment]
Need to add validation for semi-colon string and review distance > match distance.

**Comment by sisskind** [comment]
Updated validation for the review vs. match; need to do so for string.  @bwitham if a bad string is passed, does the entire conflation job choke or just that variable?

**Comment by bwitham** [comment]
Cool, thanks.  

I just checked by passing in bad string values for the numeric, boolean, and list config option inputs and it seems to be swallowing them and either using a default value...or who knows what value, since the results output results I'm getting back are way different.  That's definitely not good, so I'll fix the validation when I get back from vacation.  For now, I guess its undefined behavior.

https://github.com/ngageoint/hootenanny/issues/1657

**Comment by sisskind** [comment]
Is this still something for demo?  If so, will not be able to get a full release out but could use on nightly version.
