### ISSUE TITLE
Zoom to conflation review should have maximum zoom level

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#84]
The map extent for review features that are very close together (DC POI datasets) requires zooming out to make sense of the basemap imagery.  Set a minimum zoom level for the review item exent.

**Comment by sisskind** [comment]
@mjeffe98  Ready for test

**Comment by mjeffe98** [comment]
Tested on Hootenanny iD Editor - Version: 0.2.19-77-g9244f18 and appeared to be functioning properly.  On today's "deployed" build (Hootenanny iD Editor - Version: 0.2.19-74-gd595e7d) the review zooming in too far for the basemap imagery service.
