### ISSUE TITLE
Duplicate folder names at same level in structure

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#85]
It's possible to create duplicate folder names when uploading a dataset and entering text in the New Folder Name box.

**Comment by sisskind** [comment]
@brianhatchl Do you mean duplicate folders within the same folder, or duplicate folder names in general?

**Comment by brianhatchl** [comment]
![screenshot from 2015-12-10 14 06 34](https://cloud.githubusercontent.com/assets/2600932/11726449/afc0b912-9f4c-11e5-9e34-bf64ccd8da4c.png)

**Comment by sisskind** [comment]
@brianhatchl Thanks -- will fix.

**Comment by sisskind** [comment]
Updated:
* Cannot create duplicate via 'Add Folder' button
* Cannot create duplicate via 'Add Folder' context menu
* Cannot create duplicate via 'Add Dataset'
* Cannot create duplicate via Conflation job

**Comment by sisskind** [comment]
@mjeffe98 Ready for Testing

**Comment by mjeffe98** [comment]
warning pop up now preventing adding a duplicate folder name.
