### ISSUE TITLE
Basemap Issue During Hoot Smoketest

### ISSUE THREAD

**Issue by kweint** [ngageoint/hootenanny-ui#867]
Following the below methodology (DigitalGlobe WorldView-2 image
over the Roman Colosseum), on step 8 the pop-up request was unable to zoom into the base layer (I had to manually zoom and pan around to find it). 

1. Select the Basemaps tab and click on the ‘Add New Basemap’ button. 
2. Select the raster file (TIF, Geotiffs work best)
3. Enter a name for your basemap i.e. how you would like it to appear from the Background layers list. File name is used if empty. 
4. Click ‘Publish’
5. When complete the Basemap will appear listed with an eyeball icon that has a slash through it. Click on eye icon to make the basemap appear as available from list of background layers.
6. Click on return to map and select background or type ‘b’
7. Select the basemap from list available background services (RomanColoseum_…)
8. **Click ‘OK’ in pop-up requesting to zoom to base layer.** 

Would someone mind trying to replicate this in hoot release?

**Comment by brianhatchl** [comment]
I'm able to reproduce using develop branch.  It seems the problem is the order of the x and y coordinates in the url hash is reversed.  Clicking zoom to sets the hash to `map=18.04/41.89022/12.49240` when the Colosseum is at `map=18.04/12.49240/41.89022`.

**Comment by kweint** [comment]
Thank you for replicating and troubleshooting the problem Brian!

**Comment by sisskind** [comment]
@kweint can you pull develop and test?

**Comment by brianhatchl** [comment]
@kweint bump

**Comment by sisskind** [comment]
@kweint ping
