### ISSUE TITLE
Multiple popups warning that a review contains more than two members

### ISSUE THREAD

**Issue by mschicker** [ngageoint/hootenanny-ui#871]
When reviewing network conflation merge conflicts, it is not uncommon for me to get this popup 5 or more times in a row:

![image](https://cloud.githubusercontent.com/assets/10749517/24516916/92f53556-1539-11e7-91d0-64ac7af227e2.png)

It is very annoying. One popup would be sufficient. Possibly I'm seeing this popup for each member of the review beyond the second...

**Comment by brianhatchl** [comment]
Converted to alert div that does not require user interaction.

Ready for test.
