### ISSUE TITLE
Cookie Cut Conflation Error

### ISSUE THREAD

**Issue by kweint** [ngageoint/hootenanny-ui#889]
After attempting to perform a cookie cutter/horizontal conflation on district_of_columbia_highway and Street_Centerlines_Light (see below procedure) I was met with an empty map and the following error message each time: 

5/25/2017, 4:23:34 PM: Map is empty.
Error
    at Object.<anonymous> (http://localhost:8888/hootenanny-id/js/id/core/connection.js:98:56)
    at Object.event (http://localhost:8888/hootenanny-id/js/lib/d3.v3.js:584:40)
    at XMLHttpRequest.respond (http://localhost:8888/hootenanny-id/js/lib/d3.v3.js:2116:22)

**Procedure:** 
1. Ingest DC Street datasets using the recently created custom translation files. Note the different Translation Schema files used to import each dataset. 
2. - district_of_columbia_highway.zip
3. - Street_Centerline_Light.shp
4. Return to Map and select the Street Centerlines Light as the Reference Dataset, dc highway osm as the Secondary dataset.
5. Click ‘Conflate’
6. Change the value for Type to Cookie Cutter & Horizontal.
7. Hit Conflate. Note the conflation time will vary depending on the specs of the machine. This example took about 5-10 min to run locally.
8. 50+ reviews should appear. You can resolve them all by clicking resolve all or leave them as is (unresolved) for multi-user step.

**Comment by brianhatchl** [comment]
This appears to be the cause of the empty output map (from stdout):
>21:36:57.890 INFO .../cpp/hoot/core/ops/NamedOp.cpp( 57) Applying operation: hoot::CookieCutterOp
21:36:57.892 WARN ...nflate/AlphaShapeGenerator.cpp( 57) Alpha Shape area is zero. Try increasing the buffer size and/or alpha.
21:36:57.893 WARN ...core/conflate/CookieCutter.cpp( 77) Cutter area is zero. Try increasing the buffer size or check the input.

**Comment by brianhatchl** [comment]
These seem to be the operative cookie cutter params used by default:
>-D unify.pre.ops=hoot::CookieCutterOp 
-D cookie.cutter.alpha=2500
-D cookie.cutter.alpha.shape.buffer=0
-D cookie.cutter.output.crop=false

**Comment by brianhatchl** [comment]
cc: @bwitham @mschicker @bmarchant @mattjdnv

**Comment by bwitham** [comment]
This is a test sequence that has worked with these identical inputs in the past?  It tells you exactly what to do:  increase the buffer size or the alpha. :-)  Are those configurable in the UI?  But maybe doing that will still result in the same error anyway...so may not matter.

The core part of the workflow should have either a command slow/glacial or a regression smoke test created for it as a result of this work, so we can get test feedback on it more often than just every release.  If there's a master list of UI smoke tests available, publish it somewhere.  I converted the core part of a bunch of Jeffe's tests awhile back to regression smoke tests that run every night.

**Comment by brianhatchl** [comment]
I believe this conflation produced data with default inputs before.

I tried with 1000 for alpha shape buffer and even clipped down the reference (to be inserted, seems like it's kinda backwards) dataset.  Always got the alpha shape is zero message.  The alpha param does not seem to be exposed through the UI.

The two datasets are almost the same extent, which I thought was strange.

**Comment by bwitham** [comment]
Where's the source data for this?

**Comment by brianhatchl** [comment]
slacked to you

**Comment by bwitham** [comment]
thank you.

**Comment by bwitham** [comment]
I'm not seeing any road attributes on the data when loaded...therefore no way for hoot to conflate them.  Maybe I have the wrong data?  translation issue going on here...

**Comment by brianhatchl** [comment]
@bwitham Good catch.  I think the data used here are the result of an earlier smoke test step to import them from shapefile or gdb so maybe this is actually an error in translation.

@kweint Can you slack me the original data files that were imported and provide the translation steps used to ingest?

**Comment by kweint** [comment]
Absolutely! Give me a moment to pull that all up.

**Comment by kweint** [comment]
@brianhatchl Attached please find the original zip files for the dc cookie cut data, and a PDF with the translation assistant methods. If you have any questions, please let me know. 

[TranslationAssistantMethodology.pdf](https://github.com/ngageoint/hootenanny-ui/files/1038789/TranslationAssistantMethodology.pdf)

[district_of_columbia_highway.zip](https://github.com/ngageoint/hootenanny-ui/files/1038775/district_of_columbia_highway.zip)
[dc_streetcenterline.zip](https://github.com/ngageoint/hootenanny-ui/files/1038774/dc_streetcenterline.zip)

**Comment by bwitham** [comment]
got the data thanks, @kweint.  Data was visible just not translated, but now I'll translate it with the pdf instructions.

**Comment by brianhatchl** [comment]
I found a bug in the services code where the ingest command was using the wrong location for custom scripts.  Working with Katie now to see if that's reproducible in the release branch and if so maybe a custom translation script was not selected on input, which would have caused the imported features to have no tags.

**Comment by bwitham** [comment]
Ok.  I created the custom translations with TA but got errors when trying to ingest using the translations...so may be the same thing.  I cookie cut conflated from the command line using the same translations and was able to conflate without getting the alpha shape warnings, but I haven't looked closely at the actual conflated output yet.
