### ISSUE TITLE
Map-in-map doesn't always redraw after main map pans/zooms

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#9]
This seems like it's due to the map drawn event not firing due to a changes we may have made to https://github.com/ngageoint/hootenanny-ui/blob/develop/js/id/renderer/map.js.

https://github.com/ngageoint/hootenanny-ui/blob/develop/js/id/ui/map_in_map.js#L260

**Comment by brianhatchl** [comment]
I realized now that his occurs when there is no dataset loaded in the map.  The mapinmap works as expected when a dataset is present

**Comment by sisskind** [comment]
![issue9](https://cloud.githubusercontent.com/assets/6191659/11250091/c57905d0-8df8-11e5-8faf-41d8da5c63e9.gif)

**Comment by sisskind** [comment]
@brianhatchl can you review and merge if kosher?

Commit: https://github.com/ngageoint/hootenanny-ui/commit/1a69bfe858b3dc3680c8835ac5b4bbeff0eba22c

Compare: https://github.com/ngageoint/hootenanny-ui/compare/develop...issue-9

**Comment by brianhatchl** [comment]
yup

**Comment by brianhatchl** [comment]
It works, but what to you think about the alternate implementation using map 'move' event handler?
https://github.com/ngageoint/hootenanny-ui/compare/develop...issue-9

Also, it seems like when there is data in the map, redraw will get called twice, once on 'move' event and again on 'drawn' event.

**Comment by sisskind** [comment]
Will double check when data is loaded -- was looking at when data wasn't in map based on previous comment.

Much prefer your implementation used above.

**Comment by sisskind** [comment]
Good catch.  Will update and merge.

**Comment by sisskind** [comment]
@mjeffe98 ready for test.

**Comment by mjeffe98** [comment]
appears to be working fine on my dev instance. will close.
