### ISSUE TITLE
Review feature (red/blue) halos are not removed when last review is resolved

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#90]

**Comment by mjeffe98** [comment]
Looks like I have the updated Conflicts.js but the last red/blue halos do not get removed when last review is resolved.

**Comment by brianhatchl** [comment]
I swear it had worked, but you're right, I had to clear another couple vars.  We need to refactor #82 this file.

**Comment by mjeffe98** [comment]
This is now working in latest develop build.
