### ISSUE TITLE
Folders are not case sensitive

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#91]
Treat all folder names as equal regardless of case of letters to avoid duplication of folder names.

**Comment by sisskind** [comment]
@mjeffe98 Ready for test

**Comment by mjeffe98** [comment]
Looking at this in Hootenanny iD Editor - Version: 0.2.19-84-g70e5640, I can't add a duplicate folder even though the case is different e.g. TEST2 and tesT2. If we supported case sensitivity in the folder names I would be able to maintain both.  Is that correct @sisskind ?

**Comment by mjeffe98** [comment]
@sisskind  Looks like its not working i.e. I cannot add both test and TesT as folders at the same level

**Comment by mjeffe98** [comment]
This was just a communication issue.  "Case sensitivity" is supported in order to detect whether there is duplication of names not so that we can have the same folder name but in varying case.
