### ISSUE TITLE
Refactor Folder.js / datasettable structure

### ISSUE THREAD

**Issue by rmrice** [ngageoint/hootenanny-ui#952]
Once https://github.com/ngageoint/hootenanny-ui/pull/951 is merged in, we will want to make improvements for the UX of the dataset table. Functionality we want:

- Be able to sort by last accessed date
- Multi-select using shift key (right now you can only multi-select by ctrl+ click individual datasets)
- Multi-select using checkboxes for bulk deletion

any others? cc @sisskind @brianhatchl

**Comment by sisskind** [comment]
@rmrice Are we putting this on hold until Hoot 2.0?

**Comment by rmrice** [comment]
Yes, hold off until we start refactoring for hoot 2.0.

**Comment by rmrice** [comment]
refs #591 #595
